Repository jetty/jetty.project, pull requests merged in 2018-11, with the labels that each got.

#3050 Issue #3049 Warn on common SslContext vulnerable configurations
  jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
  jetty-server/src/main/config/etc/jetty-ssl-context.xml
  jetty-server/src/main/config/modules/https.mod
  jetty-server/src/main/config/modules/ssl.mod
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
Labels: wip

#3052 Issue #3051 - New Simplified Jenkinsfile
  Jenkinsfile
Labels: Build

#2859 Issue #2858 upgrade jnr-unixsocket to 0.19
  jetty-unixsocket/src/main/java/org/eclipse/jetty/unixsocket/UnixSocketEndPoint.java
  pom.xml
Labels: wip

#3088 Revert backport of HttpClient executor bean handling.
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
Labels: High Priority

#3096 Using new Declarative Jenkinsfile format
  Jenkinsfile
Labels: Build

#2670 Issue #2646 - Better handle concurrent calls to change session id and invalidate within a context
  jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionCache.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DefaultSessionCacheTest.java
Labels: do-not-merge, wip
