Repository jetty/jetty.project, pull requests merged in 2018-08, with the labels that each got.

#2770 Issue #2768 - JSR356 Session.getUserProperties() is null during @OnOpen
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/ConfiguratorTest.java
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EchoCaptureHandler.java
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EndpointEchoClient.java
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/EndpointEchoTest.java
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/MessageQueue.java
  jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/samples/EchoStringEndpoint.java
Labels: Test

#2825 Issue #2824 - Request.getParameters() should not reparse or recreate _parameters Map
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
Labels: Bug

#2827 Issue #2787 BadMessage if bad query detected in dispatcher
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DispatcherTest.java
Labels: Sponsored

#2816 Issue #2811 - Dump fix JreDisabled:java.security to JVM:disabled
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslSelectionDump.java
  jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java
Labels: Enhancement, Security

#2818 Issue #2817 - Client SSL Defaults
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/DefaultHttpClientProvider.java
Labels: Enhancement, Security

#2812 Issue #2775 LowResourceMonitor extendable
  jetty-server/src/main/config/etc/jetty-lowresources.xml
  jetty-server/src/main/java/org/eclipse/jetty/server/LowResourceMonitor.java
  jetty-server/src/test/java/org/eclipse/jetty/server/CustomResourcesMonitorTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/LowResourcesMonitorTest.java
Labels: wip
