Repository jetty/jetty.project, pull requests merged in 2019-10, with the labels that each got.

#4081 Remove unnecessary Connection upgrade check
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
Labels: Bug

#4145 Fixing #4144 - handle wrapped requests better
  jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/ForwardedSchemeHeaderRule.java
  jetty-security/src/main/java/org/eclipse/jetty/security/authentication/DigestAuthenticator.java
Labels: Bug

#4143 Fixes #4141 - Servlet not async + async Filter + wrapped request
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletWrapperTest.java
Labels: Bug, High Priority

#4149 Issue #4121 - ThreadFactory support in QTP
  jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
  jetty-util/src/test/java/org/eclipse/jetty/util/thread/ThreadFactoryTest.java
Labels: Enhancement

#4095 Issue #3734 - throw ISE for WebSocket suspend after close
  jetty-websocket/jetty-websocket-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
  jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/SuspendResumeTest.java
  jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java
Labels: Bug

#4116 Fixes #4115 - Drop HTTP/2 pseudo headers.
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpHeader.java
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/HTTP2Test.java
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/TrailersTest.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Flusher.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/FrameGenerator.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/Generator.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/HeadersGenerator.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/generator/PushPromiseGenerator.java
  jetty-http2/http2-common/src/test/java/org/eclipse/jetty/http2/frames/FrameFloodTest.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackContext.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackEncoderTest.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackPerfTest.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackTest.java
  jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2Test.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
Labels: Bug

#4211 Issue #4208 - Content-Length in 304
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpManyWaysToCommitTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java
Labels: Specification

#4205 Fixes #4203 and #4204 - Transfer-Encoding + Content-Length behaviors
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/rfcs/RFC2616BaseTest.java
Labels: Bug, Specification, Sponsored
