Repository jetty/jetty.project, pull requests merged in 2019-12, with the labels that each got.

#4377 Issue #4376 Async Content Complete
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
  jetty-server/src/test/java/org/eclipse/jetty/server/AsyncCompletionTest.java
Labels: Sponsored

#4417 Issue #4415 - Addressing Gzip Decoding of large files
  jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java
  jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java
Labels: Bug

#4424 Fixes #4421 - HttpClient support for PROXY protocol.
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
  jetty-client/src/main/java/org/eclipse/jetty/client/Origin.java
  jetty-client/src/main/java/org/eclipse/jetty/client/ProxyConfiguration.java
  jetty-client/src/main/java/org/eclipse/jetty/client/ProxyProtocolClientConnectionFactory.java
  jetty-client/src/main/java/org/eclipse/jetty/client/api/Request.java
  jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientProxyProtocolTest.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ClientConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ProxyConnectionTest.java
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTest.java
Labels: High Priority
