Repository jetty/jetty.project, pull requests merged in 2019-03, with the labels that each got.

#3445 Issue #3429 - Adding WebAppProvider.scan() method to JMX
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/App.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/AppProvider.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentManager.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/DebugListenerBinding.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/bindings/GlobalWebappConfigBinding.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/graph/Graph.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/jmx/DeploymentManagerMBean.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ScanningAppProvider.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/jmx/WebAppProviderMBean.java
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/JmxServiceConnection.java
Labels: Sponsored

#3441 Issue #3440 Stop on Unavailable
  examples/embedded/src/main/java/org/eclipse/jetty/embedded/LikeJettyXml.java
  examples/embedded/src/main/java/org/eclipse/jetty/embedded/OneWebApp.java
  jetty-proxy/src/main/java/org/eclipse/jetty/proxy/ConnectHandler.java
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/HouseKeeper.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/GracefulStopTest.java
  jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java
  jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java
  jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketServerFactory.java
Labels: Sponsored

#3431 Issue #3425 upgrade conscrypt to 2.0.0 and get rid reflect usage
  jetty-alpn/jetty-alpn-conscrypt-client/src/main/java/org/eclipse/jetty/alpn/conscrypt/client/ConscryptClientALPNProcessor.java
  jetty-alpn/jetty-alpn-conscrypt-server/pom.xml
  jetty-alpn/jetty-alpn-conscrypt-server/src/main/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptServerALPNProcessor.java
  jetty-alpn/jetty-alpn-conscrypt-server/src/test/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptHTTP2Server.java
  jetty-alpn/jetty-alpn-conscrypt-server/src/test/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptHTTP2ServerTest.java
  jetty-alpn/jetty-alpn-conscrypt-server/src/test/resources/keystore
  jetty-alpn/jetty-alpn-conscrypt-server/src/test/resources/keystore.jks
  jetty-documentation/src/main/asciidoc/configuring/connectors/configuring-ssl.adoc
  jetty-home/src/main/resources/modules/conscrypt.mod
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-http2.xml
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
  pom.xml
Labels: wip

#3461 Jetty 9.3.x gzip request customizer
  jetty-server/src/main/config/etc/jetty-gzip-inflate.xml
  jetty-server/src/main/config/modules/gzip-inflate.mod
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipRequestCustomizer.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
Labels: Enhancement, Sponsored
