Repository jetty/jetty.project, pull requests merged in 2019-02, with the labels that each got.

#3330 Issue #3329 Hazelcast remove session fails
  jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java
Labels: Bug

#3376 Add jdk12 build in Jenkinsfile
  Jenkinsfile
  jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTLSTest.java
  jetty-home/pom.xml
  jetty-infinispan/pom.xml
  jetty-util/src/test/java/org/eclipse/jetty/util/LazyListTest.java
  pom.xml
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSessionScavengingTest.java
Labels: wip

#3393 Jetty 9.4.x 3373 gzip oom
  jetty-client/src/main/java/org/eclipse/jetty/client/ContentDecoder.java
  jetty-client/src/main/java/org/eclipse/jetty/client/GZIPContentDecoder.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
  jetty-client/src/test/java/org/eclipse/jetty/client/GZIPContentDecoderTest.java
  jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientGZIPTest.java
  jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java
  jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java
  jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AsyncMiddleManServlet.java
  jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java
Labels: Sponsored
