Repository jetty/jetty.project, pull requests merged in 2019-11, with the labels that each got.

#4085 Issue #3863 - Enforce use of SNI
  jetty-server/src/main/config/etc/jetty-ssl-context.xml
  jetty-server/src/main/config/etc/jetty-ssl.xml
  jetty-server/src/main/config/modules/ssl.mod
  jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SniSslConnectionFactoryTest.java
  jetty-server/src/test/resources/jetty-logging.properties
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
Labels: Enhancement

#4289 Issue #4287 - Move getUriLastPathSegment() to URIUtil
  jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
  jetty-util/src/test/resources/test-base-resource.jar
  jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/WebInfConfigurationTest.java
Labels: Enhancement

#4017 Fixes #3951 - Consider adding demand API to HTTP/2.
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/DataDemandTest.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java
Labels: Enhancement

#4326 Issue #4325 - X509ExtendedKeyManager exceptions on non-Server SSL
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
  jetty-util/src/test/java/org/eclipse/jetty/util/ssl/X509Test.java
Labels: Bug

#4335 Issue #4334 - Improve testing of ErrorHandler behavior
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
Labels: Test

#4339 Issue #2634 fix occasional exception stack trace in UnixSocketTest
  pom.xml
Labels: Test

#4336 Fixes #2195 - Jetty start.jar can expand properties in JVM Args now
  jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java
Labels: Enhancement
