Repository jetty/jetty.project, pull requests merged in 2019-08, with the labels that each got.

#3946 Issue #3804 CDI integration rename
  jetty-cdi/src/main/config/etc/cdi/jetty-cdi.xml
  jetty-cdi/src/main/config/etc/cdi/jetty-cdi2.xml
  jetty-cdi/src/main/config/modules/cdi-decorate.mod
  jetty-cdi/src/main/config/modules/cdi-spi.mod
  jetty-cdi/src/main/config/modules/cdi.mod
  jetty-cdi/src/main/config/modules/cdi2.mod
  jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiDecoratingListener.java
  jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiServletContainerInitializer.java
  jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java
  jetty-deploy/src/main/config/modules/decorate.mod
  jetty-distribution/pom.xml
  jetty-distribution/src/main/resources/demo-base/webapps/ROOT/index.html
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DecoratingListener.java
  jetty-webapp/src/main/java/org/eclipse/jetty/webapp/DecoratingListener.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java
Labels: High Priority

#3961 Fixed decoration changes for #3804
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java
  tests/test-webapps/test-cdi-common-webapp/src/main/webapp/index.html
  tests/test-webapps/test-owb-cdi-webapp/pom.xml
  tests/test-webapps/test-owb-cdi-webapp/src/main/webapp/WEB-INF/jetty-web-owb.xml
Labels: High Priority

#3993 Add WebAssembly MIME type support
  jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
Labels: do-not-merge

#3950 Issue #3040 - Allow RFC6265 Cookies to include optional SameSite attribute
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
Labels: Enhancement

#4002 Fixes #3989 - Selector restart with custom ManagedSelector
  jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java
Labels: Enhancement

#3995 Fixes #3983 - JarFileResource directory listing is invalid
  jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarFileResource.java
  jetty-util/src/test/java/org/eclipse/jetty/util/resource/JarResourceTest.java
  jetty-util/src/test/resources/jar-file-resource.jar
Labels: Bug

#3994 Fixes #3985 - Updates to CookieCutter to reject no-equal cookies
  jetty-server/src/main/java/org/eclipse/jetty/server/CookieCutter.java
  jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutterTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/CookieCutter_LenientTest.java
Labels: Bug

#3984 Issue #3936 Provide write-through modes for the NullSessionCache
  jetty-server/src/main/config/etc/sessions/session-cache-null.xml
  jetty-server/src/main/config/modules/session-cache-null.mod
  jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionDataStore.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/NullSessionCache.java
  jetty-server/src/main/java/org/eclipse/jetty/server/session/NullSessionCacheFactory.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestSessionDataStore.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/NullSessionCacheTest.java
Labels: Enhancement

#3912 Issue #3806 - Make Async sendError fully Async
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferOutputStream.java
  jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
  jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/ResponsePatternRule.java
  jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/ValidUrlRule.java
  jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/ResponsePatternRuleTest.java
  jetty-security/src/test/java/org/eclipse/jetty/security/SpecExampleConstraintTest.java
  jetty-security/src/test/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticatorTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ShutdownHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/AsyncCompletionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpInputAsyncStateTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpManyWaysToAsyncCommitBadBehaviourTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpManyWaysToAsyncCommitTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
  jetty-server/src/test/java/org/eclipse/jetty/server/LocalAsyncContextTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/NcsaRequestLogTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/SecuredRedirectHandlerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SniSslConnectionFactoryTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncContextTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncListenerTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletIOTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/CustomRequestLogTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ErrorPageTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
  jetty-servlets/src/main/java/org/eclipse/jetty/servlets/DoSFilter.java
  jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java
  jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketConnectionStatsTest.java
  jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketNegotiationTest.java
  jetty-websocket/websocket-server/src/test/java/org/eclipse/jetty/websocket/server/WebSocketInvalidVersionTest.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/BadAppTests.java
Labels: Bug

#4010 Issue #4006 Fix ClusteredSessionMigrationTest
  tests/test-sessions/test-jdbc-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSessionMigrationTest.java
Labels: Test

#4023 session#getLastAccessedTime should throw IllegalStateException if session has been invalidated
  jetty-server/src/main/java/org/eclipse/jetty/server/session/Session.java
  jetty-server/src/test/java/org/eclipse/jetty/server/session/SessionHandlerTest.java
Labels: Bug, TCK

#3965 Issue #3964 - Listener behavior cleanup (Jetty 9.4.x)
  jetty-security/src/test/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticatorTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelListeners.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelEventTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpInputAsyncStateTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpInputTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpWriterTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/MockConnector.java
  jetty-util/src/main/java/org/eclipse/jetty/util/component/Container.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredInvalidationSessionTest.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractClusteredSessionScavengingTest.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/AbstractWebAppObjectInSessionTest.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestContextScopeListener.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestHttpChannelCompleteListener.java
  tests/test-sessions/test-sessions-common/src/main/java/org/eclipse/jetty/server/session/TestServer.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AsyncTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/CreationTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DefaultSessionCacheTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DeleteUnloadableSessionTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DirtyAttributeTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/IdleSessionTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/NonClusteredSessionScavengingTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/ReentrantRequestSessionTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SameContextForwardedSessionTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SaveOptimizeTest.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/SessionRenewTest.java
Labels: Enhancement

#4034 Issue #4033 - Add Lenient percent decode in URIUtil
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
Labels: Bug
