Repository jetty/jetty.project, pull requests merged in 2020-05, with the labels that each got.

#4829 Jetty 10.0.x 4825 pushbuilder
  jetty-server/src/main/java/org/eclipse/jetty/server/PushBuilderImpl.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
Labels: Specification, TCK

#4779 Issue #4770 - Deprecate GzipTester
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AbstractFileContentServlet.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AbstractGzipTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AsyncScheduledDispatchWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AsyncTimeoutCompleteWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AsyncTimeoutDispatchWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletLengthStreamTypeWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletLengthTypeStreamWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletStreamLengthTypeWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletStreamLengthTypeWriteWithFlush.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletStreamTypeLengthWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletTypeLengthStreamWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/BlockingServletTypeStreamLengthWrite.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipContentLengthTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultNoRecompressTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultServletDeferredContentTypeTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultServletTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipHandlerNoReCompressTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipHandlerTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipTester.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/Hex.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/HttpOutputWriteFileContentServlet.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/IncludedGzipMinSizeTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/IncludedGzipTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/TestDirContentServlet.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/TestMinGzipSizeServlet.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/TestStaticMimeTypeServlet.java
  jetty-servlets/src/test/resources/test.svg.sha1
Labels: Test

#4838 Issue #4835 - Addressing flush/commit with GzipHttpOutputInterceptor
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerCommitTest.java
Labels: Bug

#4844 proxy v2 skip address length bytes when LOCAL command is specified
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ProxyConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ProxyProtocolTest.java
Labels: Bug, Sponsored

#4849 Implement ProxyCustomizer to make real address:port pairs accessible for proxied requests
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyCustomizer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ProxyCustomizerTest.java
Labels: Enhancement, Sponsored

#4840 Start a mongo instance for testing using docker via java code
  Jenkinsfile
  jetty-util/src/main/config/modules/slf4j-api.mod
  pom.xml
  tests/test-sessions/test-mongodb-sessions/pom.xml
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/nosql/mongodb/MongoSessionDataStoreTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/nosql/mongodb/MongoTestHelper.java
  tests/test-sessions/test-mongodb-sessions/src/test/resources/simplelogger.properties
Labels: Build, Test

#4856 introduce socket configuration properties in Jetty XML files
  jetty-server/src/main/config/etc/jetty-http.xml
  jetty-server/src/main/config/etc/jetty-ssl.xml
  jetty-server/src/main/config/modules/http.mod
  jetty-server/src/main/config/modules/ssl.mod
  jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java
Labels: Enhancement, Sponsored

#4864 Issue #4828 Buffer Corruption
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
Labels: Bug

#4863 Issue #4860 - NPE from HttpFields
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
Labels: Bug
