Repository jetty/jetty.project, pull requests merged in 2020-02, with the labels that each got.

#4519 Composable connection factories
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/DetectorConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/OptionalSslConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/SslConnectionFactory.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DetectorConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/OptionalSslConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ProxyConnectionTest.java
Labels: Sponsored

#4544 Issue #4541 Large response header
  jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpSenderOverHTTP.java
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorClientTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerHTTPTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpTester.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
Labels: Sponsored

#4570 Issue #4567 - StdErrLog cleanup and final Arg Throwable support
  jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java
  jetty-util/src/main/java/org/eclipse/jetty/util/log/JettyLogHandler.java
  jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java
  jetty-util/src/main/java/org/eclipse/jetty/util/log/Logger.java
  jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java
  jetty-util/src/test/java/org/eclipse/jetty/util/log/StdErrLogTest.java
Labels: Enhancement

#4596 Issue #4567 - Backport of StdErrLog 10.0.x for Throwable behavior change
  jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java
  jetty-util/src/test/java/org/eclipse/jetty/util/log/StdErrLogTest.java
Labels: Bug

#4607 Issue #4606 - fixing formatTick use of `now`
  jetty-util/src/main/java/org/eclipse/jetty/util/DateCache.java
Labels: Bug

#4610 Docs for OpenID
  jetty-documentation/src/main/asciidoc/distribution-guide/security/chapter.adoc
  jetty-documentation/src/main/asciidoc/distribution-guide/security/openid-support.adoc
Labels: Documentation
