Repository jetty/jetty.project, pull requests merged in 2020-04, with the labels that each got.

#4742 Issue #4699 fix jar files from multimodules not scanned
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyLibrary/pom.xml
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyLibrary/src/main/java/jettyissue/MyAnnotation.java
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyLibrary/src/main/java/jettyissue/MyServletContainerInitializer.java
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyLibrary/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyWebApp/pom.xml
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyWebApp/src/config/context.xml
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyWebApp/src/config/jetty.xml
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyWebApp/src/main/java/jettyissue/NormalClass.java
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/MyWebApp/src/main/webapp/index.html
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/invoker.properties
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/pom.xml
  jetty-maven-plugin/src/it/jetty-run-mojo-jar-scan-it/postbuild.groovy
  jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyRunMojo.java
Labels: Bug

#4734 Issue #4529 - Fixing HTML error page from showing servlet info if configured not to do so
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
Labels: Bug

#4740 Issue #4638 - updating documentation about form limits
  jetty-documentation/src/main/asciidoc/configuring/security/configuring-form-size.adoc
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
Labels: Documentation

#4753 Issue #4752 Call HttpSessionListener.sessionCreated in order listeners were added.
  jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/session/SessionHandlerTest.java
Labels: TCK

#4748 Issue #4745 - update documentation for centralized-webapp-logging
  jetty-documentation/src/main/asciidoc/administration/logging/example-logback-centralized-logging.adoc
Labels: Documentation

#4761 Issue #4760 Response.setLocale should override previous
  jetty-http/src/main/resources/org/eclipse/jetty/http/encoding.properties
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
Labels: TCK

#4763 Issue #4762 Request.authenticate must return true if already authenticated
  jetty-security/src/test/java/org/eclipse/jetty/security/ConstraintTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
Labels: TCK

#4796 Jetty 10.0.x 4794 http input set read listener
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpInputTest.java
Labels: Specification, TCK

#4804 Issue #4794 Test for asyncIsStarted for setReadListener
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpInputTest.java
Labels: Specification, TCK

#4811 Issue #4819 - Workarounds for old (pre API 24) Android SDKs
  jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
Labels: JVM Issue, Sponsored, Third Party
