Repository jetty/jetty.project, pull requests merged in 2020-10, with the labels that each got.

#5408 Bump jnr-unixsocket from 0.24 to 0.38.3
  jetty-unixsocket/pom.xml
  jetty-unixsocket/src/main/assembly/config.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket-forwarded.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket-http.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket-http2c.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket-proxy-protocol.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket-secure.xml
  jetty-unixsocket/src/main/config-template/etc/jetty-unixsocket.xml
  jetty-unixsocket/src/main/config-template/modules/unixsocket-forwarded.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-http.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-http2c.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-prefix.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-proxy-protocol.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-secure.mod
  jetty-unixsocket/src/main/config-template/modules/unixsocket-suffix.mod
  jetty-unixsocket/src/main/config/modules/unixsocket.mod
  pom.xml
Labels: dependencies

#5411 Bumping google-cloud from 1.0.0 to 1.105.0
  jetty-gcloud/jetty-gcloud-session-manager/pom.xml
  jetty-gcloud/pom.xml
  jetty-maven-plugin/pom.xml
  tests/test-sessions/test-gcloud-sessions/pom.xml
Labels: dependencies

#5439 Bump jboss-logging from 3.3.2.Final to 3.4.1.Final
  pom.xml
Labels: dependencies

#5441 Bump build-helper-maven-plugin from 3.0.0 to 3.2.0
  pom.xml
Labels: dependencies

#5440 Bump checkstyle from 8.29 to 8.36.2
  pom.xml
Labels: dependencies

#5419 Issue #5417 - Honoring implied ports on ForwardedRequestCustomizer better
  jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
Labels: Bug

#5445 ForwardedRequestCustomizer behavior should not be applied to requests without forwarding headers
  jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
Labels: Bug

#5450 Cleanup Request.isSecure() logic
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
Labels: Enhancement

#5453 Issue #5451 - Cleanup of temp file usages.
  examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyHandlers.java
  jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
  jetty-io/src/test/java/org/eclipse/jetty/io/IOTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/ContextHandlerTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletTester.java
  jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PutFilter.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/MultipartFilterTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/PutFilterTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MultiPartInputStreamParser.java
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/FileSessionDataStoreTest.java
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/FileTestHelper.java
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/TestFileSessions.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSerializedSessionScavengingTest.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/ClusteredSessionScavengingTest.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanFileSessionDataStoreTest.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/SerializedInfinispanSessionDataStoreTest.java
Labels: Enhancement

#5458 Issue #5451 - Removing file/dir permission management from codebase
  jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormInputStream.java
  jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MultiPartInputStreamParser.java
Labels: Enhancement

#5477 Bump spifly from 1.2.4 to 1.3.2
  jetty-annotations/src/main/java/org/eclipse/jetty/annotations/AnnotationParser.java
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
Labels: dependencies, java

#5459 Fix archive assemblies (tar.gz and zip) to have fixed file/dir modes.
  jetty-home/src/main/assembly/jetty-assembly.xml
Labels: Enhancement

#5481 NPE protection on WebInfConfiguration.deconfigure()
  jetty-io/src/test/java/org/eclipse/jetty/io/IOTest.java
  jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/AbstractJettyMojo.java
  jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java
Labels: Bug

#5515 Closes #5511 - Deleting old SslEngineBehaviorTest
  jetty-io/src/test/java/org/eclipse/jetty/io/SslEngineBehaviorTest.java
Labels: Test

#5513 Bump org.eclipse.osgi (platform) from 3.13.100 to 3.16.0
  jetty-osgi/test-jetty-osgi/pom.xml
Labels: Test, dependencies, java

#5512 Bump org.eclipse.osgi.services from 3.7.100 to 3.9.0
  jetty-osgi/test-jetty-osgi/pom.xml
Labels: Test, dependencies, java

#5529 Bump maven.resolver.version from 1.3.1 to 1.6.1
  pom.xml
  tests/test-distribution/pom.xml
Labels: dependencies, java

#5538 Issue #5535 - Adding support for regex include/exclude of Protocols to SslContextFactory
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
  jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java
Labels: Enhancement
