Repository jetty/jetty.project, pull requests merged in 2020-12, with the labels that each got.

#5730 Correct META-INF/LICENSE handling
  jetty-runner/pom.xml
  jetty-runner/src/main/resources/MANIFEST.MF
  jetty-runner/src/main/resources/META-INF/MANIFEST.MF
Labels: Build

#5676 Issue #5675 Update some osgi test dependencies
  jetty-osgi/jetty-osgi-boot-jsp/pom.xml
  jetty-osgi/jetty-osgi-boot-warurl/pom.xml
  jetty-osgi/jetty-osgi-boot/pom.xml
  jetty-osgi/jetty-osgi-httpservice/pom.xml
  jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi-context/pom.xml
  jetty-osgi/test-jetty-osgi-server/pom.xml
  jetty-osgi/test-jetty-osgi-webapp/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithAnnotations.java
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
Labels: Test

#5740 Fix #5739 Remove distribution from doco
  README.md
  demos/embedded/src/test/java/org/eclipse/jetty/demos/OneWebAppTest.java
  demos/embedded/src/test/java/org/eclipse/jetty/demos/OneWebAppWithJspTest.java
  demos/embedded/src/test/java/org/eclipse/jetty/demos/ServerWithAnnotationsTest.java
  demos/embedded/src/test/java/org/eclipse/jetty/demos/ServerWithJNDITest.java
  jetty-ant/src/test/config/build.xml
  jetty-documentation/src/main/asciidoc/old_docs/connectors/configuring-connectors.adoc
  jetty-documentation/src/main/asciidoc/old_docs/contributing/release-testing.adoc
  jetty-documentation/src/main/asciidoc/old_docs/debugging/debugging-with-eclipse.adoc
  jetty-documentation/src/main/asciidoc/old_docs/debugging/debugging-with-intellij.adoc
  jetty-documentation/src/main/asciidoc/old_docs/debugging/enable-remote-debugging.adoc
  jetty-documentation/src/main/asciidoc/old_docs/frameworks/metro.adoc
  jetty-documentation/src/main/asciidoc/old_docs/frameworks/osgi.adoc
  jetty-documentation/src/main/asciidoc/old_docs/gettingstarted/getting-started/jetty-installing.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/configuring-logging-modules.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/dump-tool.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-apache-log4j.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-java-util-logging-native.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-java-util-logging.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-logback-centralized-logging.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-logback.adoc
  jetty-documentation/src/main/asciidoc/old_docs/logging/example-slf4j-multiple-loggers.adoc
  jetty-documentation/src/main/asciidoc/old_docs/platforms/cloudfoundry.adoc
  jetty-documentation/src/main/asciidoc/old_docs/security/jetty-home-and-jetty-base.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/screen-empty-base-listconfig.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/screen-http-webapp-deploy-listconfig.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/startup-base-vs-home.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/startup-overview.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/startup-unix-service.adoc
  jetty-documentation/src/main/asciidoc/old_docs/startup/startup-windows-service.adoc
  jetty-documentation/src/main/asciidoc/operations-guide/begin/install.adoc
  jetty-documentation/src/main/asciidoc/operations-guide/start/start-jar.adoc
  jetty-gcloud/jetty-gcloud-session-manager/src/test/java/org/eclipse/jetty/gcloud/session/GCloudSessionTester.java
  jetty-home/src/main/assembly/site-component.xml
  jetty-osgi/test-jetty-osgi-webapp-resources/pom.xml
  jetty-start/src/test/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializerTest.java
  jetty-start/src/test/java/org/eclipse/jetty/start/util/CorrectMavenCentralRefs.java
  jetty-start/src/test/java/org/eclipse/jetty/start/util/RebuildTestResources.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/support/JettyDistro.java
Labels: Documentation

#5747 get rid of this logback dependency
  tests/test-integration/pom.xml
Labels: Test

#5771 remove configuration for plugin clirr as it is not used
  jetty-runner/pom.xml
  pom.xml
  tests/pom.xml
Labels: Build

#5770 Upgrade h2spec maven plugin to 1.0.3
  pom.xml
Labels: Build, Test

#5735 Jetty 9.4.x optimize parser warning from logs and add spotbug
  Jenkinsfile
  examples/pom.xml
  jetty-alpn/jetty-alpn-client/pom.xml
  jetty-alpn/jetty-alpn-server/pom.xml
  jetty-annotations/pom.xml
  jetty-client/pom.xml
  jetty-continuation/pom.xml
  jetty-deploy/pom.xml
  jetty-distribution/pom.xml
  jetty-home/pom.xml
  jetty-http-spi/pom.xml
  jetty-http/pom.xml
  jetty-io/pom.xml
  jetty-jaas/pom.xml
  jetty-jaspi/pom.xml
  jetty-jmh/pom.xml
  jetty-jmx/pom.xml
  jetty-jndi/pom.xml
  jetty-openid/pom.xml
  jetty-osgi/jetty-osgi-boot-jsp/pom.xml
  jetty-osgi/jetty-osgi-boot-warurl/pom.xml
  jetty-osgi/jetty-osgi-boot/pom.xml
  jetty-osgi/jetty-osgi-httpservice/pom.xml
  jetty-plus/pom.xml
  jetty-proxy/pom.xml
  jetty-rewrite/pom.xml
  jetty-runner/pom.xml
  jetty-security/pom.xml
  jetty-server/pom.xml
  jetty-servlet/pom.xml
  jetty-servlets/pom.xml
  jetty-start/pom.xml
  jetty-unixsocket/pom.xml
  jetty-util-ajax/pom.xml
  jetty-util/pom.xml
  jetty-webapp/pom.xml
  jetty-websocket/pom.xml
  jetty-xml/pom.xml
  pom.xml
  tests/pom.xml
Labels: Build

#5780 Fixes #5779 Include should not set pathInContext
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DispatcherTest.java
Labels: TCK

#5813 execute isAlias test only on linux
  jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java
Labels: Mac OSX, Test

#5814 Upgrade testcontainers to 1.15.1
  pom.xml
Labels: Build

#5821 Issue #5816 : JMX-ify Scheduler implementations
  jetty-util/src/main/java/org/eclipse/jetty/util/thread/ScheduledExecutorScheduler.java
Labels: Enhancement

#5776 Remove javax.* dependencies
  demos/demo-jetty-webapp/pom.xml
  demos/demo-proxy-webapp/pom.xml
  jetty-websocket/websocket-core-client/pom.xml
  jetty-websocket/websocket-core-common/pom.xml
  jetty-websocket/websocket-core-server/pom.xml
  jetty-websocket/websocket-javax-client/pom.xml
  jetty-websocket/websocket-javax-common/pom.xml
  jetty-websocket/websocket-jetty-api/pom.xml
  jetty-websocket/websocket-jetty-client/pom.xml
  jetty-websocket/websocket-jetty-common/pom.xml
  jetty-websocket/websocket-servlet/pom.xml
  pom.xml
  tests/test-webapps/test-felix-webapp/pom.xml
Labels: Build, dependencies
