Repository jetty/jetty.project, pull requests merged in 2020-11, with the labels that each got.

#5556 Fixes #5555 NPE if Filter of named servlet
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletHandlerTest.java
Labels: Bug, High Priority

#5567 Bump maven-antrun-plugin from 1.8 to 3.0.0
  jetty-distribution/pom.xml
  jetty-gcloud/jetty-gcloud-session-manager/pom.xml
  jetty-home/pom.xml
  jetty-infinispan/infinispan-embedded-query/pom.xml
  jetty-infinispan/infinispan-embedded/pom.xml
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-infinispan/infinispan-remote/pom.xml
  jetty-osgi/jetty-osgi-boot/pom.xml
  jetty-osgi/jetty-osgi-httpservice/pom.xml
  jetty-unixsocket/pom.xml
  pom.xml
  tests/test-webapps/test-jndi-webapp/pom.xml
  tests/test-webapps/test-servlet-spec/test-spec-webapp/pom.xml
Labels: Build, dependencies, java

#5570 Bump protostream from 4.2.2.Final to 4.3.4.Final
  jetty-infinispan/infinispan-common/pom.xml
  jetty-infinispan/infinispan-remote/pom.xml
  pom.xml
  tests/test-sessions/test-infinispan-sessions/pom.xml
Labels: Build, dependencies, java

#5598 Bump maven-site-plugin from 3.7.1 to 3.9.1
  pom.xml
Labels: Build, dependencies

#5600 Bump jna from 5.5.0 to 5.6.0
  pom.xml
Labels: Test, dependencies

#5602 Bump hazelcast from 3.12.6 to 3.12.10
  jetty-hazelcast/pom.xml
Labels: dependencies, java

#5604 Bump xmemcached from 2.4.5 to 2.4.6
  jetty-memcached/jetty-memcached-sessions/pom.xml
Labels: dependencies, java

#5601 Bump tycho from 1.4.0 to 2.1.0
  pom.xml
Labels: Build, dependencies

#5638 Run websocket autobahn-testsuite with docker in junit test
  Jenkinsfile-autobahn
  jetty-websocket/websocket-core-tests/fuzzingclient.json
  jetty-websocket/websocket-core-tests/pom.xml
  jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/autobahn/AutobahnTests.java
  jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/autobahn/CoreAutobahnClient.java
  jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/autobahn/CoreAutobahnServer.java
Labels: Build, Test

#5572 Correcting compact3 jar contents to only include org.eclipse.jetty
  aggregates/jetty-all-compact3/pom.xml
Labels: Bug, Build, Sponsored

#5651 Enable gcloud testing in docker
  Jenkinsfile
  tests/test-sessions/test-gcloud-sessions/pom.xml
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/gcloud/session/GCloudSessionTestSupport.java
  tests/test-sessions/test-gcloud-sessions/src/test/resources/simplelogger.properties
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java
  tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/remote/RemoteInfinispanTestSupport.java
Labels: Build, Test

#5560 Issue #5539 - Proper StatisticsServlet output format via content negotiation
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
  jetty-server/src/main/config/modules/stats.mod
  jetty-servlet/pom.xml
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/StatisticsServlet.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/StatisticsServletTest.java
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/WebInfConfigurationTest.java
  tests/test-distribution/pom.xml
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/StatsTests.java
  tests/test-distribution/src/test/resources/stats-webapp/WEB-INF/web.xml
  tests/test-distribution/src/test/resources/stats-webapp/index.html
Labels: Bug, Enhancement, Sponsored

#5703 Issue #5644 Remove all profiles for session tests
  Jenkinsfile
  jetty-infinispan/infinispan-remote-query/pom.xml
  tests/test-sessions/test-gcloud-sessions/pom.xml
  tests/test-sessions/test-infinispan-sessions/pom.xml
  tests/test-sessions/test-memcached-sessions/pom.xml
  tests/test-sessions/test-mongodb-sessions/pom.xml
Labels: Build, Test

#5688 Jetty 10.0.x restore javadoc:jar as part of ci build
  Jenkinsfile
Labels: Build

#5526 Access to cookie config with accessor method
  jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java
Labels: Enhancement
