Repository jetty/jetty.project, pull requests merged in 2020-03, with the labels that each got.

#4630 Issue #4620 - Better support for alt PrintStream in StdErrLog
  jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java
Labels: Bug

#4629 Issue #4628 - Non-Required Module Dependency Support
  jetty-start/src/main/java/org/eclipse/jetty/start/Module.java
  jetty-start/src/main/java/org/eclipse/jetty/start/ModuleGraphWriter.java
  jetty-start/src/main/java/org/eclipse/jetty/start/Modules.java
  jetty-start/src/test/java/org/eclipse/jetty/start/ModulesTest.java
  jetty-start/src/test/resources/non-required-deps/modules/bar-dive.mod
  jetty-start/src/test/resources/non-required-deps/modules/bar.mod
  jetty-start/src/test/resources/non-required-deps/modules/foo.mod
  jetty-start/src/test/resources/non-required-deps/modules/impls/bar-dynamic.mod
Labels: Enhancement

#4632 Issue #4631 - Warning about skipping of <Arg> nodes is in wrong place for <Configure>
  jetty-server/src/main/config/etc/jetty.xml
  jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
Labels: Bug

#4689 Issue #4620 - support alt PrintStream in StdErrAppender properly
  jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
Labels: Bug

#4698 Issue #4697 ServletContext sessionModes methods should throw UnsupportedOperationException
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
Labels: Specification, TCK

#4701 Issue #4700 ServletContext.createXXX methods should throw UnsupportedOperationException
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextState.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
Labels: Specification, TCK

#4712 Reset trailers on recycled response
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpTrailersTest.java
Labels: Bug, Specification, TCK

#4708 Issue #4707 wrong value for ServletContext.setSessionTimeout
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
  jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/StandardDescriptorProcessorTest.java
  jetty-webapp/src/test/resources/web-session-config.xml
  tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/TestListener.java
  tests/test-webapps/test-jetty-webapp/src/main/webapp/WEB-INF/web.xml
Labels: Bug, Specification, TCK

#4721 Issue #4713 Async dispatch with query.
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
Labels: Specification, TCK

#4705 Fixes #4542 Root pathspec mapping pathInfo
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpecGroup.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/ServletPathSpecTest.java
Labels: Specification

#4633 Issue #4628 - Ensuring checkEnabledModules is conditional dependency aware
  jetty-start/src/main/java/org/eclipse/jetty/start/Module.java
  jetty-start/src/main/java/org/eclipse/jetty/start/Modules.java
  jetty-start/src/test/java/org/eclipse/jetty/start/ModulesTest.java
Labels: Enhancement

#4720 Issue #4719 Keep previous charencoding if not set in content type
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ErrorPageTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ResponseHeadersTest.java
Labels: Specification, TCK
