Repository jetty/jetty.project, pull requests merged in 2021-12, with the labels that each got.

#7189 interpolate bouncycastle.version in mod file
  jetty-keystore/pom.xml
  jetty-keystore/src/main/config/modules/test-keystore.mod
Labels: Build

#7208 buildnumber mavem plugin 3.0.0
  pom.xml
Labels: Build

#7221 Issue #7219 - Migrate to Github Workflow Stale
  .github/stale.yml
  .github/workflows/stale-action.yml
Labels: Build

#7075 Issue #7073 - Adding test of startAsync with bad query encoding.
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncDispatchEncodingTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/AsyncServletTest.java
Labels: Test

#7223 Move jetty-nosql to jetty-mongodb
  documentation/jetty-documentation/pom.xml
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/sessions/session-sessiondatastore-mongo.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java
  javadoc/pom.xml
  jetty-bom/pom.xml
  jetty-home/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-session/jetty-mongodb/pom.xml
  jetty-session/jetty-mongodb/src/main/config/etc/sessions/mongo/session-store-by-address.xml
  jetty-session/jetty-mongodb/src/main/config/etc/sessions/mongo/session-store-by-uri.xml
  jetty-session/jetty-mongodb/src/main/config/modules/session-store-mongo.mod
  jetty-session/jetty-mongodb/src/main/config/modules/sessions/mongo/address.mod
  jetty-session/jetty-mongodb/src/main/config/modules/sessions/mongo/uri.mod
  jetty-session/jetty-mongodb/src/main/java/module-info.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/mongodb/MongoSessionDataStore.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/mongodb/MongoSessionDataStoreFactory.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/mongodb/MongoUtils.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/mongodb/package-info.java
  jetty-session/jetty-nosql/src/main/java/org/eclipse/jetty/nosql/NoSqlSessionDataStore.java
  jetty-session/jetty-nosql/src/main/java/org/eclipse/jetty/nosql/mongodb/package-info.java
  jetty-session/pom.xml
  pom.xml
  tests/test-sessions/test-mongodb-sessions/pom.xml
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/AttributeNameTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/ClusteredInvalidateSessionTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/ClusteredSessionScavengingTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/MongoSessionDataStoreTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/mongodb/MongoTestHelper.java
Labels: jetty 12

#7249 (9.4.x) ByteBufferPool now reset the buffer's endianness on release
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
Labels: Enhancement

#7248 (10.0.x) ByteBufferPool and RetainableByteBufferPool now reset the buffer's endianness on release
  jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-io/src/test/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPoolTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
Labels: Enhancement

#7228 Regularize name of gcloud session module and package.
  javadoc/pom.xml
  jetty-bom/pom.xml
  jetty-home/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-session/jetty-gcloud/pom.xml
  jetty-session/jetty-gcloud/src/main/assembly/config.xml
  jetty-session/jetty-gcloud/src/main/config-template/etc/sessions/gcloud/session-store.xml
  jetty-session/jetty-gcloud/src/main/config-template/modules/gcloud-datastore.mod
  jetty-session/jetty-gcloud/src/main/config-template/modules/gcloud.mod
  jetty-session/jetty-gcloud/src/main/config-template/modules/gcloud/index.yaml
  jetty-session/jetty-gcloud/src/main/config-template/modules/session-store-gcloud.mod
  jetty-session/jetty-gcloud/src/main/java/org/eclipse/jetty/session/gcloud/GCloudSessionDataStore.java
  jetty-session/jetty-gcloud/src/main/java/org/eclipse/jetty/session/gcloud/GCloudSessionDataStoreFactory.java
  jetty-session/pom.xml
  pom.xml
  tests/test-sessions/test-gcloud-sessions/pom.xml
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/session/gcloud/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/session/gcloud/ClusteredSessionScavengingTest.java
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/session/gcloud/GCloudSessionDataStoreTest.java
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/session/gcloud/GCloudSessionTestSupport.java
  tests/test-sessions/test-gcloud-sessions/src/test/java/org/eclipse/jetty/session/gcloud/InvalidationSessionTest.java
Labels: jetty 12

#7229 Regularize package of jetty-hazelcast.
  jetty-session/jetty-hazelcast/src/main/config/etc/sessions/hazelcast/default.xml
  jetty-session/jetty-hazelcast/src/main/config/etc/sessions/hazelcast/remote.xml
  jetty-session/jetty-hazelcast/src/main/java/module-info.java
  jetty-session/jetty-hazelcast/src/main/java/org/eclipse/jetty/session/hazelcast/HazelcastSessionDataStore.java
  jetty-session/jetty-hazelcast/src/main/java/org/eclipse/jetty/session/hazelcast/HazelcastSessionDataStoreFactory.java
  jetty-session/jetty-hazelcast/src/main/java/org/eclipse/jetty/session/hazelcast/SessionDataSerializer.java
  jetty-session/jetty-hazelcast/src/test/java/org/eclipse/jetty/session/hazelcast/TestHazelcastSessions.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/ClusteredSessionScavengingTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/HazelcastClusteredInvalidationSessionTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/HazelcastSessionDataStoreTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/HazelcastTestHelper.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/client/ClientOrphanedSessionTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/client/ClientSessionScavengingTest.java
  tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/session/hazelcast/client/HazelcastSessionDataStoreTest.java
Labels: jetty 12

#7231 Regularize jetty 12.0.x mongo session package
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/sessions/session-sessiondatastore-mongo.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java
  jetty-session/jetty-mongodb/src/main/config/etc/sessions/mongo/session-store-by-address.xml
  jetty-session/jetty-mongodb/src/main/config/etc/sessions/mongo/session-store-by-uri.xml
  jetty-session/jetty-mongodb/src/main/java/module-info.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/session/mongodb/MongoSessionDataStore.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/session/mongodb/MongoSessionDataStoreFactory.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/session/mongodb/MongoUtils.java
  jetty-session/jetty-mongodb/src/main/java/org/eclipse/jetty/session/mongodb/package-info.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/AttributeNameTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/ClusteredInvalidateSessionTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/ClusteredOrphanedSessionTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/ClusteredSessionScavengingTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/MongoSessionDataStoreTest.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/session/mongodb/MongoTestHelper.java
  tests/test-sessions/test-mongodb-sessions/src/test/resources/simplelogger.properties
Labels: jetty 12

#7230 Regularize package of jetty-memcached to be consistent.
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/sessions/session-cachingsessiondatastore.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java
  jetty-session/jetty-memcached/pom.xml
  jetty-session/jetty-memcached/src/main/config/etc/sessions/session-data-cache/xmemcached.xml
  jetty-session/jetty-memcached/src/main/config/modules/sessions/session-data-cache/xmemcached.mod
  jetty-session/jetty-memcached/src/main/java/module-info.java
  jetty-session/jetty-memcached/src/main/java/org/eclipse/jetty/session/memcached/MemcachedSessionDataMap.java
  jetty-session/jetty-memcached/src/main/java/org/eclipse/jetty/session/memcached/MemcachedSessionDataMapFactory.java
  jetty-session/jetty-memcached/src/test/java/org/eclipse/jetty/session/memcached/TestMemcachedSessions.java
  tests/test-sessions/test-memcached-sessions/src/test/java/org/eclipse/jetty/session/memcached/CachingSessionDataStoreTest.java
  tests/test-sessions/test-memcached-sessions/src/test/java/org/eclipse/jetty/session/memcached/MemcachedTestHelper.java
Labels: jetty 12

#7253 Upgrade jackson-databind to 2.13.0
  jetty-maven-plugin/src/it/it-parent-pom/pom.xml
Labels: dependencies

#7254 Upgrade jackson-databind to 2.13.0
  pom.xml
Labels: dependencies

#7258 Upgrade log4j2 from 2.14.0 to 2.15.0
  pom.xml
Labels: dependencies

#7263 Issue #7262 - make the ServletHandler.getFilterChain method protected
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
Labels: Sponsored

#7282 Destroy interceptor when content producer gets recycled
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/AsyncContentProducerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java
Labels: Bug

#7227 Issue #7063 - Remove logging requirement from Password / Credential
  jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
  jetty-util/src/main/java/org/eclipse/jetty/util/security/Credential.java
  jetty-util/src/main/java/org/eclipse/jetty/util/security/Password.java
  jetty-util/src/test/java/org/eclipse/jetty/util/StringUtilTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/security/CredentialTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/security/PasswordTest.java
Labels: Bug

#7291 Cleanup HttpInput reopen/recycle
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java
  jetty-server/src/main/java/org/eclipse/jetty/server/BlockingContentProducer.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ContentProducer.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
Labels: Bug

#7328 Issue #7327 - Add missing entries to jetty-bom
  jetty-bom/pom.xml
Labels: Bug

#7314 Issue #7297 - Removing log4j 1.x
  jetty-util/src/main/config/modules/log4j-impl.mod
  pom.xml
Labels: Build, dependencies

#7183 Issue #6973 - Setup Request/Response objects for success with RequestLog
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java
  jetty-server/src/test/resources/jetty-logging.properties
Labels: Bug
