Repository jetty/jetty.project, pull requests merged in 2021-09, with the labels that each got.

#6686 Adding back dependabot configuration
  .github/dependabot.yml
Labels: Build, dependencies

#6689 Issue #6677 Update to Apache Jasper 9.0.52
  pom.xml
Labels: dependencies

#6690 Issue #6679 Update to Apache Jasper 10.0.10
  pom.xml
Labels: dependencies

#6736 follow up of hazelcast upgrade with .mod files as well
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-embedded.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-remote.mod
Labels: Build, dependencies

#6747 Issue #6735 Fix xml for infinispan-remote-query and infinispan-embedded-query
  jetty-infinispan/infinispan-embedded-query/src/main/config-template/etc/sessions/infinispan/infinispan-embedded-query.xml
  jetty-infinispan/infinispan-remote-query/src/main/config-template/etc/sessions/infinispan/infinispan-remote-query.xml
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/AbstractSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/InfinispanSessionDistributionTests.java
Labels: Bug

#6768 Change dependabot interval to daily
  .github/dependabot.yml
Labels: Build, dependencies

#6797 Rollup of version changes for 10.0.x
  .github/dependabot.yml
  documentation/jetty-documentation/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-runner/pom.xml
  pom.xml
  tests/test-webapps/test-owb-cdi-webapp/pom.xml
Labels: dependencies

#6798 Backport - Issue #6772 Update to asm 9.2, spifly 1.3.4
  jetty-osgi/test-jetty-osgi/pom.xml
  pom.xml
Labels: dependencies

#6796 Rollup of version changes for 9.4.x
  jetty-maven-plugin/pom.xml
  jetty-memcached/jetty-memcached-sessions/pom.xml
  jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-runner/pom.xml
  pom.xml
  tests/test-sessions/test-memcached-sessions/src/test/java/org/eclipse/jetty/memcached/sessions/MemcachedTestHelper.java
  tests/test-sessions/test-mongodb-sessions/src/test/java/org/eclipse/jetty/nosql/mongodb/MongoTestHelper.java
  tests/test-webapps/test-owb-cdi-webapp/pom.xml
Labels: dependencies

#6805 Temporarily disable 11.0.x dependabot config
  .github/dependabot.yml
Labels: dependencies

#6826 Jetty 10.0.x - more dependency backlog catch-up
  .github/dependabot.yml
  Jenkinsfile
  jetty-annotations/src/test/java/org/eclipse/jetty/annotations/TestSecurityAnnotationConversions.java
  jetty-bom/pom.xml
  jetty-jaas/pom.xml
  pom.xml
Labels: dependencies

#6827 Jetty 9.4.x - more dependency backlog catch-up
  jetty-annotations/src/test/java/org/eclipse/jetty/annotations/TestSecurityAnnotationConversions.java
  jetty-cdi/pom.xml
  jetty-gcloud/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  pom.xml
Labels: dependencies

#6833 jetty-10.0.x remove duplicate dependencies
  pom.xml
Labels: Build, dependencies

#6822 dependabot should ignore jakarta.transaction >= 2.0
  .github/dependabot.yml
Labels: Build, dependencies

#6758 Issue #6752 - Extensible DefaultSessionCache map implementation
  jetty-server/src/main/java/org/eclipse/jetty/server/session/DefaultSessionCache.java
Labels: Enhancement

#6854 Issue #6853 - remove pack200 plugins (Jetty 9.4.x)
  pom.xml
Labels: Build, dependencies

#6855 Issue #6853 - remove pack200 plugins (Jetty 10.0.x)
  pom.xml
Labels: Build, dependencies

#6734 Issue #6072 - backport of minimum fix for jetty-9.3.x
  jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SSLEngineTest.java
  jetty-websocket/websocket-client/src/test/java/org/eclipse/jetty/websocket/client/SessionTest.java
Labels: Bug, Sponsored, End-of-Life release

#6861 Fix #6860 IPv6 Format
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/HostPort.java
Labels: High Priority, Sponsored

#6839 Issue #3514 interpolation of mod files to avoid hardcoding version in mod files
  demos/demo-jndi-webapp/src/main/config/modules/demo-jndi.mod
  jetty-gcloud/jetty-gcloud-session-manager/pom.xml
  jetty-gcloud/jetty-gcloud-session-manager/src/main/assembly/config.xml
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-embedded.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-remote.mod
  jetty-home/pom.xml
  jetty-home/src/main/resources/modules/conscrypt.mod
  jetty-home/src/main/resources/modules/hawtio.mod
  jetty-home/src/main/resources/modules/jamon.mod
  jetty-home/src/main/resources/modules/jolokia.mod
  jetty-home/src/main/resources/modules/logging-jul.mod
  jetty-home/src/main/resources/modules/logging-log4j1.mod
  jetty-home/src/main/resources/modules/logging-log4j2.mod
  jetty-home/src/main/resources/modules/logging-logback.mod
  jetty-home/src/main/resources/modules/logging/slf4j.mod
  jetty-infinispan/infinispan-common/src/main/config/modules/sessions/infinispan/infinispan-common.mod
  jetty-infinispan/infinispan-embedded-query/pom.xml
  jetty-infinispan/infinispan-embedded-query/src/main/assembly/config.xml
  jetty-infinispan/infinispan-embedded/src/main/config-templates/modules/session-store-infinispan-embedded.mod
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-infinispan/infinispan-remote-query/src/main/assembly/config.xml
  jetty-infinispan/infinispan-remote/pom.xml
  jetty-infinispan/infinispan-remote/src/main/assembly/config.xml
  jetty-infinispan/infinispan-remote/src/main/config-template/modules/session-store-infinispan-remote.mod
  jetty-memcached/jetty-memcached-sessions/pom.xml
  jetty-memcached/jetty-memcached-sessions/src/main/config/modules/sessions/session-data-cache/xmemcached.mod
  jetty-nosql/pom.xml
  jetty-nosql/src/main/config/modules/session-store-mongo.mod
  jetty-unixsocket/jetty-unixsocket-server/pom.xml
  jetty-unixsocket/jetty-unixsocket-server/src/main/assembly/config.xml
  pom.xml
Labels: Build

#6893 Jetty 10.0.x Dependency Cleanup
  build-resources/pom.xml
  demos/demo-jetty-webapp/pom.xml
  demos/demo-jsp-webapp/pom.xml
  demos/demo-proxy-webapp/pom.xml
  documentation/jetty-documentation/pom.xml
  javadoc/pom.xml
  jetty-bom/pom.xml
  jetty-client/pom.xml
  jetty-home/pom.xml
  jetty-http-spi/pom.xml
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-jaspi/pom.xml
  jetty-jmx/pom.xml
  jetty-jspc-maven-plugin/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-maven-plugin/src/it/it-parent-pom/pom.xml
  jetty-maven-plugin/src/it/javax-annotation-api/pom.xml
  jetty-maven-plugin/src/it/jetty-start-war-mojo-it/pom.xml
  jetty-osgi/jetty-osgi-boot-jsp/pom.xml
  jetty-osgi/jetty-osgi-boot/pom.xml
  jetty-osgi/test-jetty-osgi-context/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithAnnotations.java
  jetty-runner/pom.xml
  jetty-runner/src/it/demo-simple-webapp-runner-with-path/pom.xml
  jetty-runner/src/it/demo-simple-webapp-runner/pom.xml
  jetty-websocket/websocket-core-tests/pom.xml
  pom.xml
  tests/test-distribution/pom.xml
  tests/test-webapps/test-cdi-common-webapp/pom.xml
  tests/test-webapps/test-felix-webapp/pom.xml
  tests/test-webapps/test-owb-cdi-webapp/pom.xml
Labels: Build, dependencies

#6916 Restore accidentally removed `<requireUpperBoundDeps/>`
  pom.xml
  tests/test-cdi/pom.xml
  tests/test-webapps/test-weld-cdi-webapp/pom.xml
Labels: Build, dependencies

#6918 fix directory name interpolation of mod file was not working
  jetty-infinispan/infinispan-embedded/pom.xml
  jetty-infinispan/infinispan-embedded/src/main/assembly/config.xml
  jetty-infinispan/infinispan-embedded/src/main/config-template/etc/sessions/infinispan/infinispan-embedded.xml
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/infinispan-embedded.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/session-store-infinispan-embedded.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan-embedded-libs.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan-embedded-serverclasses.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan.xml
Labels: Build

#6897 Issue #3514 backport of mod files filtering
  jetty-gcloud/jetty-gcloud-session-manager/pom.xml
  jetty-gcloud/jetty-gcloud-session-manager/src/main/assembly/config.xml
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-embedded.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-remote.mod
  jetty-home/pom.xml
  jetty-home/src/main/resources/modules/conscrypt.mod
  jetty-home/src/main/resources/modules/hawtio.mod
  jetty-home/src/main/resources/modules/jamon.mod
  jetty-home/src/main/resources/modules/jolokia.mod
  jetty-infinispan/infinispan-common/src/main/config/modules/sessions/infinispan/infinispan-common.mod
  jetty-infinispan/infinispan-embedded-query/pom.xml
  jetty-infinispan/infinispan-embedded-query/src/main/assembly/config.xml
  jetty-infinispan/infinispan-embedded/pom.xml
  jetty-infinispan/infinispan-embedded/src/main/assembly/config.xml
  jetty-infinispan/infinispan-embedded/src/main/config-template/etc/sessions/infinispan/infinispan-embedded.xml
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/infinispan-embedded.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/session-store-infinispan-embedded.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan-embedded-libs.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan-embedded-serverclasses.mod
  jetty-infinispan/infinispan-embedded/src/main/config-template/modules/sessions/infinispan/embedded/infinispan.xml
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-infinispan/infinispan-remote-query/src/main/assembly/config.xml
  jetty-infinispan/infinispan-remote/pom.xml
  jetty-infinispan/infinispan-remote/src/main/assembly/config.xml
  jetty-infinispan/infinispan-remote/src/main/config-template/modules/session-store-infinispan-remote.mod
  jetty-memcached/jetty-memcached-sessions/pom.xml
  jetty-memcached/jetty-memcached-sessions/src/main/config/modules/sessions/session-data-cache/xmemcached.mod
  jetty-nosql/pom.xml
  jetty-nosql/src/main/config/modules/session-store-mongo.mod
  jetty-server/pom.xml
  jetty-unixsocket/pom.xml
  jetty-unixsocket/src/main/assembly/config.xml
  jetty-util/src/main/config/modules/log4j-impl.mod
  jetty-util/src/main/config/modules/logback-impl.mod
  jetty-util/src/main/config/modules/slf4j-api.mod
  pom.xml
Labels: Build
