Repository jetty/jetty.project, pull requests merged in 2021-03, with the labels that each got.

#6022 Issue #6021 - PoC for resolvePath within XmlConfiguration
  jetty-deploy/src/main/config/etc/jetty-deploy.xml
  jetty-deploy/src/main/config/modules/global-webapp-common.d/global-webapp-common.xml
  jetty-home/src/main/resources/modules/hawtio/hawtio.xml
  jetty-home/src/main/resources/modules/jamon/jamon.xml
  jetty-home/src/main/resources/modules/jolokia/jolokia.xml
  jetty-infinispan/infinispan-embedded-query/src/main/config-template/etc/sessions/infinispan/infinispan-embedded-query.xml
  jetty-infinispan/infinispan-embedded/src/main/config-templates/etc/sessions/infinispan/infinispan-embedded.xml
  jetty-infinispan/infinispan-remote-query/src/main/config-template/etc/sessions/infinispan/infinispan-remote-query.xml
  jetty-infinispan/infinispan-remote-query/src/main/config-template/modules/sessions/infinispan/remote/other_proto_marshallers.xml
  jetty-infinispan/infinispan-remote/src/main/config-template/etc/sessions/infinispan/infinispan-remote.xml
  jetty-jaas/src/main/config/etc/jetty-jaas.xml
  jetty-keystore/src/main/config/etc/jetty-test-keystore.xml
  jetty-keystore/src/main/config/modules/test-keystore.mod
  jetty-maven-plugin/src/main/resources/maven.xml
  jetty-osgi/test-jetty-osgi/src/test/config/etc/jetty-ssl.xml
  jetty-server/src/main/config/etc/jetty-requestlog.xml
  jetty-server/src/main/config/etc/jetty-ssl-context.xml
  jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
  jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
Labels: Enhancement

#6048 fix some mod files: some url using http to https, use maven central if possible, upgrade log4j2 to 2.14.0
  jetty-home/src/main/resources/modules/hawtio.mod
  jetty-home/src/main/resources/modules/jminix.mod
  jetty-util/src/main/config/modules/log4j2-api.mod
  pom.xml
Labels: Build, dependencies, java

#6053 Issue #6052 - make ModuleLocation optional on Android
  jetty-client/pom.xml
  jetty-util/src/main/java/org/eclipse/jetty/util/ModuleLocation.java
  jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
Labels: Build, Enhancement

#6056 Issue #6050 - fix bug for permessage deflate buffer aggregation
  jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/PermessageDeflateBufferTest.java
  jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/compress/CompressExtension.java
Labels: Bug

#6002 Issue #5996 - Remove logback-access.mod
  jetty-server/src/main/config/modules/logback-access.mod
  jetty-server/src/main/config/modules/logback-access/jetty-logback-access.xml
  jetty-server/src/main/config/modules/logback-access/logback-access.xml
Labels: Bug

#6055 add an easy way to configure useInputDirectByteBuffers/useOutputDirectByteBuffers for HttpConfiguration
  jetty-server/src/main/config/etc/jetty.xml
  jetty-server/src/main/config/modules/server.mod
Labels: Enhancement, TCK

#6064 Issue #6063 - expose hazelcast.version
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-embedded.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-remote.mod
Labels: Enhancement

#6111 #6110 fix JDURL and plugin declaration.
  jetty-documentation/pom.xml
  pom.xml
Labels: Documentation
