Repository jetty/jetty.project, pull requests merged in 2021-08, with the labels that each got.

#6572 Issue #5684 - windows test overhaul
  jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentTempDirTest.java
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/providers/ScanningAppProviderRuntimeUpdatesTest.java
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/ConcurrentStreamCreationTest.java
  jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java
  jetty-security/src/test/java/org/eclipse/jetty/security/PropertyUserStoreTest.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/FileBufferedResponseHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/GracefulStopTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/FileBufferedResponseHandlerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/ServerConnectorSslServerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SniSslConnectionFactoryTest.java
  jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AbstractDoSFilterTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/PathWatcherTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/ScannerTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/HugeResourceTest.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/KeyStoreScannerTest.java
Labels: Microsoft Windows, Test

#6529 Issue #6373 testing modules, starting with session storage
  jetty-gcloud/jetty-gcloud-session-manager/src/main/config-template/etc/sessions/gcloud/session-store.xml
  jetty-gcloud/jetty-gcloud-session-manager/src/main/config-template/modules/session-store-gcloud.mod
  jetty-gcloud/jetty-gcloud-session-manager/src/main/java/org/eclipse/jetty/gcloud/session/GCloudSessionDataStore.java
  jetty-gcloud/jetty-gcloud-session-manager/src/main/java/org/eclipse/jetty/gcloud/session/GCloudSessionDataStoreFactory.java
  jetty-home/src/main/resources/modules/hawtio.mod
  jetty-home/src/main/resources/modules/jminix.mod
  jetty-infinispan/infinispan-remote/src/main/config-template/etc/sessions/infinispan/infinispan-remote.xml
  jetty-infinispan/infinispan-remote/src/main/config-template/modules/session-store-infinispan-remote.mod
  pom.xml
  tests/test-distribution/pom.xml
  tests/test-distribution/src/main/java/org/eclipse/jetty/tests/distribution/JettyHomeTester.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/AbstractJettyHomeTest.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/ThirdPartyModulesTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/AbstractSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/FileSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/FileSessionWithMemcacheDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/GCloudSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/HazelcastSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/InfinispanSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/JDBCSessionDistributionTests.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/session/MongodbSessionDistributionTests.java
  tests/test-loginservice/pom.xml
  tests/test-sessions/test-jdbc-sessions/pom.xml
Labels: Test

#6589 disabled those tests as third parties app are not jakarta ready
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/ThirdPartyModulesTests.java
Labels: Test, Build

#6596 Upgrade ant to 1.10.11
  pom.xml
Labels: dependencies

#6606 Fix flaky HttpOutputTest.testEmptyBufferKnown
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java
Labels: Bug, Test

#6412 Issue #6406 - port jetty-jaspi to use Jakarta Authentication 2.x
  documentation/jetty-documentation/src/main/asciidoc/old_docs/security/authentication.adoc
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/index.adoc
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/jaspi/chapter.adoc
  javadoc/pom.xml
  jetty-home/pom.xml
  jetty-jaspi/pom.xml
  jetty-jaspi/src/main/config/etc/jaspi/jaspi-authmoduleconfig.xml
  jetty-jaspi/src/main/config/etc/jaspi/jaspi-default.xml
  jetty-jaspi/src/main/config/etc/jaspi/jaspi-demo.xml
  jetty-jaspi/src/main/config/modules/jaspi-default-auth-config-factory.mod
  jetty-jaspi/src/main/config/modules/jaspi-demo.mod
  jetty-jaspi/src/main/config/modules/jaspi.mod
  jetty-jaspi/src/main/java/module-info.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/JaspiAuthenticator.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/JaspiAuthenticatorFactory.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/JaspiMessageInfo.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/ServletCallbackHandler.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/SimpleAuthConfig.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/BaseAuthModule.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/BasicAuthenticationAuthModule.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/modules/UserInfo.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/provider/JaspiAuthConfigProvider.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/provider/SimpleAuthConfig.java
  jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/provider/SimpleServerAuthContext.java
  jetty-jaspi/src/main/resources/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory
  jetty-jaspi/src/test/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactoryTest.java
  jetty-jaspi/src/test/java/org/eclipse/jetty/security/jaspi/HttpHeaderAuthModule.java
  jetty-jaspi/src/test/java/org/eclipse/jetty/security/jaspi/JaspiTest.java
  jetty-jaspi/src/test/resources/jaspi.xml
  jetty-maven-plugin/pom.xml
  jetty-security/src/main/java/org/eclipse/jetty/security/EmptyLoginService.java
  jetty-security/src/main/java/org/eclipse/jetty/security/WrappedAuthConfiguration.java
  jetty-webapp/src/main/java/module-info.java
  jetty-webapp/src/main/java/org/eclipse/jetty/webapp/JaspiConfiguration.java
  jetty-webapp/src/main/resources/META-INF/services/org.eclipse.jetty.webapp.Configuration
  pom.xml
Labels: Bug

#6616 Upgrade h2spec-maven-plugin to 1.0.6
  pom.xml
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Build

#6622 Bump slf4j to 2.0.0-alpha4
  jetty-home/src/main/resources/modules/logging-jul.mod
  jetty-home/src/main/resources/modules/logging-logback.mod
  jetty-home/src/main/resources/modules/logging/slf4j.mod
  jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java
  pom.xml
Labels: dependencies

#6663 Issue #6661 - Make ServerConnector socket options setting optional
  jetty-io/src/main/java/org/eclipse/jetty/io/ClientConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java
Labels: Bug, Microsoft Windows

#6651 Issue #6605 cherry-pick changes flaky test HttpOutputTest#testEmptyBufferKnown 10.0.x branch
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java
Labels: Test, Build

#6675 Build on jdk17 now.
  Jenkinsfile
  pom.xml
Labels: Build

#6684 Bump slf4j to 2.0.0-alpha5
  jetty-home/src/main/resources/modules/logging-jul.mod
  jetty-home/src/main/resources/modules/logging/slf4j.mod
  pom.xml
Labels: dependencies
