Repository jetty/jetty.project, pull requests merged in 2021-06, with the labels that each got.

#6338 Add comment on why the test ServerWithJMXTest is disabled
  demos/embedded/src/test/java/org/eclipse/jetty/demos/ServerWithJMXTest.java
Labels: Build, Test

#6356 Fixes #6354 - allow jetty bundles to use 1.7 slf4j
  pom.xml
Labels: Enhancement

#6344 Issue #6327 Fix cookie leak test
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
Labels: Test

#6380 9.4.x: Improve ByteBufferPool implementations
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-jmh/src/main/java/org/eclipse/jetty/util/ArrayByteBufferPoolBenchmark.java
Labels: Enhancement, Performance

#6386 Issue #6327 Remove DisabledOnJre or test where appropriate
  jetty-client/src/test/java/org/eclipse/jetty/client/util/SPNEGOAuthenticationTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SSLReadEOFAfterResponseTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/MultiReleaseJarFileTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/TypeUtilTest.java
  jetty-util/src/test/java/org/eclipse/jetty/util/resource/JrtResourceTest.java
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/ClassMatcherTest.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Test

#6387 10.0.x: Improve ByteBufferPool implementations
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/ArrayByteBufferPoolBenchmark.java
Labels: Enhancement, Performance

#6381 Issue #6354 - OSGI manifest for slf4j-api packages lower limit should be 1.7
  demos/demo-jetty-webapp/pom.xml
  demos/demo-jetty-webapp/src/main/java/com/acme/ChatServlet.java
  demos/demo-jetty-webapp/src/main/java/com/acme/Dump.java
  demos/demo-jetty-webapp/src/main/java/com/acme/SecureModeServlet.java
  demos/demo-jetty-webapp/src/main/java/com/acme/TestFilter.java
  jetty-alpn/jetty-alpn-client/pom.xml
  jetty-alpn/jetty-alpn-conscrypt-client/pom.xml
  jetty-alpn/jetty-alpn-conscrypt-server/pom.xml
  jetty-annotations/pom.xml
  jetty-jndi/pom.xml
  jetty-osgi/jetty-osgi-boot/pom.xml
  jetty-osgi/test-jetty-osgi-context/pom.xml
  jetty-osgi/test-jetty-osgi-server/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
  jetty-osgi/test-jetty-osgi/src/test/resources/simplelogger.properties
  jetty-plus/pom.xml
  pom.xml
Labels: Bug, High Priority

#6414 Fixes #6410 - Use SocketAddress instead of InetSocketAddress.
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http2/HTTP2ServerDocs.java
  jetty-client/src/main/java/module-info.java
  jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectorHttpClientTransport.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpClientTransport.java
  jetty-client/src/main/java/org/eclipse/jetty/client/ProxyProtocolClientConnectionFactory.java
  jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpConnectionOverHTTP.java
  jetty-client/src/main/java/org/eclipse/jetty/client/proxy/ProxyProtocolClientConnectionFactory.java
  jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpConnectionOverFCGI.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Session.java
  jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpClientTransportOverHTTP2.java
  jetty-http2/http2-http-client-transport/src/test/java/org/eclipse/jetty/http2/client/http/MaxConcurrentStreamsTest.java
  jetty-io/src/main/java/org/eclipse/jetty/io/AbstractEndPoint.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ByteArrayEndPoint.java
  jetty-io/src/main/java/org/eclipse/jetty/io/EndPoint.java
  jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
  jetty-proxy/src/main/java/org/eclipse/jetty/proxy/ProxyConnection.java
  jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ProxyCustomizer.java
  jetty-server/src/main/java/org/eclipse/jetty/server/SslConnectionFactory.java
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-unixsocket/jetty-unixsocket-common/src/main/java/org/eclipse/jetty/unixsocket/common/UnixSocketEndPoint.java
  jetty-util/src/main/java/org/eclipse/jetty/util/SocketAddressResolver.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java
  jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/internal/MockEndpoint.java
Labels: Bug

#6420 Bump (test scoped) net.minidev:json-smart version from 2.3 to 2.4.7
  jetty-client/pom.xml
Labels: Test, dependencies

#6384 Release process issue template
  .github/ISSUE_TEMPLATE/release-template.md
  .github/test-ticklist.md
Labels: Build

#6452 Issue #6451 - Request.getServletPath not following spec 3.5
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java
Labels: Bug, Specification

#6444 Issue #6434 add integration for testing generated webfrag.xml
  jetty-jspc-maven-plugin/src/it/simple-jsp-fail/postbuild.groovy
  jetty-jspc-maven-plugin/src/it/simple-jsp/postbuild.groovy
Labels: Build, Test

#6465 Issue #6464 - fix logging capture modules
  jetty-home/src/main/resources/modules/logging-jcl-capture.mod
  jetty-home/src/main/resources/modules/logging-log4j1-capture.mod
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/LoggingOptionsTests.java
Labels: Bug

#6463 disable MaxDuration mechanism in testConnectionMaxUsage
  jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java
Labels: Bug, Test

#6475 disable MaxDuration mechanism in testConnectionMaxUsage
  jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java
Labels: Bug, Test
