Repository jetty/jetty.project, pull requests merged in 2021-05, with the labels that each got.

#6229 Upgrade h2spec maven plugin 1.0.5
  pom.xml
Labels: Bug, Build, Test

#6230 Issue #6224 make jspc mojo maven threadsafe
  jetty-jspc-maven-plugin/src/main/java/org/eclipse/jetty/jspc/plugin/JspcMojo.java
Labels: Bug

#6247 upgrade h2spec-maven-plugin 1.0.5
  pom.xml
Labels: Build, Test, dependencies

#6255 Expose buildNumber properly in `--list-config`
  jetty-start/pom.xml
  jetty-start/src/main/java/org/eclipse/jetty/start/Props.java
  jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-start/src/main/resources/org/eclipse/jetty/start/build.properties
Labels: Enhancement

#6292 Issue #6291 Fix FileSessionDataStoreTest.testCleanOrphans
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/FileTestHelper.java
Labels: Test

#6294 Fix HttpChannelOverHTTP2 recycling order
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/RequestReaderTest.java
Labels: Bug

#6299 Issue #6291 Fix FileSessionDataStoreTest.testCleanOrphans (#6292)
  tests/test-sessions/test-file-sessions/src/test/java/org/eclipse/jetty/server/session/FileTestHelper.java
Labels: Test

#6300 add jetty-9.4.41.v20210516 infos in VERSION.TXT
  VERSION.txt
Labels: Documentation, Task

#6307 Issue #6138 Fix flakey DuplicateCookieTest
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java
Labels: Test

#6310 Issue #6309 remove duplicate commented out session test
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DefaultSessionCacheTest.java
Labels: Test

#6318 Issue #6309 remove duplicate commented out session test (#6310)
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DefaultSessionCacheTest.java
Labels: Test

#6301 Issue #6268 Log max form size exceeded msg.
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
Labels: Enhancement, Low Priority

#6316 Issue #5684 Re-enable ValidUrlRuleTest.test(In)ValidShamrock
  jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/ValidUrlRuleTest.java
Labels: Test
