Repository jetty/jetty.project, pull requests merged in 2022-02, with the labels that each got.

#7505 Removing jetty-maven-plugin IT test javax-annotation-api
  jetty-maven-plugin/src/it/javax-annotation-api/invoker.properties
  jetty-maven-plugin/src/it/javax-annotation-api/pom.xml
  jetty-maven-plugin/src/it/javax-annotation-api/postbuild.groovy
  jetty-maven-plugin/src/it/javax-annotation-api/src/config/jetty.xml
  jetty-maven-plugin/src/it/javax-annotation-api/src/main/java/test/App.java
  jetty-maven-plugin/src/it/javax-annotation-api/src/main/resources/my.properties
Labels: Build

#7495 Issue #7494 - remove unsupported modules
  jetty-home/src/main/resources/modules/hawtio.mod
  jetty-home/src/main/resources/modules/hawtio/hawtio.xml
  jetty-home/src/main/resources/modules/jamon.mod
  jetty-home/src/main/resources/modules/jamon/jamon.xml
  jetty-home/src/main/resources/modules/jminix.mod
  jetty-home/src/main/resources/modules/jminix/jminix.xml
  jetty-home/src/main/resources/modules/jolokia.mod
  jetty-home/src/main/resources/modules/jolokia/jolokia.xml
  pom.xml
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/ThirdPartyModulesTests.java
Labels: dependencies

#7507 test not needed anymore as it was only an example to a maven issue fixed in 3.8.4
  jetty-maven-plugin/src/it/javax-annotation-api/invoker.properties
  jetty-maven-plugin/src/it/javax-annotation-api/pom.xml
  jetty-maven-plugin/src/it/javax-annotation-api/postbuild.groovy
  jetty-maven-plugin/src/it/javax-annotation-api/src/config/jetty.xml
  jetty-maven-plugin/src/it/javax-annotation-api/src/main/java/test/App.java
  jetty-maven-plugin/src/it/javax-annotation-api/src/main/resources/log4j.xml
  jetty-maven-plugin/src/it/javax-annotation-api/src/main/resources/my.properties
Labels: Test, Build

#7503 Jetty 9.4.x : fix tries mistakenly throwing ArrayIndexOutOfBoundsException
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTrie.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MathUtils.java
  jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
Labels: Bug

#7509 Jetty 10.0.x : fix tries mistakenly throwing ArrayIndexOutOfBoundsException
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTrie.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MathUtils.java
  jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
Labels: Bug

#7510 Issue #6017 - fix accidentally broken k+=v property usage
  jetty-start/src/main/java/org/eclipse/jetty/start/Module.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
Labels: Bug

#7530 Upgrade quiche native lib to version 0.11.0
  jetty-quic/quic-quiche/quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#7555 Bump slf4j to 2.0.0-alpha6
  pom.xml
Labels: dependencies

#7570 Issue #7569 - better error message if headerCacheSize is too large
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java
Labels: Enhancement

#7556 Fixing Jetty 10 release - must use Java 17
  Jenkinsfile
  javadoc/pom.xml
  pom.xml
Labels: Build

#7521 #7461 Fix flakey ConnectionPoolTest.testQueuedRequestsDontOpenTooManyConnections:
  jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java
Labels: Test

#7578 simplify pom by using simple property rather than xml fragment
  build-resources/pom.xml
  examples/pom.xml
  jetty-jmh/pom.xml
  jetty-osgi/test-jetty-osgi-context/pom.xml
  jetty-osgi/test-jetty-osgi-fragment/pom.xml
  jetty-osgi/test-jetty-osgi-server/pom.xml
  jetty-osgi/test-jetty-osgi-webapp-resources/pom.xml
  jetty-osgi/test-jetty-osgi-webapp/pom.xml
  tests/pom.xml
  tests/test-continuation/pom.xml
  tests/test-http-client-transport/pom.xml
  tests/test-jmx/jmx-webapp/pom.xml
  tests/test-sessions/test-file-sessions/pom.xml
  tests/test-sessions/test-gcloud-sessions/pom.xml
  tests/test-sessions/test-hazelcast-sessions/pom.xml
  tests/test-sessions/test-infinispan-sessions/pom.xml
  tests/test-sessions/test-jdbc-sessions/pom.xml
  tests/test-sessions/test-memcached-sessions/pom.xml
  tests/test-sessions/test-mongodb-sessions/pom.xml
  tests/test-webapps/pom.xml
  tests/test-webapps/test-jaas-webapp/pom.xml
  tests/test-webapps/test-jetty-webapp/pom.xml
  tests/test-webapps/test-jndi-webapp/pom.xml
  tests/test-webapps/test-proxy-webapp/pom.xml
  tests/test-webapps/test-servlet-spec/pom.xml
  tests/test-webapps/test-servlet-spec/test-spec-webapp/pom.xml
  tests/test-webapps/test-webapp-rfc2616/pom.xml
Labels: Build

#7595 Issue #7461 - fix flakey test queued requests dont open too many connections
  jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java
Labels: Test

#7596 Issue #7572 - make legit test exception less noisy
  jetty-server/src/test/java/org/eclipse/jetty/server/ConnectorTimeoutTest.java
Labels: Test

#7599 Honor parameters order when parsing query and form parameters
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MultiMap.java
Labels: Enhancement

#7605 Honor parameters order when parsing query and form parameters (#7599)
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/MultiMap.java
Labels: Enhancement

#7604 Enable errorprone and spotbugs for java 17
  .mvn/jvm.config
  Jenkinsfile
  pom.xml
Labels: Build

#7607 ignore too recent weld version for 9.4.x branch
  .github/dependabot.yml
Labels: Build

#7374 Issue #7344 - wait for forked jetty process
  jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/MockShutdownMonitor.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/MockShutdownMonitorRunnable.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/TestJettyStopMojo.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ShutdownMonitor.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ShutdownMonitorTest.java
Labels: Enhancement

#7606 Issue #5965 - fixing invalid dot output from start.jar
  jetty-start/src/main/java/org/eclipse/jetty/start/ModuleGraphWriter.java
  jetty-start/src/test/java/org/eclipse/jetty/start/ModuleGraphWriterTest.java
Labels: Bug

#7651 Jetty 12.0.x revert bad merge
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractEndPoint.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IdleTimeout.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MappedByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPoolTest.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/MappedByteBufferPoolTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/StopLifeCycle.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/security/Credential.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/security/Password.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/Invocable.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/StringUtilTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/component/ContainerLifeCycleListenerTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/component/LifeCycleListenerTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/security/CredentialTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/security/PasswordTest.java
Labels: Bug, Build

#7626 add used but non declared dependencies and fix some scope
  javadoc/pom.xml
  jetty-jspc-maven-plugin/pom.xml
  jetty-maven-plugin/pom.xml
  pom.xml
Labels: Build
