Repository jetty/jetty.project, pull requests merged in 2022-03, with the labels that each got.

#7640 Issue #5965 - fixing invalid dot output from start.jar (#7606)
  jetty-start/src/main/java/org/eclipse/jetty/start/ModuleGraphWriter.java
  jetty-start/src/test/java/org/eclipse/jetty/start/ModuleGraphWriterTest.java
Labels: Bug, merge-12-needed

#7687 remove some site configuration, non used checkstyle profile and turn skip xml into one line property
  apache-jsp/pom.xml
  apache-jstl/pom.xml
  jetty-ant/pom.xml
  jetty-http-spi/pom.xml
  jetty-jspc-maven-plugin/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-osgi/pom.xml
  pom.xml
  tests/test-webapps/pom.xml
Labels: Build

#7690 jetty 9.4.x remove non used maven plugin
  apache-jsp/pom.xml
  apache-jstl/pom.xml
  jetty-ant/pom.xml
  jetty-http-spi/pom.xml
  jetty-jspc-maven-plugin/pom.xml
  jetty-maven-plugin/pom.xml
  jetty-osgi/pom.xml
  jetty-spring/pom.xml
  pom.xml
Labels: Build

#7763 Issue #7615 HttpServletResponse.encodeURL() should support relative paths
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
Labels: Bug

#7614 Added test for Regex mapping for Servlet
  jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/RegexServletTest.java
Labels: Enhancement, Sponsored, merge-12-needed

#7618 Issue #7617 - RequestLog content params extraction prevention
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java
Labels: Bug, merge-12-needed

#7765 Fix #7615 encode relative URIs
  jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
Labels: Bug

#7563 Fixes #7548 - Interrupt flag is not always cleared in between requests.
  jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
Labels: merge-12-needed

#7184 Issue #7182 having running() delete the state file where it previously only deleted the pid file.
  jetty-home/src/main/resources/bin/jetty.sh
Labels: Bug, merge-12-needed

#7770 Issue #6879 - Remove jminix
  jetty-home/src/main/resources/modules/jminix.mod
  jetty-home/src/main/resources/modules/jminix/jminix.xml
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/ThirdPartyModulesTests.java
Labels: Task

#7772 Issue #7771 - More Javadoc about WSUF and addMapping usage.
  jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeFilter.java
Labels: Documentation

#7776 Fixes #7774 - Flaky Test: DataDemandTest.testBlockingReadInADifferent…
  jetty-http3/http3-common/src/main/java/org/eclipse/jetty/http3/internal/HTTP3StreamConnection.java
  jetty-http3/http3-tests/src/test/java/org/eclipse/jetty/http3/tests/DataDemandTest.java
Labels: Test, merge-12-needed, flaky-test

#7769 Issue #5681 - clearer warning on JVM Arg / System Property use
  jetty-start/src/main/java/org/eclipse/jetty/start/Main.java
  jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java
  jetty-start/src/test/java/org/eclipse/jetty/start/PropertyDump.java
  jetty-start/src/test/java/org/eclipse/jetty/start/usecases/BasicTest.java
Labels: Enhancement

#7658 Issue #7657 Remove unused test imports in jetty-nosql
  jetty-nosql/pom.xml
Labels: merge-12-needed

#7682 Issue #7677 Exclude findbugs jsr305 jar from plugin
  jetty-maven-plugin/src/it/exclude-javax-annotation/invoker.properties
  jetty-maven-plugin/src/it/exclude-javax-annotation/pom.xml
  jetty-maven-plugin/src/it/exclude-javax-annotation/postbuild.groovy
  jetty-maven-plugin/src/it/exclude-javax-annotation/src/config/jetty.xml
  jetty-maven-plugin/src/it/exclude-javax-annotation/src/main/java/org/github/unb/TestServlet.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/it/IntegrationTestGetContent.java
  pom.xml
Labels: merge-12-needed

#7656 Issue #7655 Remove unused test imports for jetty-gcloud
  jetty-gcloud/jetty-gcloud-session-manager/pom.xml
Labels: merge-12-needed

#7800 Fixes #7575 - Misleading docs for HttpClientTransportDynamic
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/client/http/client-http-transport.adoc
  jetty-client/src/main/java/org/eclipse/jetty/client/dynamic/HttpClientTransportDynamic.java
Labels: Documentation, merge-12-needed

#7813 Fixes #6756 - Deprecate `jetty-spring` sub-project
  jetty-spring/pom.xml
  jetty-spring/src/main/java/org/eclipse/jetty/spring/Main.java
  jetty-spring/src/main/java/org/eclipse/jetty/spring/SpringConfigurationProcessor.java
  jetty-spring/src/main/java/org/eclipse/jetty/spring/SpringConfigurationProcessorFactory.java
  jetty-spring/src/main/java/org/eclipse/jetty/spring/package-info.java
  jetty-spring/src/test/resources/org/eclipse/jetty/spring/configure.xml
Labels: Task, dependencies
