Repository jetty/jetty.project, pull requests merged in 2022-01, with the labels that each got.

#7316 Issue #7277 - Allow `Request.getLocalName()` and `.getLocalPort()` to be overridden (Split authority approach)
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DetectorConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpConfigurationAuthorityOverrideTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/HostPort.java
Labels: Enhancement, Sponsored

#7357 Issue #7277 - Allow `Request.getLocalName()` and `.getLocalPort()` to be overridden
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DetectorConnectionTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/DumpHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpConfigurationAuthorityOverrideTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/HostPort.java
Labels: Enhancement, Sponsored

#7376 Issue #7375 Request scoped session saves
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/RequestScopedSessionSaveTest.java
Labels: Sponsored

#7421 Fix flakey RoundRobinConnectionPoolTest test
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/RoundRobinConnectionPoolTest.java
Labels: Bug, Test

#7434 Fix log4j2 module
  jetty-util/src/main/config/modules/log4j2-api.mod
  jetty-util/src/main/config/modules/log4j2-impl.mod
  pom.xml
Labels: dependencies

#7452 configure dependabot to only look after infinispan < 12
  .github/dependabot.yml
Labels: Build

#7405 #7271 add checks for max capacity in tries
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java
  jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTrie.java
  jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
Labels: Enhancement, Bug

#7454 Limit dependabot version ranges for infinispan, jakarta.cdi, and jakarta.transactions
  .github/dependabot.yml
Labels: Bug

#7464 Remove aggregate-jar goal as it prevents deploy
  scripts/release-jetty.sh
Labels: Build

#7476 Issue #7435 - update infinispan deps (9.4.x)
  pom.xml
Labels: Build, dependencies

#7477 Issue #7435 - update infinispan deps (10.0.x)
  jetty-maven-plugin/src/it/it-parent-pom/pom.xml
  pom.xml
Labels: Build, dependencies

#7483 Adding back jetty-11 config to dependabot
  .github/dependabot.yml
Labels: Build
