Repository jetty/jetty.project, pull requests merged in 2022-04, with the labels that each got.

#7803 unwrap exception until we get the first non ServletException, as this can be wrap of wrap of wrap when using ContextHandlerCollection
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ErrorPageErrorHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ErrorPageTest.java
Labels: Bug, merge-12-needed

#7834 Issue #7748 - Backport of allow override of path mapping behavior in ServletContextHandler
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/RegexPathSpecTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpecTest.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
Labels: Enhancement, Sponsored

#7845 Issue #7748 - Merge PathSpec improvements made in 9.4.x
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/RegexPathSpecTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpecTest.java
Labels: Enhancement

#7851 Issue #7818 - HttpChannel.Listener.onResponseBegin() Test
  jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelEventTest.java
Labels: Test

#7856 Issue #7855 - maven compiler plugin should not generate package-info.class files
  pom.xml
Labels: Build

#7857 Issue #7855 - maven compiler plugin should not generate package-info.class files
  pom.xml
Labels: Build

#7866 Update to Tycho 2.7.1 Bugfix release
  jetty-p2/pom.xml
Labels: Build

#7865 upgrade maven-shade-plugin 3.3.0 working with Maven 3.8.5 (skip this dependency-reduced pom generation as we do not use and it causes issues)
  pom.xml
Labels: Build

#7867 shade plugin 3.3.0 (#7865)
  pom.xml
Labels: Build

#7892 Fix #7891 regex pathInfo
  jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/RegexServletTest.java
Labels: Sponsored

#7924 Fix an error
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/begin/deploy.adoc
Labels: Documentation

#7931 Fix #7929 requestlog format string commented default
  jetty-server/src/main/config/modules/requestlog.mod
Labels: Documentation
