Repository jetty/jetty.project, pull requests merged in 2022-06, with the labels that each got.

#8094 exclude log4j-core to avoid problem with m-enforcer-p see https://issues.apache.org/jira/browse/LOG4J2-3241
  javadoc/pom.xml
  jetty-infinispan/infinispan-common/pom.xml
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-infinispan/infinispan-remote/pom.xml
  tests/test-sessions/test-infinispan-sessions/pom.xml
Labels: Build

#8104 Update security checklist: bugzilla -> gitlab
  SECURITY.md
  advisories/2015-02-24-httpparser-error-buffer-bleed.md
Labels: Task, Documentation

#8113 exclude log4j-core to avoid problem with m-enforcer-p see https://issues.apache.org/jira/browse/LOG4J2-3241 (#8094)
  jetty-infinispan/infinispan-common/pom.xml
  jetty-infinispan/infinispan-remote-query/pom.xml
  jetty-infinispan/infinispan-remote/pom.xml
  tests/test-sessions/test-infinispan-sessions/pom.xml
Labels: Build

#8089 Issue #8088 Add STOP.EXIT System property to configure ShutdownMonitor.exitVm
  jetty-server/src/main/java/org/eclipse/jetty/server/ShutdownMonitor.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ShutdownMonitorTest.java
Labels: Sponsored

#7947 Improved PathSpec handling for servletName & pathInfo
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/AbstractPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/MatchedPath.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/MatchedResource.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpecSet.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/RegexPathSpecTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/ServletPathSpecOrderTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/ServletPathSpecTest.java
  jetty-http/src/test/resources/jetty-logging.properties
  jetty-server/src/main/java/org/eclipse/jetty/server/AbstractNCSARequestLog.java
  jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/Invoker.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/NativeWebSocketConfiguration.java
  jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeFilter.java
  jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeHandlerWrapper.java
Labels: Enhancement, Sponsored

#8136 Cherry-pick of Improvements to PathSpec for Jetty 10.0.x
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/AbstractPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/MatchedPath.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/MatchedResource.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpecSet.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/UriTemplatePathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/RegexPathSpecTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/ServletPathSpecOrderTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/ServletPathSpecTest.java
  jetty-http/src/test/resources/jetty-logging.properties
  jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java
  jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java
  jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/Invoker.java
  jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/RegexServletTest.java
  jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketMappings.java
Labels: Enhancement, Sponsored

#8133 Issue #8088 Add STOP.EXIT System property to configure ShutdownMonitor.exitVm
  jetty-server/src/main/java/org/eclipse/jetty/server/ShutdownMonitor.java
  jetty-server/src/test/java/org/eclipse/jetty/server/ShutdownMonitorTest.java
Labels: Sponsored

#8139 update readme as IT tests are running per default now
  jetty-maven-plugin/README_INTEGRATION_TEST.md
Labels: Documentation, Build

#8138 no more profile IT tests runs per default
  jetty-maven-plugin/README_INTEGRATION_TEST.md
Labels: Documentation, Build

#8134 Improve cleanup of deflater/inflater pools for PerMessageDeflateExtension
  jetty-util/src/main/java/org/eclipse/jetty/util/compression/CompressionPool.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/Extension.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/ExtensionStack.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/TransformingFlusher.java
  jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketCoreSession.java
  jetty-websocket/websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/PermessageDeflateBufferTest.java
Labels: Sponsored

#8162 Migrate code from jetty-util Logger to slf4j Logger
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartInputStreamParser.java
  jetty-websocket/websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/proxy/WebSocketProxy.java
Labels: Bug, Task

#8150 Disable H3 tests by default with a system property to explicitly enable them
  tests/test-http-client-transport/pom.xml
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/TransportProvider.java
Labels: Enhancement, http3

#8163 RegexPathSpec documentation and MatchedPath improvements
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/RegexPathSpecTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/RegexServletTest.java
Labels: Enhancement, Documentation

#8175 Removing invalid maxConnections references
  jetty-server/src/main/config/etc/jetty-lowresources.xml
  jetty-server/src/main/config/modules/lowresources.mod
Labels: Bug

#8185 Issue #8184 - Correcting match logic for multiple servlet suffix url-pattern
  jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
  jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
Labels: High Priority, Bug

#8205 skip default checkout option to avoid a useless git fetch
  Jenkinsfile
Labels: Build

#8217 Go back to simpler Jenkinsfile
  Jenkinsfile
Labels: jetty 12

#8219 Issue #7833 - Chunked Transfer-Encoding and HEAD response test
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/HugeResourceTest.java
Labels: Test

#8226 Issue #7833 - Chunked Transfer-Encoding and HEAD response test
  jetty-webapp/src/test/java/org/eclipse/jetty/webapp/HugeResourceTest.java
Labels: Test

#8034 add jetty-osgi dependency to jetty-p2 to be sure it is included
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-p2/pom.xml
  pom.xml
Labels: Build
