Repository jetty/jetty.project, pull requests merged in 2023-06, with the labels that each got.

#9803 jetty-util: don't override Enumeration methods in QuotedStringTokenizer
  jetty-util/src/main/java/org/eclipse/jetty/util/QuotedStringTokenizer.java
Labels: Enhancement

#9800 Fixes #9795 - jetty-slf4j-impl is non-optional on some modules
  demos/demo-jetty-webapp/pom.xml
  demos/demo-proxy-webapp/pom.xml
  jetty-http3/http3-common/pom.xml
  jetty-infinispan/infinispan-embedded-query/pom.xml
  tests/test-jmx/jmx-webapp/pom.xml
  tests/test-jpms/pom.xml
  tests/test-webapps/test-http2-webapp/pom.xml
  tests/test-webapps/test-openid-webapp/pom.xml
  tests/test-webapps/test-websocket-client-provided-webapp/pom.xml
  tests/test-webapps/test-websocket-client-webapp/pom.xml
  tests/test-webapps/test-websocket-webapp/pom.xml
Labels: Build, dependencies

#9781 Issue #9657 Upgrade request should throw ServletException
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
Labels: Bug, TCK

#9882 Issue #9879 re-enable and fix rewrite demo
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-jetty-webapp/src/main/config/modules/demo.d/ee10-demo-rewrite-rules.xml
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-jetty-webapp/src/main/config/modules/ee10-demo-jetty.mod
  jetty-ee8/jetty-ee8-demos/jetty-ee8-demo-jetty-webapp/src/main/config/modules/demo.d/ee8-demo-rewrite-rules.xml
  jetty-ee8/jetty-ee8-demos/jetty-ee8-demo-jetty-webapp/src/main/config/modules/ee8-demo-jetty.mod
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-jetty-webapp/src/main/config/modules/demo.d/ee9-demo-rewrite-rules.xml
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-jetty-webapp/src/main/config/modules/ee9-demo-jetty.mod
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
Labels: Bug

#9884 Fix `QueuedPool`'s performance
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java
Labels: Bug

#9902 Jetty 12.0.x ee9 serverpush tck
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/java/org/eclipse/jetty/ee9/test/client/transport/AbstractTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/java/org/eclipse/jetty/ee9/test/client/transport/PushedResourcesTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/resources/serverpushtck/secondary1.html
Labels: Bug, TCK

#9907 Issue #9906 Empty path info
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletHandler.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextHandlerTest.java
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/ServletHandler.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ServletContextHandlerTest.java
Labels: Bug

#9893 Pause before checking session eviction
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/AsyncTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/CreationTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/SameContextForwardedSessionTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/AsyncTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/CreationTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/SameContextForwardedSessionTest.java
Labels: Bug, Test

#9917 Upgrade Guava to 32.0.1
  pom.xml
Labels: dependencies

#9929 Fix spotbugs packages
  jetty-core/jetty-alpn/jetty-alpn-client/pom.xml
  jetty-core/jetty-alpn/jetty-alpn-server/pom.xml
  jetty-core/jetty-client/pom.xml
  jetty-core/jetty-deploy/pom.xml
  jetty-ee10/jetty-ee10-annotations/pom.xml
  jetty-ee10/jetty-ee10-jaspi/pom.xml
  jetty-ee10/jetty-ee10-plus/pom.xml
  jetty-ee10/jetty-ee10-servlet/pom.xml
  jetty-ee8/jetty-ee8-annotations/pom.xml
  jetty-ee8/jetty-ee8-nested/pom.xml
  jetty-ee8/jetty-ee8-openid/pom.xml
  jetty-ee8/jetty-ee8-plus/pom.xml
  jetty-ee8/jetty-ee8-security/pom.xml
  jetty-ee8/jetty-ee8-servlet/pom.xml
  jetty-ee9/jetty-ee9-annotations/pom.xml
  jetty-ee9/jetty-ee9-jaspi/pom.xml
  jetty-ee9/jetty-ee9-nested/pom.xml
  jetty-ee9/jetty-ee9-openid/pom.xml
  jetty-ee9/jetty-ee9-plus/pom.xml
  jetty-ee9/jetty-ee9-proxy/pom.xml
  jetty-ee9/jetty-ee9-security/pom.xml
  jetty-ee9/jetty-ee9-servlet/pom.xml
  pom.xml
Labels: Build

#9924 Upgrade of dependencies: slf4j 2.0.7, and some 3rd parties dependencies used for testing
  jetty-ee10/pom.xml
  pom.xml
Labels: dependencies

#9930 mark CloseableDoSFilterTest#testEvenLowRateIP as flaky tests
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/CloseableDoSFilterTest.java
  jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/CloseableDoSFilterTest.java
Labels: Build, flaky-test

#9920 Remove ee10 HttpChannel.Listener
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletRequestLogTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/GzipWithSendErrorTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
Labels: Enhancement, Bug

#9934 Fix ee10 path info only (alternative)
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/resources/pathTest/default/dot
  jetty-ee10/jetty-ee10-servlet/src/test/resources/pathTest/rdir/dot
Labels: Bug

#9950 Jetty 12 #9949 stop test
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/StopTest.java
Labels: Test

#9948 #9946 Stop passing Handler in constructor as a parent
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/session/SessionDocs.java
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/websocket/WebSocketServerDocs.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Handler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/StopTest.java
  jetty-ee10/jetty-ee10-apache-jsp/src/test/java/org/eclipse/jetty/ee10/jsp/TestJettyJspServlet.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/Http2Server.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ManyServletContexts.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ProxyServer.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-jetty-webapp/src/test/java/org/eclipse/jetty/ee10/ChatServletTest.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-jetty-webapp/src/test/java/org/eclipse/jetty/ee10/DispatchServletTest.java
  jetty-ee10/jetty-ee10-fcgi-proxy/src/test/java/org/eclipse/jetty/ee10/fcgi/proxy/TryFilesFilterTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/AsyncMiddleManServletTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/BalancerServletTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ClientAuthProxyTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ForwardProxyServerTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServer.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletFailureTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletLoadTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ReverseProxyTest.java
  jetty-ee10/jetty-ee10-runner/src/main/java/org/eclipse/jetty/ee10/runner/Runner.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletTester.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextListenersTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncServletLongPollTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherForwardTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/FormTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/GzipHandlerBreakEvenSizeTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/GzipHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/InitServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RegexServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/SSLAsyncIOServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletLifeCycleTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/AbstractDoSFilterTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/CrossOriginFilterTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/DoSFilterJMXTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/EventSourceServletTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/HeaderFilterTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/IncludeExcludeBasedFilterTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/QoSFilterTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/ThreadStarvationTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/HttpInputIntegrationTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/main/java/org/eclipse/jetty/ee10/session/SessionTestSupport.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/RequestDispatchedSessionTest.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppDefaultServletTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/LocalServer.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/server/MemoryUsageTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/server/ServerDecoderTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HandlerWrapper.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
Labels: Enhancement

#9952 Disable parallel execution of module that contains DistributionTests
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: flaky-test

#9968 Deflake ReservedThreadExecutorTest
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/ReservedThreadExecutorTest.java
Labels: flaky-test

#9970 Fix default servlet character encoding directories
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceListing.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
Labels: Bug

#9978 Adding test to prove out zipfs bug with backslash character
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/MountedPathResourceTest.java
Labels: Test, JVM Issue, Jetty 12

#9974 Fix ServletContext.getResourcePaths()
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee10/jetty-ee10-webapp/pom.xml
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/acme/webapp/GetRealPathsServlet.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/acme/webapp/GetResourcePathsServlet.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/webapp-with-resources/WEB-INF/lib/odd-resource.jar
  jetty-ee10/jetty-ee10-webapp/src/test/webapp-with-resources/WEB-INF/web.xml
Labels: Bug

#9985 #9984 fix URLResourceFactory isDirectory and newReadableByteChannel
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/URLResourceFactory.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/UrlResourceFactoryTest.java
Labels: Bug

#9992 Add jdk bug ID
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/MountedPathResourceTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
Labels: Enhancement, Test

#9993 Remove file buffered response handler
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/FileBufferedResponseHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/FileBufferedResponseHandlerTest.java
Labels: Enhancement

#9995 Issue #9973 - Unwrap URI.scheme-specific-parts until we find a path we can resolve against.
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/URLResourceFactory.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/UrlResourceFactoryTest.java
Labels: Bug, Jetty 12

#9997 No progress during Gzip Request Inflation results in bogus error
  jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java
  jetty-server/src/test/java/org/eclipse/jetty/server/AsyncContentProducerTest.java
  jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerInputTest.java
Labels: Bug

#9988 Add constructors accepting the handler to wrap to all core handler wrappers
  documentation/jetty-documentation/src/main/asciidoc/old_docs/extras/default-handler.adoc
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/http/server-http-handler-use.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/BufferedResponseHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ConnectHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/DebugHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/DelayedHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/GracefulHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/IdleTimeoutHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/SecuredRedirectHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ShutdownHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/TryPathsHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/StatisticsHandlerTest.java
Labels: Enhancement

#10002 Merge `jetty-11.0.x` into `jetty-12.0.x`
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/AsyncContentProducer.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/AsyncContentProducerTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/BlockingContentProducerTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/GzipHandlerInputTest.java
Labels: Build
