Repository jetty/jetty.project, pull requests merged in 2023-05, with the labels that each got.

#9670 Jetty 12 - Fix `HostHeaderCustomizer` and improve tests
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HostHeaderCustomizerTest.java
Labels: Enhancement, Test, Jetty 12

#9725 jetty 12.0.x rename jakarta classes as well
  jetty-ee8/pom.xml
Labels: Build

#9732 Issue #9731 infinite loop in role refs
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/internal/DefaultUserIdentity.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/UserIdentityScope.java
  jetty-ee9/jetty-ee9-security/src/main/java/org/eclipse/jetty/ee9/security/AbstractUserAuthentication.java
Labels: Bug

#9668 Issue #9649 ServletApiResponse.addIntHeader must ignore headers after commit
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ErrorPageTest.java
Labels: TCK

#9673 Issue #9650 throw ISE if response committed before resetBuffer called
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ErrorPageTest.java
Labels: TCK

#9744 Issue #9743 changeSessionId should throw ISE if no session
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
Labels: Bug, TCK

#9735 Issue #9734 fix check for state start in cookie config
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/SessionHandler.java
Labels: Bug, TCK

#9751 Issue #9750 Fix value of login-config/auth-method for CLIENT-CERT
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/DefaultAuthenticatorFactory.java
Labels: Bug, TCK

#9752 Fix invalid warning
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
Labels: Bug

#9757 Issue #9745 Role * wins over specific roles
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/StandardDescriptorProcessor.java
Labels: Bug, TCK

#9764 Issue #9762 ee9 double parses cookies
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/CookieCache.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RequestTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
Labels: Bug, TCK

#9683 Don't use `ResourceFactory.root()` in `AttributeNormalizer`
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resources.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
Labels: Bug

#9724 Jetty 12 immutable ee10 configurations
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IncludeExcludeSet.java
  jetty-ee10/jetty-ee10-annotations/src/main/java/org/eclipse/jetty/ee10/annotations/AnnotationConfiguration.java
  jetty-ee10/jetty-ee10-annotations/src/test/java/org/eclipse/jetty/ee10/annotations/TestAnnotationConfiguration.java
  jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiConfiguration.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/MavenWebAppContext.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/MavenWebInfConfiguration.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/annotations/AnnotationConfiguration.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/webapp/EnvConfiguration.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/webapp/PlusConfiguration.java
  jetty-ee10/jetty-ee10-quickstart/src/main/java/org/eclipse/jetty/ee10/quickstart/QuickStartConfiguration.java
  jetty-ee10/jetty-ee10-quickstart/src/main/java/org/eclipse/jetty/ee10/quickstart/QuickStartGeneratorConfiguration.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/DeploymentErrorTest.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/AbstractConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/ClassMatcher.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/Configuration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/Configurations.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/FragmentConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JaasConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JaspiConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JmxConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JndiConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JspConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/ServletsConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebXmlConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/ConfigurationsTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/config/JakartaWebSocketConfiguration.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-client/src/main/java/org/eclipse/jetty/ee10/websocket/client/config/JettyWebSocketClientConfiguration.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/config/JettyWebSocketConfiguration.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
  tests/test-distribution/test-ee9-distribution/src/test/java/org/eclipse/jetty/ee9/tests/distribution/openid/OpenIdProvider.java
Labels: Jetty 12

#9771 remove snapshot repositories, force module order (may not work with mvnd)
  Jenkinsfile
  pom.xml
Labels: Build

#9684 Refine how Request / Channel / Stream completion works
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpHeader.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/StreamResetTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/LargeHeaderTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ResponseCompleteTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ServerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/StatisticsHandlerTest.java
  jetty-core/jetty-server/src/test/resources/jetty-logging.properties
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
Labels: Bug, Jetty 12

#9761 H3: Fix racy read from stream-less channel
  jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java
  jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3StreamClient.java
  jetty-http3/http3-common/src/main/java/org/eclipse/jetty/http3/api/Stream.java
  jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java
  jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpSenderOverHTTP3.java
  tests/test-http-client-transport/src/test/resources/jetty-logging.properties
Labels: Bug

#9775 Issue #9774 Disallow cross context
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
Labels: Bug, TCK

#9786 Issue #9785 context path set incorrectly for ee9
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
Labels: Bug, TCK

#9791 Fix flaky test testBlockingReadInADifferentThread
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java
Labels: Bug

#9804 Issue #9770 test if dot executable is available during release
  pom.xml
Labels: Build
