Repository jetty/jetty.project, pull requests merged in 2023-08, with the labels that each got.

#10180 Ensure @BeforeEach and @AfterEach are public methods (not protected)
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign-incubator/src/test/java/org/eclipse/jetty/quic/quiche/foreign/incubator/LowLevelQuicheClientCertTest.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign-incubator/src/test/java/org/eclipse/jetty/quic/quiche/foreign/incubator/LowLevelQuicheTest.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/test/java/org/eclipse/jetty/quic/quiche/jna/LowLevelQuicheClientCertTest.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/test/java/org/eclipse/jetty/quic/quiche/jna/LowLevelQuicheTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppDefaultServletCacheTest.java
Labels: Test, Jetty 12

#10206 Merge release `jetty-12.0.0.beta4` back into `jetty-12.0.x` HEAD
  VERSION.txt
Labels: Build, Jetty 12

#10228 Issue #10227 - `HttpServletResponse.addCookie(Cookie)` support for Cookie attributes
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/SetCookieTest.java
Labels: Bug, Jetty 12

#10232 Issue #10231 - ee10 `DefaultServlet` HTTP method support.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
  jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/AbstractGzipTest.java
  jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/GzipDefaultServletTest.java
Labels: Bug, Jetty 12

#10221 Include section on building Jetty in README
  README.md
Labels: Documentation

#10163 Allow better configuration of WebAppContext classloader
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppClassLoader.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppClassLoader.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
Labels: Sponsored

#10299 Issue #10066 - Allow customization of `SAXParserFactory` and `SAXParser` in `XmlParser`
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentTempDirTest.java
  jetty-deploy/src/test/resources/context-binding-test-1.xml
  jetty-deploy/src/test/resources/jetty.xml
  jetty-documentation/src/main/asciidoc/quick-start/configuring/what-to-configure.adoc
  jetty-maven-plugin/src/it/run-mojo-gwt-it/beer-server/src/config/jetty.xml
  jetty-maven-plugin/src/it/run-mojo-gwt-it/beer-server/src/main/jettyconf/context.xml
  jetty-start/src/test/resources/bogus.xml
  jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java
  jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
  jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java
  jetty-xml/src/test/resources/org/eclipse/jetty/xml/mortbay.xml
  tests/test-integration/src/test/resources/RFC2616Base.xml
  tests/test-integration/src/test/resources/ssl.xml
  tests/test-webapps/test-owb-cdi-webapp/src/main/webapp/WEB-INF/jetty-web-owb.xml
Labels: Enhancement, Sponsored

#10316 Cleaning up dependencies on WebSocket Server
  jetty-websocket/websocket-jetty-server/pom.xml
  jetty-websocket/websocket-jetty-tests/pom.xml
Labels: dependencies

#10318 Bump guava to 32.1.2-jre
  pom.xml
Labels: dependencies

#10276 Issue #10274 - Improve javadoc + move internal methods
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/package-info.java
Labels: Enhancement, Documentation

#10214 Issue #10213 - Ensuring proper usage of StartLog logging
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/FS.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/FileInitializer.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/Main.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/PathFinder.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/PathMatchers.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartEnvironment.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/builders/StartDirBuilder.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/BaseHomeFileInitializer.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/DownloadFileInitializer.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/LocalFileInitializer.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializer.java
Labels: Bug, Jetty 12

#10209 Issue #10158 - tests to prove out XML only based deployment technique
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Test, Jetty 12

#10329 Various cleanups in HttpParser
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
Labels: Enhancement

#10343 Fixes #10315 - ServletInputStream::isReady results in IllegalArgument…
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AsyncIOServletTest.java
Labels: High Priority

#10310 Issue #10309 - Duplicate `X-Powered-By` headers
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ssl/SSLEngineTest.java
Labels: Bug, Jetty 12

#9871 Jetty 12.0.x use Maven build cache for PRs and branches except jetty-12.0.x main branch
  .github/workflows/codeql-analysis.yml
  .mvn/jvm.config
  .mvn/maven-build-cache-config.xml
  .mvn/maven.config
  Jenkinsfile
  README.md
  build/scripts/dependency-update-reports.sh
  build/scripts/release-jetty.sh
  documentation/jetty-documentation/pom.xml
  documentation/jetty-documentation/src/main/asciidoc/contribution-guide/4-build.adoc
  jetty-core/jetty-alpn/jetty-alpn-client/pom.xml
  jetty-core/jetty-alpn/jetty-alpn-server/pom.xml
  jetty-core/jetty-start/pom.xml
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/PropertyPassingTest.java
  jetty-core/jetty-util/pom.xml
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/pom.xml
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/JettyDemos.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/LikeJettyXml.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/OneWebApp.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/OneWebAppWithJsp.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ServerWithAnnotations.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ServerWithJNDI.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-spec/jetty-ee10-demo-spec-webapp/pom.xml
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-spec/jetty-ee10-demo-spec-webapp/src/test/java/org/eclipse/jetty/ee10/demos/SpecWebAppTest.java
  jetty-ee10/jetty-ee10-jspc-maven-plugin/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/it/jetty-cdi-start-forked/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/it/jetty-start-distro-mojo-it/jetty-simple-webapp/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/it/jetty-start-war-distro-mojo-it/jetty-simple-webapp/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/it/settings.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/JettyHomeForker.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/pom.xml
  jetty-ee8/jetty-ee8-jspc-maven-plugin/pom.xml
  jetty-ee8/jetty-ee8-maven-plugin/pom.xml
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/pom.xml
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/JettyDemos.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/OneWebApp.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/OneWebAppWithJsp.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/ServerWithAnnotations.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/ServerWithJNDI.java
  jetty-ee9/jetty-ee9-jspc-maven-plugin/pom.xml
  jetty-ee9/jetty-ee9-maven-plugin/pom.xml
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/AbstractWebAppMojo.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/pom.xml
  pom.xml
  tests/test-distribution/pom.xml
Labels: Build

#10270 no need to setup maven twice just use the wrapper
  .github/workflows/codeql-analysis.yml
Labels: Build

#10344 Issue #10337 - fixes to SizeLimitHandler
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/SizeLimitHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/SizeLimitHandlerTest.java
Labels: Sponsored

#10395 jetty 12.0.x merge from 11.0.x
  pom.xml
Labels: Build

#10393 Jetty 12.0.x fix cache issue with maven invoker
  .mvn/maven-build-cache-config.xml
  Jenkinsfile
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/pom.xml
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/MetaInfConfigurationTest.java
  pom.xml
Labels: Build

#10364 Make JettyHomeTester more resilient to blank mavenLocalRepository input
  tests/jetty-home-tester/src/main/java/org/eclipse/jetty/tests/hometester/JettyHomeTester.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/BadAppTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DynamicListenerTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/GzipModuleTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/LoggingOptionsTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/ModulesTest.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/OsgiAppTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/StatsTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/session/AbstractSessionDistributionTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/session/HazelcastSessionDistributionTests.java
  tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/OpenIdTests.java
  tests/test-distribution/test-ee9-distribution/src/test/java/org/eclipse/jetty/ee9/tests/distribution/OpenIdTests.java
Labels: Build, Jetty 12

#10391 Issue #10385 - fix NPE in GzipDefaultServletTest
  jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/GzipDefaultServletTest.java
Labels: Test

#10313 Issue #10295 - implement EE10 FormAuthenticator with dispatch option
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/AuthenticationState.java
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/authentication/FormAuthenticator.java
  jetty-core/jetty-security/src/test/java/org/eclipse/jetty/security/AuthenticationTestHandler.java
  jetty-core/jetty-security/src/test/java/org/eclipse/jetty/security/BasicAuthenticatorTest.java
  jetty-core/jetty-security/src/test/java/org/eclipse/jetty/security/FormAuthenticatorTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ReHandlingErrorHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/TryPathsHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/security/FormAuthenticatorTest.java
Labels: Low Priority

#10406 Bump jetty-setuid to 2.0.1
  jetty-home/pom.xml
  jetty-home/src/main/resources/etc/jetty-setuid.xml
  jetty-home/src/main/resources/modules/setuid.mod
Labels: Bug, Jetty 12

#10407 Address transitive dependencies with open CVEs
  jetty-ee8/jetty-ee8-home/pom.xml
  jetty-ee8/pom.xml
  jetty-integrations/jetty-gcloud/jetty-gcloud-session-manager/pom.xml
  pom.xml
Labels: dependencies, Jetty 12

#10417 Fix #10416 Do not copy ee9 response headers
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/ResponseHttpFields.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/ContextHandlerTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/RequestTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/ResponseTest.java
Labels: build-no-cache

#10418 Fix #9169 refine idle timeout and failure
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ServerTest.java
Labels: build-no-cache

#10415 Fix #10411 default environment
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/deploy/deploy-jetty.adoc
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/deploy/deploy-rules.adoc
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentManager.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ScanningAppProvider.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentManagerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/MockAppProvider.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Deployable.java
Labels: build-no-cache

#10435 add source plugin to eclipse-release, as mentioned in comment :)
  pom.xml
Labels: Build

#10439 Backport `Request.beginNanoTime()` from 12.0.x
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java
  jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
Labels: Enhancement
