Repository jetty/jetty.project, pull requests merged in 2023-10, with the labels that each got.

#10655 Fixes #10611 - Flaky StreamResetTest.testClientResetConsumesQueuedData()
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AbstractTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/PrefaceTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/RawHTTP2ProxyTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/RequestTrailersTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/StreamCountTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/StreamResetTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientDemandTest.java
Labels: build-all-tests

#10671 Disable more flaky tests failing because of buffer leaks
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
Labels: Bug

#10660 Issue #7408 fix scope of Maven plugins dependencies and re enable some IT tests
  jetty-ee10/jetty-ee10-jspc-maven-plugin/pom.xml
  jetty-ee10/jetty-ee10-jspc-maven-plugin/src/it/simple-jsp/postbuild.groovy
  jetty-ee10/jetty-ee10-maven-plugin/pom.xml
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/JettyStopMojo.java
  jetty-ee8/jetty-ee8-jspc-maven-plugin/pom.xml
  jetty-ee8/jetty-ee8-maven-plugin/pom.xml
  jetty-ee9/jetty-ee9-jspc-maven-plugin/pom.xml
  jetty-ee9/jetty-ee9-jspc-maven-plugin/src/it/simple-jsp/postbuild.groovy
  jetty-ee9/jetty-ee9-maven-plugin/pom.xml
  pom.xml
Labels: Build, dependencies

#10685 fix infinite recursion in server dump with Path
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Dumpable.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
Labels: High Priority

#10674 Rollback JDK21 requirements during Compile + Jar creation in Jetty 10+
  documentation/jetty-documentation/pom.xml
  pom.xml
  scripts/release-jetty.sh
Labels: Build

#10728 Fix flaky leaky h2 tests
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/StreamResetTest.java
Labels: flaky-test

#10708 Fix racy assertion in `HttpClientTLSTest.testHostNameVerificationFailure`
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTLSTest.java
Labels: Bug, flaky-test

#10706 Improve error message when no valid keystore can be found during startup
  jetty-http3/http3-tests/src/test/java/org/eclipse/jetty/http3/tests/HTTP3ServerConnectorTest.java
  jetty-quic/quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java
Labels: Bug

#10727 Fix EE10 removeAttributes
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RequestTest.java
Labels: Bug

#10742 Address build/test failure against bad entities.
  jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java
Labels: Test, Build

#10745 Merge 11 to 12 Issue #10731 wrong context attribute name javax.servlet instead of jakarta.servlet (#10735) and Address build/test failure against bad entities. (#10742)
  jetty-core/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlParserTest.java
  jetty-ee10/jetty-ee10-glassfish-jstl/src/test/java/org/eclipse/jetty/ee10/jstl/JspConfig.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee9/jetty-ee9-glassfish-jstl/src/test/java/org/eclipse/jetty/ee9/jstl/JspConfig.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartFormInputStream.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebInfConfiguration.java
Labels: Bug

#10667 Add configuration to allow deferring the initial Deployment until after Server is started
  jetty-deploy/pom.xml
  jetty-deploy/src/main/config/etc/jetty-deploy.xml
  jetty-deploy/src/main/config/modules/deploy.mod
  jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ScanningAppProvider.java
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/providers/WebAppProviderTest.java
  jetty-deploy/src/test/java/org/eclipse/jetty/deploy/test/XmlConfiguredJetty.java
  jetty-deploy/src/test/resources/jetty-deploy-wars.xml
  jetty-deploy/src/test/resources/jetty-logging.properties
  jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java
Labels: Enhancement, Sponsored

#10710 Allow POSTing with a URL not ending with '/' to jax-ws endpoints
  jetty-core/jetty-http-spi/pom.xml
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/HttpSpiContextHandler.java
  jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JaxWsEndpointTest.java
  jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/LoggingUtil.java
Labels: Bug

#10730 Fix NPE in ResponseListeners
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java
Labels: Bug

#10686 tag this test as external (not running on CI) as it is using external resource from https://open.api.ebay.com
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
Labels: Build

#10737 Jetty 12.0.x 10716 charset printwriter
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResponseHeadersTest.java
Labels: TCK

#10757 H3: Make sure ByteBuffers given to feedClearBytesForStream() don't make JNA choke
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
Labels: Bug

#10763 Fix client setting MAX_FIELD_SECTION_SIZE handling
  jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/ClientHTTP3Session.java
  jetty-http3/http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java
Labels: Bug

#10765 awaitility must be only test dependency
  jetty-core/jetty-deploy/pom.xml
Labels: Build, dependencies

#10772 Fixes #10771 - EE10 ServletApi.isSecure() bug with ForwardedRequestCustomizer
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RequestTest.java
Labels: Bug, Specification

#10732 upgrade h2spec plugin to 1.0.11
  pom.xml
Labels: dependencies

#10753 Improve and test `jetty.sh` behaviors
  jetty-home/src/main/resources/bin/jetty.sh
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageFromDSL.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOS.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSAmazonCorretto11.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSUbuntuJammyJDK17.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageUserChange.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageUserRoot.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/JettyShStartTest.java
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/dir one/test1.xml
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/dir two/test2.xml
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/etc/jetty.conf
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/logs/.gitignore
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/modules/test.mod
  tests/test-distribution/src/test/resources/bases/spaces-with-conf/start.d/test.ini
  tests/test-distribution/src/test/resources/jetty-logging.properties
Labels: Bug

#10789 Fixing 429 Too Many Requests from w3.org
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ResourceListingTest.java
  pom.xml
Labels: Test, Build

#10790 Updates to jetty.sh and testing to reduce failures
  jetty-home/src/main/resources/bin/jetty.sh
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSAmazonCorretto17.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSUbuntuJammyJDK17.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageUserChange.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/JettyShStartTest.java
Labels: Test, Build

#10791 Updates to jetty.sh and testing to reduce failures
  jetty-home/src/main/resources/bin/jetty.sh
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSAmazonCorretto11.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageOSUbuntuJammyJDK17.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/ImageUserChange.java
Labels: Test, Build

#10796 Issue #10794 - fixing Moved Permanently handling of query strings
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ContextHandlerTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
Labels: Bug

#10800 Jetty 12.0.x - Dependency Updates
  jetty-core/jetty-http-spi/pom.xml
  jetty-ee10/pom.xml
  pom.xml
Labels: dependencies

#10807 Issue #10804 isRequestedSessionId should be false for invalid session
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/SessionHandlerTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/SessionHandlerTest.java
Labels: Bug

#10813 Fixes #10812 - Correct awaitility dependency scope
  jetty-deploy/pom.xml
Labels: dependencies
