Repository jetty/jetty.project, pull requests merged in 2023-09, with the labels that each got.

#10471 Upgrade testcontainers 1.19.0 (fix local issue with upgraded docker version)
  pom.xml
  tests/jetty-test-session-common/src/main/java/org/eclipse/jetty/session/test/tools/RemoteInfinispanTestSupport.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/session/HazelcastSessionDistributionTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/session/InfinispanSessionDistributionTests.java
Labels: Build

#10481 do not skip asciidoctor generation with eclipse-release profile
  pom.xml
Labels: Duplicate, Build

#10495 Switch to non deprecated classes of maven-resolver
  pom.xml
  tests/jetty-home-tester/pom.xml
  tests/jetty-home-tester/src/main/java/org/eclipse/jetty/tests/hometester/JettyHomeTester.java
Labels: Test, Build

#10480 Fixes #10361 - Introduce QoSHandler
  documentation/jetty-documentation/src/main/asciidoc/old_docs/extras/qos-filter.adoc
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/arch-threads.adoc
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/http/server-http-handler-use.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/LocalConnector.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/jmx/QoSHandlerMBean.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java
  jetty-ee10/jetty-ee10-servlets/src/main/java/org/eclipse/jetty/ee10/servlets/QoSFilter.java
  jetty-ee9/jetty-ee9-servlets/src/main/java/org/eclipse/jetty/ee9/servlets/QoSFilter.java
Labels: build-no-cache

#10464 Fixes #10219 - Review HTTP Cookie parsing
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpCookieTest.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/CookieCache.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookieStore.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265SetCookieParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/SetCookieParser.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieStoreTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpCookieUtils.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ResponseTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ServerHttpCookieTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/SessionHandlerTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
Labels: build-no-cache

#10510 Issue #10508 - honor Servlet spec behaviors for null in addHeader / setHeader calls
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResponseHeadersTest.java
Labels: Bug, Specification

#10514 Updating 9.4.52 entries in VERSION.txt
  VERSION.txt
Labels: Build

#10515 Updating 10.x entries in VERSION.txt
  VERSION.txt
Labels: Build

#10518 Updating jetty-10.0.x VERSION.txt from changes in jetty-9.4.x
  VERSION.txt
Labels: Build

#10516 Updating 11.x entries in VERSION.txt
  VERSION.txt
Labels: Build

#10517 Updating 12.x entries in VERSION.txt
  VERSION.txt
Labels: Build

#10522 Fixing CVE number for CGI servlet deprecation (11.0.x)
  VERSION.txt
Labels: Build

#10521 Fixing CVE number for CGI servlet deprecation (10.0.x)
  VERSION.txt
Labels: Build

#10512 upgrade to bouncycastle 1.76
  jetty-keystore/pom.xml
  jetty-keystore/src/main/config/modules/test-keystore.mod
Labels: dependencies

#10520 Fixing CVE number for CGI servlet deprecation (9.4.x)
  VERSION.txt
Labels: Build

#10523 Fixing CVE number for CGI servlet deprecation & removal (12.0.x)
  VERSION.txt
Labels: Build

#10365 Cleanup of start properties usages in `jetty-10.0.x`
  demos/demo-jndi-webapp/src/main/config/modules/demo.d/demo-jndi.xml
  jetty-deploy/src/main/config/modules/deploy.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-embedded.mod
  jetty-hazelcast/src/main/config/modules/session-store-hazelcast-remote.mod
  jetty-server/src/main/config/etc/jetty-debug.xml
  jetty-server/src/main/config/etc/jetty-http.xml
  jetty-server/src/main/config/etc/jetty-ssl.xml
  jetty-server/src/main/config/modules/debug.mod
  jetty-server/src/main/config/modules/gzip.mod
  jetty-server/src/main/config/modules/server.mod
Labels: Bug

#10503 Issue #10500 - preserve request header quoting when accessed through `JettyHttpExchangeDelegate`
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java
  jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/SPIServerTest.java
Labels: Bug

#10507 jetty 12.0.x upgrade dependencies
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/pom.xml
  pom.xml
Labels: Build, dependencies

#10544 Fix checkstyle after 11.0.x merge
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/security/ConstraintTest.java
Labels: Bug

#10545 Backport #10540 to `jetty-10.0.x` Fixed deadlock in class initialization.
  jetty-http/src/main/java/org/eclipse/jetty/http/EmptyHttpFields.java
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
Labels: Bug

#10551 Jetty 9.4.x - Fixing javadoc proxy test failures
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DemoBaseTests.java
  tests/test-webapps/test-proxy-webapp/src/main/webapp/WEB-INF/web.xml
  tests/test-webapps/test-proxy-webapp/src/test/java/org/eclipse/jetty/ProxyWebAppTest.java
Labels: Build

#10528 Fix NPE in HttpChannelState
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Labels: Bug

#10546 backport the jetty-http Huffman encoders/decoders from 10.0.x
  jetty-http/src/main/java/org/eclipse/jetty/http/HttpTokens.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/EncodingException.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/Huffman.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/HuffmanDecoder.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/HuffmanEncoder.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/NBitIntegerDecoder.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/NBitIntegerEncoder.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/NBitStringDecoder.java
  jetty-http/src/main/java/org/eclipse/jetty/http/compression/NBitStringEncoder.java
  jetty-http/src/test/java/org/eclipse/jetty/http/HuffmanTest.java
  jetty-http/src/test/java/org/eclipse/jetty/http/NBitIntegerTest.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackContext.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackException.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackFieldPreEncoder.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/MetaDataBuilder.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/NBitInteger.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackContextTest.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackDecoderTest.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackTest.java
  jetty-http2/http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HuffmanTest.java
  jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java
  jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
Labels: Enhancement, Sponsored

#10533 Issue #10328 - Review ResourceFactory.newSystemResource
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/ssl/X509Test.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ExampleServerXml.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/FileServerXml.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/OneWebAppWithJsp.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/SecuredHelloHandler.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/ServerWithAnnotations.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebXmlConfiguration.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/ExampleServerXml.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/FileServerXml.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/OneWebAppWithJsp.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/SecuredHelloHandler.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/ServerWithAnnotations.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebXmlConfiguration.java
Labels: Enhancement

#10494 Issue #10490 - fixes and testing for websocket JakartaServerUpgradeRequest
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/internal/DeferredAuthenticationState.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaServerUpgradeRequest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/ServerUpgradeRequestTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/internal/DelegatedServerUpgradeRequest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/ServerUpgradeRequestTest.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaServerUpgradeRequest.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/ServerUpgradeRequestTest.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/ServerUpgradeRequestTest.java
Labels: Bug

#10556 Issue #10463 Fix lastModified header when using HttpServletResponseWrapper
  jetty-ee8/jetty-ee8-servlet/src/test/resources/contextResources/test.txt
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ResponseHeadersTest.java
Labels: Bug, Jetty 12

#10492 ConditionalHandler
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpecSet.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/BufferedResponseHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ConditionalHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessSet.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/BufferedResponseHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ConditionalHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/InetAccessHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/InetAddressPattern.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
Labels: Enhancement

#10565 Upgrade gcloud sdk emulator to last 447.0.0-emulators
  tests/jetty-test-session-common/src/main/java/org/eclipse/jetty/session/test/tools/GCloudSessionTestSupport.java
Labels: Test, Build

#10553 Reintroduce an Exception type for invalid UTF-8
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8LineParser.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/Utf8StringBuilderTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/CloseStatus.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/exception/BadPayloadException.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/MessageHandler.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/PartialStringMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/StringMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/util/PartialStringMessageSinkTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/HttpWriterTest.java
Labels: Enhancement, Sponsored

#10548 Issue #10547 - Allow Executor of WebSocketClient to be customized via HttpClient
  jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
  jetty-websocket/websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/WebSocketClientTest.java
Labels: Bug, Sponsored

#10570 Upgrade quiche to version 0.18.0
  jetty-quic/quic-quiche/quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/Quiche.java
  jetty-quic/quic-quiche/quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/int64_t.java
  pom.xml
Labels: Enhancement

#10424 Issue #10421 fix jpms warning
  jetty-core/jetty-deploy/pom.xml
  jetty-ee10/jetty-ee10-servlet/pom.xml
  jetty-ee10/jetty-ee10-servlets/pom.xml
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-client-webapp/src/main/config/modules/ee10-websocket-jetty-client-webapp.mod
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/config/modules/ee10-websocket-jetty.mod
  jetty-ee8/jetty-ee8-servlets/pom.xml
  jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-javax-server/pom.xml
  jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-javax-server/src/main/config/modules/ee8-websocket-javax.mod
  jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-jetty-client-webapp/src/main/config/modules/ee8-websocket-jetty-client-webapp.mod
  jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-jetty-client/src/main/config/modules/ee8-websocket-jetty-client.mod
  jetty-ee8/jetty-ee8-websocket/jetty-ee8-websocket-jetty-server/src/main/config/modules/ee8-websocket-jetty.mod
  jetty-ee9/jetty-ee9-servlets/pom.xml
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-client-webapp/src/main/config/modules/ee9-websocket-jetty-client-webapp.mod
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/config/modules/ee9-websocket-jetty.mod
Labels: Build

#10566 Disable flaky leaky tests
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTimeoutTest.java
Labels: Bug, Test

#10577 Upgrade jetty setuid
  jetty-home/pom.xml
Labels: Bug

#10483 Improve BufferedResponseHandler
  jetty-core/jetty-io/pom.xml
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferAggregator.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/BufferedContentSink.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/BufferedContentSinkTest.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ByteBufferAggregatorTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/BufferedResponseHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/BufferedResponseHandlerTest.java
Labels: Enhancement

#10550 Make `ScheduledExecutorScheduler` more customizable
  jetty-util/src/main/java/org/eclipse/jetty/util/thread/ScheduledExecutorScheduler.java
Labels: Enhancement, Sponsored

#10501 Issue #10473 - Revert jetty.sh pgrep, and update started checks
  jetty-home/src/main/resources/bin/jetty.sh
  jetty-server/src/main/config/modules/state.mod
  jetty-server/src/main/java/org/eclipse/jetty/server/StateLifeCycleListener.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Bug

#10549 Issue #10449 - Improve javadoc and jetty-documentation packaging
  .mvn/maven-build-cache-config.xml
  documentation/jetty-documentation/pom.xml
  javadoc/pom.xml
  pom.xml
Labels: Documentation, Build

#10605 Issue #10473 - Better warnings in `jetty.sh` on filesystem permission issues
  jetty-home/src/main/resources/bin/jetty.sh
Labels: Enhancement

#10607 Issue #10606 - Bump build to JDK 21
  Jenkinsfile
  jetty-jaas/pom.xml
  jetty-jaas/src/test/java/org/eclipse/jetty/jaas/JAASLdapLoginServiceTest.java
  tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Build

#10618 Reduced mildly expensive HttpMethod.is calls by reordering boolean logic
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
Labels: Performance
