Repository jetty/jetty.project, pull requests merged in 2023-12, with the labels that each got.

#11011 [Jetty 10] Dependency Rollup - Dec 2023
  build-resources/pom.xml
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-p2/pom.xml
  pom.xml
Labels: dependencies

#11013 [9.4.x] Dependency Rollup - December 2023
  jetty-osgi/test-jetty-osgi/pom.xml
  jetty-spring/pom.xml
  pom.xml
Labels: dependencies

#10951 Upgrade to Maven build cache extension 1.1.0
  pom.xml
Labels: Build, dependencies

#10864 Jetty 12.0.x use coverage report rather than the non anymore maintained jacoco plugin
  Jenkinsfile
  pom.xml
Labels: build-no-cache

#10948 Fixes #10277 - Review read failures impacting writes.
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/http/server-http-handler-implement.adoc
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ReadWriteFailuresTest.java
Labels: build-no-cache

#11028 Jetty 12.0.x 10856 jndi doco
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/jndi/chapter.adoc
Labels: Documentation

#11027 Issue #10334 - Cleanup Module + XML properties usage
  jetty-core/jetty-server/src/main/config/modules/bytebufferpool-quadratic.mod
  jetty-core/jetty-server/src/main/config/modules/bytebufferpool.mod
  jetty-core/jetty-server/src/main/config/modules/graceful.mod
  jetty-core/jetty-server/src/main/config/modules/gzip.mod
  jetty-core/jetty-server/src/main/config/modules/session-store-jdbc.mod
  jetty-ee10/jetty-ee10-webapp/src/main/config/etc/jetty-ee10-deploy.xml
  jetty-ee10/jetty-ee10-webapp/src/main/config/modules/ee10-deploy.mod
  jetty-ee8/jetty-ee8-openid/src/main/config/etc/jetty-ee8-openid.xml
  jetty-ee8/jetty-ee8-openid/src/main/config/modules/ee8-openid.mod
  jetty-ee8/jetty-ee8-webapp/src/main/config/etc/jetty-ee8-deploy.xml
  jetty-ee8/jetty-ee8-webapp/src/main/config/modules/ee8-deploy.mod
  jetty-ee9/jetty-ee9-openid/src/main/config/etc/jetty-ee9-openid.xml
  jetty-ee9/jetty-ee9-openid/src/main/config/modules/ee9-openid.mod
  jetty-ee9/jetty-ee9-webapp/src/main/config/etc/jetty-ee9-deploy.xml
  jetty-ee9/jetty-ee9-webapp/src/main/config/modules/ee9-deploy.mod
Labels: Bug

#10957 Issue #10956 - Reviewed Expect 100 Continue Handler
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
Labels: save-home

#11042 Issue #11039 duplicate durable listeners on maven restart
  jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyEmbedder.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/SomeListener.java
  jetty-maven-plugin/src/test/java/org/eclipse/jetty/maven/plugin/TestJettyEmbedder.java
  jetty-maven-plugin/src/test/resources/embedder-context.xml
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletHandlerTest.java
Labels: Bug

#11048 Issue #11043 Update to Apache Jasper 9.0.83
  pom.xml
Labels: Task

#11049 Issue #11044 update to Apache Jasper 10.0.27
  pom.xml
Labels: Task

#11030 Refactor eeX plus.security and plus.annotation classes to core
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/annotations/chapter.adoc
  jetty-core/jetty-plus/pom.xml
  jetty-core/jetty-plus/src/main/java/module-info.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/Injection.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/InjectionCollection.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/LifeCycleCallback.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/LifeCycleCallbackCollection.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/PostConstructCallback.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/PreDestroyCallback.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/package-info.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/security/DataSourceLoginService.java
  jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/security/package-info.java
  jetty-ee10/jetty-ee10-annotations/pom.xml
  jetty-ee10/jetty-ee10-annotations/src/main/java/org/eclipse/jetty/ee10/annotations/PostConstructAnnotationHandler.java
  jetty-ee10/jetty-ee10-annotations/src/main/java/org/eclipse/jetty/ee10/annotations/PreDestroyAnnotationHandler.java
  jetty-ee10/jetty-ee10-annotations/src/main/java/org/eclipse/jetty/ee10/annotations/ResourceAnnotationHandler.java
  jetty-ee10/jetty-ee10-annotations/src/test/java/org/eclipse/jetty/ee10/annotations/TestAnnotationDecorator.java
  jetty-ee10/jetty-ee10-annotations/src/test/java/org/eclipse/jetty/ee10/annotations/resources/TestResourceAnnotations.java
  jetty-ee10/jetty-ee10-plus/pom.xml
  jetty-ee10/jetty-ee10-plus/src/main/java/module-info.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/annotation/Injection.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/annotation/InjectionCollection.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/annotation/LifeCycleCallbackCollection.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/annotation/RunAs.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/annotation/RunAsCollection.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/security/package-info.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/webapp/PlusConfiguration.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/webapp/PlusDecorator.java
  jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/webapp/PlusDescriptorProcessor.java
  jetty-ee10/jetty-ee10-plus/src/test/java/org/eclipse/jetty/ee10/plus/annotation/LifeCycleCallbackCollectionTest.java
  jetty-ee10/jetty-ee10-plus/src/test/java/org/eclipse/jetty/ee10/plus/webapp/PlusDescriptorProcessorTest.java
  jetty-ee10/jetty-ee10-quickstart/src/main/java/org/eclipse/jetty/ee10/quickstart/QuickStartGeneratorConfiguration.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-loginservice/src/test/java/org/eclipse/jetty/ee10/loginservice/DataSourceLoginServiceTest.java
  jetty-ee8/jetty-ee8-annotations/pom.xml
  jetty-ee8/jetty-ee8-plus/pom.xml
  jetty-ee9/jetty-ee9-annotations/pom.xml
  jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/PostConstructAnnotationHandler.java
  jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/PreDestroyAnnotationHandler.java
  jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/ResourceAnnotationHandler.java
  jetty-ee9/jetty-ee9-annotations/src/test/java/org/eclipse/jetty/ee9/annotations/TestAnnotationDecorator.java
  jetty-ee9/jetty-ee9-annotations/src/test/java/org/eclipse/jetty/ee9/annotations/resources/TestResourceAnnotations.java
  jetty-ee9/jetty-ee9-plus/pom.xml
  jetty-ee9/jetty-ee9-plus/src/main/java/module-info.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/annotation/LifeCycleCallback.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/annotation/PostConstructCallback.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/annotation/PreDestroyCallback.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/annotation/RunAs.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/annotation/RunAsCollection.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/security/DataSourceLoginService.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/security/package-info.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/webapp/PlusConfiguration.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/webapp/PlusDecorator.java
  jetty-ee9/jetty-ee9-plus/src/main/java/org/eclipse/jetty/ee9/plus/webapp/PlusDescriptorProcessor.java
  jetty-ee9/jetty-ee9-plus/src/test/java/org/eclipse/jetty/ee9/plus/annotation/LifeCycleCallbackCollectionTest.java
  jetty-ee9/jetty-ee9-plus/src/test/java/org/eclipse/jetty/ee9/plus/webapp/PlusDescriptorProcessorTest.java
  jetty-ee9/jetty-ee9-quickstart/src/main/java/org/eclipse/jetty/ee9/quickstart/QuickStartGeneratorConfiguration.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-loginservice/src/test/java/org/eclipse/jetty/ee9/loginservice/DataSourceLoginServiceTest.java
Labels: build-no-cache

#11033 Fixes #11031 - HttpClient should expose Connection/EndPoint used by H…
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpChannel.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java
  jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
  jetty-client/src/main/java/org/eclipse/jetty/client/api/Connection.java
  jetty-client/src/main/java/org/eclipse/jetty/client/api/Request.java
  jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpChannelOverHTTP.java
  jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpConnectionOverHTTP.java
  jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientFailureTest.java
  jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpChannelOverFCGI.java
  jetty-fcgi/fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/http/HttpConnectionOverFCGI.java
  jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpChannelOverHTTP2.java
  jetty-http2/http2-http-client-transport/src/main/java/org/eclipse/jetty/http2/client/http/HttpConnectionOverHTTP2.java
  jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpChannelOverHTTP3.java
  jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpConnectionOverHTTP3.java
  tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTest.java
Labels: Sponsored

#11052 Issue #11046 Update EE9 to Apache Jasper 10.0.27
  jetty-ee9/pom.xml
Labels: Task

#11050 Issue #11045 update Apache Jasper 10.1.16
  jetty-ee10/pom.xml
Labels: Task

#11053 Issue #11047 Update EE8 to Apache Jasper 9.0.83.1
  jetty-ee8/pom.xml
Labels: Task

#11036 Improve the dump output of ConcurrentPool
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ConcurrentPool.java
Labels: Enhancement

#11065 Fixes #11064 - Jetty 12: NPE if MultiPartFormData.setFilesDirectory()…
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormDataTest.java
Labels: Sponsored, build-no-cache

#11057 Issue #11040 - Deprecate PathResource.SUPPORTED_SCHEMES
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
Labels: Enhancement

#11059 Update to cdi-api 3.0.1
  pom.xml
Labels: Task

#11067 Fixes #11066 - URIUtilTest.testFileUriGetUriLastPathSegment on macOS
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
Labels: Test

#11038 Fixes #11037 - Serialize HttpClient request failures
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HTTPSessionListenerPromise.java
  jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/SessionClientListener.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/IteratingCallbackTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/DemandingFlusher.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/TransformingFlusher.java
Labels: build-no-cache

#11017 Fixes #11016 - Jetty 12 IllegalStateException when stopping Server wi…
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncServletLongPollTest.java
  jetty-ee8/jetty-ee8-servlet/pom.xml
  jetty-ee9/jetty-ee9-servlet/pom.xml
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/AsyncServletLongPollTest.java
Labels: build-no-cache

#11051 Do not use HttpStream.Wrapper in SizeLimitHandler
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/http/server-http-handler-use.adoc
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SizeLimitHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/SizeLimitHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/SizeLimitHandlerServletTest.java
Labels: Sponsored

#11070 Add Testcase for ee8/ee9 nested HandlerCollection
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/HandlerCollectionTest.java
Labels: Test

#11069 Implemented server-side reset of the stream using error code NO_ERROR in case the request content is not read.
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/AsyncContentProducer.java
Labels: build-no-cache

#11084 Issue #11081 - fix race condition in WebSocket FrameHandlers
  jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java
  jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
Labels: Bug
