Repository jetty/jetty.project, pull requests merged in 2024-01, with the labels that each got.

#11205 Dependency Rollup - Jan 2024 - [`jetty-10.0.x`]
  .github/dependabot.yml
  build-resources/pom.xml
  jetty-gcloud/pom.xml
  jetty-osgi/pom.xml
  pom.xml
  tests/test-integration/src/test/java/org/eclipse/jetty/test/jsp/JspAndDefaultWithAliasesTest.java
Labels: dependencies

#11209 Dependency Rollup - Jan 2024 - [`jetty-9.4.x`]
  jetty-bom/pom.xml
  jetty-documentation/pom.xml
  jetty-http-spi/pom.xml
  jetty-jaspi/pom.xml
  jetty-osgi/pom.xml
  pom.xml
  tests/test-integration/src/test/java/org/eclipse/jetty/test/jsp/JspAndDefaultWithAliasesTest.java
Labels: dependencies

#11212 Cleaning up top level dependencies
  pom.xml
Labels: Build, dependencies

#11215 Fix Build on Windows
  .mvn/maven-build-cache-config.xml
  pom.xml
Labels: Microsoft Windows, Build

#11257 Dependency Rollup / 2024 Jan 8 / jetty-9.4.x
  jetty-gcloud/pom.xml
  pom.xml
Labels: dependencies

#11093 Fixes #10220 - Implement CrossOriginHandler.
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-cross-origin.adoc
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules-standard.adoc
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/http/server-http-handler-use.adoc
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/server/websocket/server-websocket-filter.adoc
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpHeader.java
  jetty-core/jetty-server/src/main/config/etc/jetty-cross-origin.xml
  jetty-core/jetty-server/src/main/config/modules/cross-origin.mod
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/CrossOriginHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/CrossOriginHandlerTest.java
  jetty-ee10/jetty-ee10-servlets/src/main/java/org/eclipse/jetty/ee10/servlets/CrossOriginFilter.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Enhancement, Sponsored

#11262 Correct some javadoc typos
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/MultiPartRequestContent.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/OutputStreamRequestContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/CookieParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java
Labels: Documentation

#11269 Issue #11259 - HTTP/2 connection not closed after idle timeout when TCP congested.
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/IdleTimeoutTest.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-http3/http3-common/src/main/java/org/eclipse/jetty/http3/internal/HTTP3Session.java
  jetty-quic/quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java
Labels: Bug

#11267 Fixes #11259 - HTTP/2 connection not closed after idle timeout when TCP congested.
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/IdleTimeoutTest.java
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java
  jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/IdleTimeoutTest.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/IdleTimeoutTest.java
Labels: Bug

#11268 Issue #11259 - HTTP/2 connection not closed after idle timeout when TCP congested.
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/IdleTimeoutTest.java
  jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
Labels: Bug

#11276 Issue #11273 - Add support for BSD based `expr` utility in `jetty.sh`
  jetty-home/src/main/resources/bin/jetty.sh
Labels: Enhancement

#11264 Issue #11263 - Reduce usage of glob lib/foo/*.jar in modules
  jetty-core/jetty-http2/jetty-http2-server/src/main/config/modules/http2.mod
  jetty-core/jetty-http2/jetty-http2-server/src/main/config/modules/http2c.mod
  jetty-core/jetty-http3/jetty-http3-server/src/main/config/modules/http3.mod
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-unixdomain-server/src/main/config/modules/unixdomain-http.mod
  jetty-ee10/jetty-ee10-annotations/src/main/config/modules/ee10-annotations.mod
  jetty-ee10/jetty-ee10-apache-jsp/src/main/config/modules/ee10-apache-jsp.mod
  jetty-ee10/jetty-ee10-glassfish-jstl/src/main/config/modules/ee10-glassfish-jstl.mod
  jetty-ee10/jetty-ee10-jaspi/src/main/config/modules/ee10-jaspi.mod
  jetty-ee10/jetty-ee10-maven-plugin/src/main/resources/ee10-maven.mod
  jetty-ee8/jetty-ee8-annotations/src/main/config/modules/ee8-annotations.mod
  jetty-ee8/jetty-ee8-apache-jsp/src/main/config/modules/ee8-apache-jsp.mod
  jetty-ee8/jetty-ee8-glassfish-jstl/src/main/config/modules/ee8-glassfish-jstl.mod
  jetty-ee8/jetty-ee8-jaspi/src/main/config/modules/ee8-jaspi-default-auth-config-factory.mod
  jetty-ee8/jetty-ee8-jaspi/src/main/config/modules/ee8-jaspi-demo.mod
  jetty-ee8/jetty-ee8-jaspi/src/main/config/modules/ee8-jaspi.mod
  jetty-ee8/pom.xml
  jetty-ee9/jetty-ee9-annotations/src/main/config/modules/ee9-annotations.mod
  jetty-ee9/jetty-ee9-apache-jsp/src/main/config/modules/ee9-apache-jsp.mod
  jetty-ee9/jetty-ee9-glassfish-jstl/src/main/config/modules/ee9-glassfish-jstl.mod
  jetty-ee9/jetty-ee9-jaspi/src/main/config/modules/ee9-jaspi.mod
  jetty-home/src/main/resources/modules/conscrypt.mod
  jetty-integrations/jetty-memcached/jetty-memcached-sessions/src/main/config/modules/sessions/session-data-cache/xmemcached.mod
  jetty-integrations/jetty-nosql/src/main/config/modules/session-store-mongo.mod
  pom.xml
Labels: Enhancement, Sponsored, dependencies

#11304 Fix incorrect reliance on autoDemand when handlers are not configured
  jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/pom.xml
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/FrameListenerTest.java
Labels: Bug, Sponsored

#11300 Restore DefaultServlet.doPost to the previous major releases' behavior
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
Labels: Bug, Sponsored

#11293 Issue #11292 - Missing Date Response Header.
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RequestTest.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Bug

#11318 Issue #11220 - ContextHandler NPE protections
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/LoggerDebugTest.java
Labels: Bug

#11313 Issue #11281 - fix two NPEs seen during MultiPart with DEBUG enabled
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java
Labels: Bug

#11314 Issue #11312 - fix deprecated init-param detection in DefaultServlet
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
Labels: Bug

#11261 Issue #11260 - Allow `QuickStartConfiguration` to be used in mixed contexts environment where some do not have a WEB-INF/quickstart-web.xml
  jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java
  tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/PreconfigureSpecWar.java
  tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/QuickStartTest.java
  tests/test-quickstart/src/test/webapps/no-web-xml/index.html
Labels: Bug, Sponsored

#11321 Issue #11317 - Low hanging fix for LOG.debug in addBean.
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java
Labels: Bug

#11288 Fixes for Spring core integration
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MutableHttpFields.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorClientTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSinkSubscriber.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteBufferChunk.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/EchoHandler.java
Labels: Enhancement, Third Party

#11210 Fixes #11095 - IllegalStateException for completed requests with GzipHandler
  jetty-core/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/gzip/GzipHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/GzipHandlerTest.java
  jetty-ee10/jetty-ee10-servlets/src/test/java/org/eclipse/jetty/ee10/servlets/GzipDefaultServletDeferredContentTypeTest.java
  jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/GzipDefaultServletDeferredContentTypeTest.java
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/JettyHomeTester.java
Labels: build-no-cache, build-all-tests

#11341 Issue #11329 - fix artifactIds in Jetty 12 migration guide
  documentation/jetty-documentation/src/main/asciidoc/programming-guide/migration/migration-11-to-12.adoc
Labels: Documentation

#11351 Update to quiche version 0.20.0
  jetty-quic/quic-quiche/quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#11352 Jetty 12: Update to quiche version 0.20.0
  build/scripts/release-jetty.sh
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java
  pom.xml
Labels: Enhancement
