Repository jetty/jetty.project, pull requests merged in 2024-06, with the labels that each got.

#11878 Add response to debug log event in HttpSender#failRequest()
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
Labels: Enhancement

#11896 Issue #11893 fix maven helloworld example
  documentation/jetty/modules/programming-guide/pages/maven-jetty/jetty-maven-helloworld.adoc
Labels: Documentation

#11913 Issue #11909 - duplicate --modules=<name> can trigger ConcurrentModificationException
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java
  jetty-core/jetty-start/src/test/resources/dist-home/start.ini
  jetty-core/jetty-start/src/test/resources/overdeclared-modules/resources/jetty-logging.properties
  jetty-core/jetty-start/src/test/resources/overdeclared-modules/start.d/config.ini
Labels: Bug

#11849 Simplified Reactive Stream update for ContentSourcePublisher
  Jenkinsfile
  jetty-core/jetty-io/pom.xml
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/content/ContentSourcePublisherTest.java
  pom.xml
Labels: High Priority

#11916 Issue #11911 Fix documentation example for Request.getHttpUri
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java
Labels: Documentation

#11897 Fix missing notifyRemoteAsyncErrors http config wiring
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnectionFactory.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AbstractTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AsyncIOTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AsyncServletTest.java
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicStreamEndPoint.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/ForeignQuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/Http2AsyncIOServletTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/Http3AsyncIOServletTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/java/org/eclipse/jetty/ee9/test/client/transport/Http2AsyncIOServletTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/src/test/java/org/eclipse/jetty/ee9/test/client/transport/Http3AsyncIOServletTest.java
Labels: Bug, Sponsored

#11927 Cleanup ee9 DefaultServletTest
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
Labels: Test

#11886 Initial work for Cross Context Dispatch testing suite
  tests/pom.xml
  tests/test-cross-context-dispatch/ccd-common/pom.xml
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/DispatchPlan.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/DispatchPlanHandler.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/DispatchType.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/HttpRequest.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/PlanSessionCache.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/Property.java
  tests/test-cross-context-dispatch/ccd-common/src/main/java/org/eclipse/jetty/tests/ccd/common/Step.java
  tests/test-cross-context-dispatch/ccd-common/src/test/java/org/eclipse/jetty/tests/ccd/common/DispatchPlanLoadTest.java
  tests/test-cross-context-dispatch/ccd-common/src/test/resources/forward-include-dump.txt
  tests/test-cross-context-dispatch/ccd-ee10-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee10-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee10/CCDServlet.java
  tests/test-cross-context-dispatch/ccd-ee10-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee10/DumpServlet.java
  tests/test-cross-context-dispatch/ccd-ee10-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee10/ForwardServlet.java
  tests/test-cross-context-dispatch/ccd-ee10-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee10/InternalRequestURIFilter.java
  tests/test-cross-context-dispatch/ccd-ee10-webapp/src/main/webapp/WEB-INF/web.xml
  tests/test-cross-context-dispatch/ccd-ee8-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee8-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee8/CCDServlet.java
  tests/test-cross-context-dispatch/ccd-ee8-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee8/DumpServlet.java
  tests/test-cross-context-dispatch/ccd-ee8-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee8/ForwardServlet.java
  tests/test-cross-context-dispatch/ccd-ee8-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee8/InternalRequestURIFilter.java
  tests/test-cross-context-dispatch/ccd-ee8-webapp/src/main/webapp/WEB-INF/web.xml
  tests/test-cross-context-dispatch/ccd-ee9-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee9-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee9/CCDServlet.java
  tests/test-cross-context-dispatch/ccd-ee9-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee9/DumpServlet.java
  tests/test-cross-context-dispatch/ccd-ee9-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee9/ForwardServlet.java
  tests/test-cross-context-dispatch/ccd-ee9-webapp/src/main/java/org/eclipse/jetty/tests/ccd/ee9/InternalRequestURIFilter.java
  tests/test-cross-context-dispatch/ccd-ee9-webapp/src/main/webapp/WEB-INF/web.xml
  tests/test-cross-context-dispatch/ccd-tests/pom.xml
  tests/test-cross-context-dispatch/ccd-tests/src/test/java/org/eclipse/jetty/tests/redispatch/AbstractRedispatchTest.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/java/org/eclipse/jetty/tests/redispatch/RedispatchPlansTests.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/java/org/eclipse/jetty/tests/redispatch/RedispatchTests.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/java/org/eclipse/jetty/tests/redispatch/ResponseDetails.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/error-handler.xml
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/install-ccd-handler.xml
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/context-ee10-forward-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/context-ee8-forward-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/context-ee8-include-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-forward-to-ee8-include-ee9-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-request-forward-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-request-include-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-session-ee8-ee9-ee8.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-session-forward-to-ee8-session-include-ee9-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee8-request-forward-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee8-request-include-dump.txt
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/webapp-xmls/ccd-ee10.xml
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/webapp-xmls/ccd-ee8.xml
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/webapp-xmls/ccd-ee9.xml
  tests/test-cross-context-dispatch/pom.xml
Labels: Test

#11888 Jetty 12.0.x object identity ee8 and ee9
  jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/AbstractSessionManager.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/CreationTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/CrossContextDispatcher.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/SessionHandler.java
  jetty-ee9/jetty-ee9-security/src/main/java/org/eclipse/jetty/ee9/security/SecurityHandler.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/CrossContextDispatcherTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/CreationTest.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/java/org/eclipse/jetty/tests/redispatch/RedispatchPlansTests.java
  tests/test-cross-context-dispatch/ccd-tests/src/test/resources/plans/ee10-session-ee8-ee9-ee8.txt
Labels: save-home

#11940 Fix warnings during jetty-ee9-servlet tests
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/CacheControlHeaderTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletRangesTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ServletRequestLogTest.java
Labels: Test

#11936 Servlet 61 cookie fixes
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/CookieCompliance.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionMetaData.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpCookieUtils.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpCookieTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ServerHttpCookieTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ContextScopeListenerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletRequestListenerTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/PushedResourcesTest.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ContextScopeListenerTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ServletRequestListenerTest.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-client-transports/src/test/java/org/eclipse/jetty/ee11/test/client/transport/PushedResourcesTest.java
Labels: Specification, TCK

#11910 ByteChannelContentSource
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/PathRequestContent.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/util/MultiPartRequestContentTest.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteChannelContentSource.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/PathContentSource.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentCopier.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ContentSourceTest.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/internal/ContentCopierTest.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java
Labels: High Priority

#11930 Issue #11925 - Fix Etag NPE when using URLResource and improve Base Resource is alias warning
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/EtagUtils.java
  jetty-core/jetty-maven/src/main/java/org/eclipse/jetty/maven/MavenResource.java
  jetty-core/jetty-maven/src/main/java/org/eclipse/jetty/maven/SelectiveJarResource.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/MemoryResource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/URLResourceFactory.java
  jetty-ee8/jetty-ee8-servlet/pom.xml
  jetty-ee9/jetty-ee9-servlet/pom.xml
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DispatcherTest.java
Labels: Bug

#11961 Upgrade Infinispan 15.0.5
  VERSION.txt
  pom.xml
Labels: dependencies

#11963 Issue #11962 - Cleanup XML environment specific deployment AppProviders
  VERSION.txt
  jetty-core/jetty-deploy/src/main/config/etc/jetty-core-deploy.xml
  jetty-ee10/jetty-ee10-quickstart/src/main/config/etc/jetty-ee10-quickstart.xml
  jetty-ee10/jetty-ee10-webapp/src/main/config/etc/jetty-ee10-deploy.xml
  jetty-ee8/jetty-ee8-quickstart/src/main/config/etc/jetty-ee8-quickstart.xml
  jetty-ee8/jetty-ee8-webapp/src/main/config/etc/jetty-ee8-deploy.xml
  jetty-ee9/jetty-ee9-quickstart/src/main/config/etc/jetty-ee9-quickstart.xml
  jetty-ee9/jetty-ee9-webapp/src/main/config/etc/jetty-ee9-deploy.xml
Labels: Bug, Sponsored

#11967 Fix flaky ContextScopeListenerTest
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ContextScopeListenerTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ContextScopeListenerTest.java
Labels: Test, flaky-test

#11951 Remove buffer from pool on write failure
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java
Labels: Sponsored
