Repository jetty/jetty.project, pull requests merged in 2024-11, with the labels that each got.

#12470 Change ee9 to ee10 in jetty-logging.properties
  jetty-ee10/jetty-ee10-servlets/src/test/resources/jetty-logging.properties
Labels: Build

#12497 Issue #12495 Restore ErrorPageTest
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ErrorPageTest.java
Labels: Test

#12449 Issue #12324 - support Accept-Encoding: * on CompressionHandler
  jetty-core/jetty-compression/jetty-compression-server/pom.xml
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/CompressionConfig.java
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/CompressionHandler.java
  jetty-core/jetty-compression/jetty-compression-server/src/test/java/org/eclipse/jetty/compression/server/CompressionConfigTest.java
  jetty-core/jetty-compression/jetty-compression-tests/src/test/java/org/eclipse/jetty/compression/CompressionHandlerTest.java
Labels: Enhancement

#12536 Fix `HTTP2Test.testLargeRequestHeaders`
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
Labels: Bug

#12557 Fixes #12553 - Execute immediately HTTP/2 failures.
  jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/IdleTimeoutTest.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/HTTP3ServerConnectionFactory.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadPool.java
Labels: Sponsored

#12567 Issue #12446 upgrade some github actions
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: Build

#12545 Fix `IllegalStateException` in `HttpChannelState.completed()` after `abort()`
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
Labels: Bug

#12582 Remove useless tooling which does not help at all for flaky tests (and such consume extra resources and disk for no help)
  Jenkinsfile
Labels: Build

#12571 Allow BadMessageException to propagate unwrapped through HttpInput
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/SizeLimitHandlerTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/HttpInputInterceptorTest.java
Labels: Enhancement, Sponsored

#12593 Create start.d/*.ini for [ini-template] modules
  documentation/jetty/modules/operations-guide/pages/begin/index.adoc
  documentation/jetty/modules/operations-guide/pages/modules/index.adoc
  documentation/jetty/modules/operations-guide/pages/protocols/index.adoc
  documentation/jetty/modules/operations-guide/pages/start/index.adoc
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/Modules.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/usecases/AbstractUseCase.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/usecases/TransientIniTemplateTest.java
Labels: Enhancement
