Repository jetty/jetty.project, pull requests merged in 2024-03, with the labels that each got.

#11486 Improve HTTP parsing long look-ahead
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpMethod.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  tests/jetty-jmh/src/main/java/org/eclipse/jetty/http/jmh/HttpParseBenchmark.java
Labels: Enhancement, Performance

#11487 Fix StatisticsHandler not receiving implicit status 200
  documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/server/http/HTTPServerDocs.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/LatencyRecordingHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/EventsHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/StatisticsHandlerTest.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/EventsHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletRequestLogTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
Labels: Bug

#11511 Issue #11510 - Prevent NPE in ClassMatcher.match()
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/ClassMatcher.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/ClassMatcher.java
Labels: Bug

#11520 Upgrade quiche to version 0.20.1
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/Quiche.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#11530 Fixing missing dep of testcontainers -> commons-compress -> commons-codec
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-jdbc/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-loginservice/pom.xml
Labels: dependencies

#11493 `Resource.copyTo()` throws `UnsupportedOperationException` for `PathResource` instances
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/MemoryResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
Labels: Bug

#11554 Fix #11553 restore startWebapp
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
Labels: High Priority, Sponsored

#11549 Fix ClosedFileSystemException on hot redeploy
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/FileSystemPool.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/FileSystemPoolTest.java
Labels: Bug, JVM Issue

#11518 Ensure request is set for ContextScopeListener in EE10
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextEvent.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextState.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ContextScopeListenerTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ContextScopeListenerTest.java
Labels: Sponsored

#11551 jetty-12.0.x jdk22 build
  Jenkinsfile
  pom.xml
Labels: Build

#11550 Issue #11548 - Replication as jetty-ee10-webapp testcase
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/resources/jetty-logging.properties
Labels: Bug, Test

#11576 Issue #11572 add check for isDeployable when hot deploy file changes
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ContextProvider.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/providers/ContextProviderRuntimeUpdatesTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/test/XmlConfiguredJetty.java
  jetty-core/jetty-deploy/src/test/resources/webapps/simple.xml
Labels: Bug

#11575 Issue #11574 war should not be extracted unless configured to do so
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppClassLoader.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebInfConfigurationTest.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppClassLoader.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebInfConfiguration.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/WebInfConfigurationTest.java
Labels: Bug

#11540 Issue #11539 restore old behavior of `Resource.copyTo()` with regards to existing destination files.
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/CombinedResource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/Overlay.java
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/Overlay.java
Labels: Enhancement, Sponsored

#11544 Issue #10387 configure doclint to not generate verbose useless warning, remove obsolete parameter
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/DateCache.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppClassLoader.java
  pom.xml
Labels: Build

#11585 Fixes to URIUtil for Windows
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/FileSystemPool.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
Labels: Microsoft Windows

#11571 remove unknown maven plugin parameter
  pom.xml
Labels: Build

#11590 Disable Conscrypt tests on aarch64
  jetty-core/jetty-alpn/jetty-alpn-conscrypt-client/src/test/java/org/eclipse/jetty/alpn/java/client/ConscryptHTTP2ClientTest.java
  jetty-core/jetty-alpn/jetty-alpn-conscrypt-server/src/test/java/org/eclipse/jetty/alpn/conscrypt/server/ConscryptHTTP2ServerTest.java
Labels: Test

#11591 Update Dependencies [12.0.x] - March 2024
  build/scripts/dependency-update.sh
  javadoc/pom.xml
  jetty-core/pom.xml
  jetty-ee10/jetty-ee10-annotations/pom.xml
  jetty-ee10/jetty-ee10-plus/pom.xml
  jetty-ee10/pom.xml
  jetty-ee8/jetty-ee8-osgi/jetty-ee8-osgi-boot/pom.xml
  jetty-ee8/pom.xml
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/pom.xml
  jetty-ee9/jetty-ee9-osgi/pom.xml
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestOSGiUtil.java
  jetty-ee9/pom.xml
  jetty-home/pom.xml
  jetty-integrations/jetty-infinispan/jetty-infinispan-remote-query/pom.xml
  pom.xml
  tests/jetty-testers/pom.xml
Labels: dependencies
