Repository jetty/jetty.project, pull requests merged in 2024-12, with the labels that each got.

#12591 Issue #12577 - Fixing NPE from HttpURI.getDecodedPath() if path doesn't exist
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpURITest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
Labels: Bug

#12602 Fix incorrect maven coordinates
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/pom.xml
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Bug, Test

#12589 jetty 12.0.x upgrade dependencies
  pom.xml
Labels: dependencies

#12579 restore abort for SendCallback.failed
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
Labels: Sponsored

#12611 Supporting Compression discovery with ServiceLoader.
  jetty-core/jetty-compression/jetty-compression-brotli/src/main/config/etc/jetty-compression-brotli.xml
  jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/module-info.java
  jetty-core/jetty-compression/jetty-compression-brotli/src/main/resources/META-INF/services/org.eclipse.jetty.compression.Compression
  jetty-core/jetty-compression/jetty-compression-gzip/src/main/config/etc/jetty-compression-gzip.xml
  jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/module-info.java
  jetty-core/jetty-compression/jetty-compression-gzip/src/main/resources/META-INF/services/org.eclipse.jetty.compression.Compression
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/module-info.java
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/CompressionHandler.java
  jetty-core/jetty-compression/jetty-compression-tests/src/test/java/org/eclipse/jetty/compression/CompressionHandlerTest.java
  jetty-core/jetty-compression/jetty-compression-zstandard/src/main/config/etc/jetty-compression-zstandard.xml
  jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/module-info.java
  jetty-core/jetty-compression/jetty-compression-zstandard/src/main/resources/META-INF/services/org.eclipse.jetty.compression.Compression
Labels: Enhancement

#12606 Fixed #12603 Errors logged after cross context dispatch
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletCoreResponse.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ServletCoreResponse.java
Labels: High Priority, Bug, Sponsored

#12610 Add H2 stress tests
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-http2-webapp/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-http2-webapp/src/test/java/org/eclipse/jetty/test/webapp/StressHTTP2Test.java
Labels: Enhancement, Test

#12648 Better handling of bad gzip content.
  Jenkinsfile
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java
  jetty-servlet/src/test/java/org/eclipse/jetty/servlet/GzipHandlerTest.java
Labels: Sponsored, save-home

#12633 Ensure a redirect of the HttpServletResponse will close HttpOutput
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/WriteAfterRedirectTest.java
Labels: Sponsored

#12656 Issue #12650 Fix multipart attribute for forwards.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java
Labels: Bug
