Repository jetty/jetty.project, pull requests merged in 2024-10, with the labels that each got.

#12328 Fix flaky assertions in `ConnectionPoolTest`
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java
Labels: flaky-test

#12340 Make sure the delegate callback has been failed before SendCallback's iteration returns
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
Labels: Bug

#12338 Issue #12326 Jetty 12.1.x Infinispan flaky tests
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/src/test/resources/config.yaml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-sessions/jetty-ee11-test-sessions-infinispan/src/test/resources/config.yaml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-infinispan/src/test/resources/config.yaml
  pom.xml
  tests/jetty-test-session-common/src/main/java/org/eclipse/jetty/session/test/tools/InfinispanTestSupport.java
  tests/jetty-test-session-common/src/main/java/org/eclipse/jetty/session/test/tools/RemoteInfinispanTestSupport.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/session/InfinispanSessionDistributionTests.java
  tests/test-distribution/test-distribution-common/src/test/resources/config.yaml
Labels: Build

#12364 Update commons-io to address CVE
  jetty-ee10/jetty-ee10-maven-plugin/src/it/it-parent-pom/pom.xml
  jetty-ee8/jetty-ee8-maven-plugin/src/it/it-parent-pom/pom.xml
  jetty-ee9/jetty-ee9-maven-plugin/src/it/it-parent-pom/pom.xml
  pom.xml
Labels: dependencies

#12365 Update apache avro to address CVE
  pom.xml
Labels: dependencies

#12375 Fix #12356 Do not send keep-alive when not persistent
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorServerTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/AbstractConnectHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ConnectHandlerSSLTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ConnectHandlerTest.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ConnectHandlerSSLTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/support/rawhttp/HttpRequestTesterTest.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/RequestTest.java
  jetty-ee9/jetty-ee9-proxy/src/test/java/org/eclipse/jetty/ee9/proxy/AbstractConnectHandlerTest.java
  jetty-ee9/jetty-ee9-proxy/src/test/java/org/eclipse/jetty/ee9/proxy/ConnectHandlerTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/java/org/eclipse/jetty/ee9/test/support/rawhttp/HttpRequestTesterTest.java
Labels: Bug

#12386 Issue #12385 Update ee10 jsp to Apache Jasper 10.1.31
  jetty-ee10/pom.xml
Labels: dependencies

#12388 Issue #12387 Update to Apache Jasper 9.0.96 for EE8
  jetty-ee8/pom.xml
Labels: dependencies

#12347 Use lowercase for charsets #11741
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/ContentResponseTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/util/TypedContentProviderTest.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MimeTypes.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
  jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/authentication/FormAuthenticator.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestBase.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/DefaultHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/CharacterEncodingTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResourceServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResponseHeadersTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/security/ConstraintTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/HttpInputTransientErrorTest.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/CharacterEncodingTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/DefaultServletTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResourceServletTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResponseHeadersTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResponseTest.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/java/org/eclipse/jetty/ee11/test/HttpInputTransientErrorTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ResponseHeadersTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/java/org/eclipse/jetty/ee9/test/HttpInputTransientErrorTest.java
Labels: build-no-cache

#12376 Jetty 12.0.x dependencies upgrade
  jetty-core/jetty-http-spi/pom.xml
  jetty-core/jetty-security/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee10/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-infinispan/pom.xml
  pom.xml
Labels: dependencies, eclipse-dash

#12345 12.0.x: Fix flaky assertions in `ConnectionPoolTest`
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java
Labels: flaky-test

#12400 jetty 12.1.x merge 12.0
  .github/ISSUE_TEMPLATE/release-template.md
  jetty-core/jetty-http-spi/pom.xml
  jetty-core/jetty-security/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-infinispan/pom.xml
  pom.xml
Labels: Build, dependencies

#12402 Issue #12396 enable back ResourceFactoryTest
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java
Labels: Test

#12322 Issue #9980 - add additional codes for CustomRequestLog
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
Labels: Enhancement

#12410 a few more versions upgrades
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-sessions/jetty-ee11-test-sessions-infinispan/pom.xml
  jetty-ee8/jetty-ee8-osgi/test-jetty-ee8-osgi/pom.xml
  pom.xml
Labels: dependencies

#12411 concurrency issue unzipping file, need to catch FileSystemAlreadyExistsException
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/JettyHomeTester.java
Labels: Test

#12319 Fixes #12318 SecurityUtils should not elminate calls to existing methods
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/security/SecurityUtils.java
Labels: Bug

#12415 Fix log message to contain correct exception class name
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/JettyHomeTester.java
Labels: Build

#12414 Issue #12397 - Add more default excludes to GzipHandler.
  jetty-core/jetty-http/src/main/resources/org/eclipse/jetty/http/mime.properties
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/gzip/GzipHandlerTest.java
Labels: Bug

#12407 Issue #12403 - verify XML PublicID behaviors.
  documentation/jetty/modules/operations-guide/pages/protocols/index.adoc
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java
  jetty-core/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
Labels: Bug

#12420 Issue #12396 - fix and re-enable NcsaRequestLogTest
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/NcsaRequestLogTest.java
Labels: Test

#12379 Fixes #12378 - Change default value for SslContextFactory.renegotiationAllowed to false.
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java
Labels: Sponsored

#12437 Fix download url in message
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
Labels: Documentation

#12424 Update DebugHandlerTest
  jetty-core/jetty-server/pom.xml
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/DebugHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/DebugHandlerTest.java
Labels: Build
