Repository jetty/jetty.project, pull requests merged in 2024-07, with the labels that each got.

#11997 Update deployment documentation for new features
  documentation/jetty/modules/operations-guide/pages/deploy/index.adoc
  documentation/jetty/modules/operations-guide/pages/jndi/index.adoc
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java
Labels: Documentation

#12011 Jetty 12.1.x tck error message
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ErrorHandler.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResponseTest.java
Labels: TCK

#11995 Upgrade quiche to version 0.22.0
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/ForeignQuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#11999 Fix broken client tls negotiation
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicStreamEndPoint.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/NegotiatingServerConnection.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
Labels: Bug

#12014 Deny HTTP/3 connection creation for clients missing cert when needClientAuth is true
  jetty-core/jetty-http3/jetty-http3-tests/pom.xml
  jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java
  jetty-core/jetty-quic/jetty-quic-client/pom.xml
  jetty-core/jetty-quic/jetty-quic-client/src/main/java/org/eclipse/jetty/quic/client/ClientQuicSession.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/PemExporter.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java
Labels: Bug

#12010 Ensure expired Set-Cookie not present on push as per spec
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java
Labels: TCK

#11972 Jetty 12.0.x batch of upgrades
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee10/pom.xml
  pom.xml
  tests/jetty-testers/pom.xml
Labels: dependencies

#12026 Issue #12019 ensure cmd line properties files applied
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
Labels: Bug

#12024 Make `Fields` interpret null values as empty strings
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/FieldsTest.java
Labels: Bug

#12043 Increase visibility of legacy multipart parser
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartInputStreamLegacyParser.java
Labels: Enhancement, Sponsored

#12031 Fix Regression on ee9 / ee8 MultiPart parsing
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartFormInputStream.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartInputStreamLegacyParser.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/MultiPartServletTest.java
Labels: Bug, Sponsored

#12042 Jetty 10 Upgrade quiche to version 0.22.0
  jetty-quic/quic-quiche/quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/ForeignIncubatorQuicheConnection.java
  jetty-quic/quic-quiche/quic-quiche-foreign-incubator/src/main/java/org/eclipse/jetty/quic/quiche/foreign/incubator/quiche_h.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
  jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#11974 h2spec plugin version 1.0.12
  jetty-core/jetty-http2/jetty-http2-tests/pom.xml
Labels: dependencies

#12015 jetty-p2 module back
  jetty-p2/pom.xml
  pom.xml
Labels: Build

#12041 Jetty 10: backport the tracking retainable pool from 12
  jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java
  jetty-io/src/main/java/org/eclipse/jetty/io/LogarithmicArrayByteBufferPool.java
  jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
Labels: Enhancement, Sponsored

#12056 Move core demos from jetty-core to jetty-demos
  jetty-core/jetty-bom/pom.xml
  jetty-core/pom.xml
  jetty-demos/jetty-core-demos/jetty-core-demo-handler/pom.xml
  jetty-demos/jetty-core-demos/jetty-core-demo-handler/src/main/config/modules/demo-handler.mod
  jetty-demos/jetty-core-demos/jetty-core-demo-handler/src/main/config/modules/demo.d/demo-handler.xml
  jetty-demos/jetty-core-demos/jetty-core-demo-handler/src/main/java/org/eclipse/jetty/demo/HelloHandler.java
  jetty-demos/jetty-core-demos/pom.xml
  jetty-demos/pom.xml
  jetty-home/pom.xml
Labels: Enhancement

#12061 Merge Jetty 11 into Jetty 12.0
  build/build-resources/pom.xml
  pom.xml
Labels: Enhancement

#12064 Merge Jetty 12.0 into Jetty 12.1
  .github/dependabot.yml
  .gitignore
  Jenkinsfile
  SECURITY.md
  build/build-resources/pom.xml
  jetty-core/jetty-http2/jetty-http2-tests/pom.xml
  jetty-core/jetty-http3/jetty-http3-tests/pom.xml
  jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java
  jetty-core/jetty-quic/jetty-quic-client/pom.xml
  jetty-core/jetty-quic/jetty-quic-client/src/main/java/org/eclipse/jetty/quic/client/ClientQuicSession.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicStreamEndPoint.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/PemExporter.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java
  jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/NegotiatingServerConnection.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/gzip/GzipHandlerTest.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/FieldsTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-sessions/jetty-ee11-test-sessions-infinispan/pom.xml
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartFormInputStream.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/MultiPartInputStreamLegacyParser.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/MultiPartServletTest.java
  jetty-p2/pom.xml
  pom.xml
  tests/jetty-testers/pom.xml
Labels: Enhancement

#12072 Addressing more regressions on form handling in ee9 / ee8 environments
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/FormTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/MultiPartServletTest.java
Labels: Bug, Sponsored

#12078 Issue #12070 fix session lastAccessedTime and isNew
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/CreationTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/SessionHandler.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/CreationTest.java
Labels: Bug

#12081 Issue #10904 Reorder pid and state file checks
  jetty-home/src/main/resources/bin/jetty.sh
Labels: Bug

#12045 Issue #12044 ensure temp dir cleaned up
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/TempDirTest.java
  jetty-ee8/jetty-ee8-webapp/src/test/webapp/WEB-INF/web.xml
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebInfConfiguration.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java
Labels: Bug

#12020 Implement HttpContent.writeTo() async API
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/InputStreamRequestContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/FileMappingHttpContentFactory.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/HttpContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/PreCompressedHttpContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/ResourceHttpContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/ResourceHttpContentFactory.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/VirtualHttpContentFactory.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/FileMappingHttpContentFactoryTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerByteRangesTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/TryPathsHandlerTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/BufferUtilTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ResourceServlet.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResourceServletTest.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ResourceServlet.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletMultiPartFormData.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/DefaultServletTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResourceServletTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ResourceHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ResourceService.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/resource/ByteBufferRangeWriter.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/resource/HttpContentRangeWriter.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/resource/InputStreamRangeWriter.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/resource/RangeWriter.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/resource/SeekableByteChannelRangeWriter.java
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
Labels: Enhancement

#12069 Cleanup and javadoc `HttpContent` API
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/FileMappingHttpContentFactory.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/HttpContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/PreCompressedHttpContent.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/ResourceHttpContent.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ResourceServlet.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ResourceServlet.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ResourceService.java
Labels: Enhancement

#12090 add target/jetty-home as part of the cache as it is useful with jetty-home module
  .mvn/maven-build-cache-config.xml
Labels: Build

#12066 Fixes #11926 - Authority Customizer.
  documentation/jetty/modules/programming-guide/pages/server/http.adoc
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCompliance.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/AuthorityCustomizer.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AbstractServerTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/AuthorityCustomizerTest.java
Labels: save-home
