Repository jetty/jetty.project, pull requests merged in 2024-08, with the labels that each got.

#12144 Jetty 10: Add leak tracking in tests
  jetty-server/pom.xml
  jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java
Labels: Enhancement

#12123 Fixes #12122 - NPE in HttpReceiver.responseContentAvailable().
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpReceiverOverHTTP.java
  jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpReceiverOverFCGI.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java
  jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpReceiverOverHTTP3.java
Labels: save-home

#12113 Improved handling of 100 Continue
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/ContinueProtocolHandler.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
  jetty-core/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/ProxyHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/StringUtil.java
  jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/AbstractProxyServlet.java
  jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java
  jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/AbstractProxyServlet.java
  jetty-ee9/jetty-ee9-proxy/src/test/java/org/eclipse/jetty/ee9/proxy/ProxyServletTest.java
Labels: build-no-cache, build-all-tests, save-home

#12169 Issue #11408 - Environment property values are not expanded
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/PropertyDump.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/PropertyPassingTest.java
Labels: Bug, Sponsored

#12164 Issue #12163 - Adding missing HttpConfiguration fields to JMX and dump()
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
Labels: Bug

#12168 Add Missing changes to ee11 WebInfConfiguration
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/TempDirTest.java
  jetty-ee11/jetty-ee11-webapp/src/main/java/org/eclipse/jetty/ee11/webapp/WebInfConfiguration.java
  jetty-ee11/jetty-ee11-webapp/src/test/java/org/eclipse/jetty/ee11/webapp/TempDirTest.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java
Labels: Build

#12200 Jetty 9.4.x: Improve ThreadLimitHandler
  jetty-server/pom.xml
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java
Labels: Enhancement

#12201 Jetty 10.0.x: Improve ThreadLimitHandler
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
  jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java
Labels: Enhancement

#12199 fix npe when onCompleteFailure happens after reset
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
Labels: Bug

#12083 Fix `DynamicCapacity.release()`
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/BadURITest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
Labels: Bug
