Repository jetty/jetty.project, pull requests merged in 2024-02, with the labels that each got.

#11386 Making FormFields get defaults from Context, not Request
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
Labels: Enhancement

#11389 Allow spec port stripping of 80/443 on websocket too.
  jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
Labels: Enhancement

#11412 Issue #11410 - PathMappingsHandler does not set Server on added handlers
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/PathMappingsHandlerTest.java
Labels: Bug

#11397 Jetty 12: `ContextHandler.getTempDirectory()` does not respect the `Context.getTempDirectory()` contract
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ServerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ContextHandlerTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java
Labels: Bug, build-no-cache

#11409 Issue #11310 - multipart parser dropping some relevant CR bytes in parts
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormDataTest.java
Labels: Bug

#11279 Issue #11271 - fix use of AliasCheckers with CombinedResource
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SymlinkAllowedResourceAliasChecker.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/HotSwapHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/CombinedResource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/AliasCheckerSymlinkTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/combined/WEB-INF/file
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/combined/combinedFile
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/combined/files/file1
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/webroot/files/file2
  tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerMultipleResourceBasesTest.java
  tests/test-integration/src/test/resources/file1
  tests/test-integration/src/test/resources/file2
Labels: Bug, Sponsored

#11437 Issue #11424 - Document default of `jetty.deploy.scanInterval` at `0`
  documentation/jetty-documentation/src/main/asciidoc/operations-guide/deploy/deploy-hot-static.adoc
  jetty-core/jetty-deploy/src/main/config/modules/core-deploy.mod
  jetty-core/jetty-server/src/main/config/modules/server.mod
  jetty-ee10/jetty-ee10-webapp/src/main/config/modules/ee10-deploy.mod
  jetty-ee8/jetty-ee8-webapp/src/main/config/modules/ee8-deploy.mod
  jetty-ee9/jetty-ee9-webapp/src/main/config/modules/ee9-deploy.mod
Labels: Documentation

#10432 Fix buffer leaks in FCGI and H3 `HttpClientIdleTimeoutTest`
  jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java
Labels: Bug

#11418 Jetty 12.0.x 11377 fix jettyhome osgi path
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/util/Util.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/boot/EE10Activator.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/boot/EE9Activator.java
Labels: Bug, Microsoft Windows

#11445 Fix #10805 zero dynamic table
  jetty-http2/http2-client/src/test/java/org/eclipse/jetty/http2/client/DynamicTableTest.java
  jetty-http2/http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
Labels: merge-12-needed

#11402 Issue #11398 - allow frames to be demanded in WebSocket onOpen
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java
Labels: Bug

#11440 Improve jetty-util on Windows
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/PathResource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/URLResourceFactory.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/FileSystemResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/PathResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceAliasTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/UrlResourceFactoryTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/ssl/SslContextFactoryTest.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/MetaInfConfigurationTest.java
Labels: Microsoft Windows, Test

#11443 Fix NPE in HttpReceiverOverHTTP2.read() when the channel's stream is null
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpExchange.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java
Labels: Sponsored, Http Client

#11345 Issue #11270 - Improve XmlConfiguration reporting of Resource location during error
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfigurationException.java
Labels: Enhancement

#11457 Improve Error messages for Ambiguous URIs
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpURITest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
Labels: Enhancement

#11455 Improve DEBUG during WebInfConfiguration.unpack
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebInfConfiguration.java
Labels: Enhancement, Sponsored
