Repository jetty/jetty.project, pull requests merged in 2024-05, with the labels that each got.

#11723 Improve ThreadLimitHandler
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ThreadLimitHandler.java
Labels: Enhancement

#11693 Fix flaky `testUploadWithPendingReadConcurrentServerCloseClosesStream()`
  jetty-core/jetty-tests/jetty-test-client-transports/pom.xml
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
Labels: flaky-test

#11721 Fix `IllegalArgumentException: demand pending`
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ContentProducer.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpInput.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncServletIOTest.java
Labels: Bug

#11770 Issue #11760 fix NPE getRequestURL() for cross context
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcherTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/CrossContextDispatcher.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/CrossContextDispatcherTest.java
Labels: Bug

#11775 Issue #11766 - null out ReadListener on recycle to aid GC.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpInput.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpInput.java
Labels: Enhancement

#11783 Apache Maven Build cache 1.2.0
  pom.xml
Labels: Build

#11759 ContentSinkOutputStream may not rethrow already thrown exception
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSinkOutputStream.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/content/ContentSinkOutputStreamTest.java
Labels: Bug

#11777 Issue #11776 - NPE protection in Request.getServerPort
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/AbstractTrie.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTernaryTrie.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Index.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
Labels: Bug, Sponsored

#11793 Don't create circular throwables and don't throw StackOverflowError if one gets logged
  jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
  jetty-core/jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/StdErrAppenderTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextEvent.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/AsyncContextEvent.java
Labels: Bug

#11808 Fixed header cache for unknown values
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
Labels: Bug, Sponsored

#11825 Allow ContentListener and AsyncContentListener to throw Exception
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/AsyncContentListenerTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/ContentListenerTest.java
Labels: Enhancement

#11827 Fix #11756 empty byte array for no content in ChunkAccumulator
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ChunkAccumulator.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
Labels: Bug

#11799 Issue #11791 fix suffix mapping for non default DefaultServlet usage.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/resources/suffixroot/test.js
Labels: Bug

#11829 Fix #11815 HttpServletMapping
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletHandler.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletPathMapping.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/AsyncContextTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/DispatcherTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ServletTest.java
Labels: Specification

#11824 Issue #11813 add tests for no-ops on Response after commit.
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResponseTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/SetCookieTest.java
Labels: Specification
