Repository jetty/jetty.project, pull requests merged in 2024-04, with the labels that each got.

#11615 Upgrade m-invoker-p to 3.6.1 and simplify configuration for jdk22 build
  pom.xml
Labels: Build

#11619 Fix UTF-8 NFC/NFD tests failures on Macos
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java
Labels: Test

#11638 Issue #11490 - fixing CustomRequestLog.setIgnorePaths
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
Labels: Bug

#11582 Issue #11573 - add new `disable-urlcache.mod`
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-log4j2-webapp/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-log4j2-webapp/src/main/java/org/eclipse/jetty/ee10/log4j2/LogContextListener.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-log4j2-webapp/src/main/java/org/eclipse/jetty/ee10/log4j2/LogServlet.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-log4j2-webapp/src/main/resources/log4j2.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-log4j2-webapp/src/main/webapp/WEB-INF/web.xml
  jetty-ee10/jetty-ee10-tests/pom.xml
  jetty-home/src/main/resources/etc/disable-urlcache.xml
  jetty-home/src/main/resources/modules/disable-urlcache.mod
  tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/DisableUrlCacheTest.java
  tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/OpenIdTests.java
Labels: Enhancement

#11657 Fix flaky `RequestListenersTest.testCompletionListeners()`
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestListenersTest.java
Labels: Test

#11664 12.0.x: Merge upgrade quiche version to 0.21.0
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#11661 Issue #11659 - Properly ignore OWS before field values.
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpParserTest.java
Labels: Bug, Specification

#11674 Jetty 12 main will keep not using the cache but at least will build cache output for PRs
  Jenkinsfile
Labels: Build

#11680 Fix Maven warning about missing duplicate-finder-maven-plugin version
  pom.xml
Labels: Build

#11637 Fix for some invalid server behaviors when a client is aborting a request
  jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicStreamEndPoint.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AbstractTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/RequestReaderTest.java
Labels: Bug, Sponsored

#11684 Cleaning up ee10 `AsyncContextTest`
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextTest.java
Labels: Test

#11672 Issue #11648 - Introducing HttpDateTime class.
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/DateParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpCookieTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpDateTimeTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ResourceService.java
  tests/jetty-jmh/src/main/java/org/eclipse/jetty/http/jmh/HttpDateTimeParseBenchmark.java
Labels: Bug, Specification

#11688 Fix `HttpFields.Mutable.Wrapper.computeField()`
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorClientTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextHandlerTest.java
Labels: Bug, Sponsored

#11670 Tweaking DisableUrlCacheTest to identify flaky nature of testcase.
  tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/DisableUrlCacheTest.java
Labels: flaky-test, build-all-tests

#11685 Issue #11676 fix session CreationTest
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/CreationTest.java
Labels: flaky-test

#11689 Issue #11677 fix AttributeNameTest
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-mongodb/src/test/java/org/eclipse/jetty/ee10/session/nosql/mongodb/AttributeNameTest.java
Labels: flaky-test

#11640 Issue #11026 - fix `jetty.sh restart` flaw
  jetty-home/src/main/resources/bin/jetty.sh
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/jettysh/JettyShStartTest.java
Labels: Bug

#11570 update SizeLimitHandler with fixes needed for appengine tests
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SizeLimitHandler.java
Labels: Sponsored

#11454 Issue #11453 - Testcase for reported UriCompliance issue
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
Labels: Test

#11700 Issue #11699 - ISE when Response does not exist.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java
Labels: Bug

#11703 [April 2024] Jetty 12 Dependency Updates
  build/build-resources/pom.xml
  build/scripts/release-jetty.sh
  pom.xml
Labels: Build, dependencies

#11713 Issue #11706 ee9 BadServletInit in wrong package
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-badinit-webapp/src/main/java/org/eclipse/jetty/ee9/test/BadServletInit.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-badinit-webapp/src/main/webapp/WEB-INF/web.xml
Labels: build-no-cache
