Repository jetty/jetty.project, pull requests merged in 2025-07, with the labels that each got.

#13299 Race Condition in WebSocketConnection - Job failed: java.lang.IllegalStateException: FILLING_AND_PARSING
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java
Labels: High Priority, Bug

#13331 Update URL reference in WebSocket javadoc
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/exception/BadPayloadException.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/exception/MessageTooLargeException.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/exception/ProtocolException.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/StatusCode.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-api/src/main/java/org/eclipse/jetty/ee9/websocket/api/StatusCode.java
Labels: Documentation

#13345 Fix `IllegalStateException` when aborting a blocking write
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannel.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java
Labels: Bug

#13288 jetty 12.0.x 8867 plugin toolchain
  jetty-core/jetty-maven/src/main/java/org/eclipse/jetty/maven/AbstractForker.java
  jetty-core/jetty-maven/src/main/java/org/eclipse/jetty/maven/AbstractHomeForker.java
  jetty-core/jetty-maven/src/main/java/org/eclipse/jetty/maven/AbstractServerForker.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/JettyForker.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/JettyHomeForker.java
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/AbstractWebAppMojo.java
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/JettyForker.java
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/JettyHomeForker.java
Labels: Enhancement

#13365 Issue #13364 change deploy WARN to DEBUG
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/ScanningAppProvider.java
Labels: Bug

#13358 Fixes #12300: add null check in RewriteHandler.doStart() and unit test
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteHandlerMissingChildTest.java
Labels: Bug

#13332 Implement accept-language and accept-encoding rewrite rules
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSV.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedCSVTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/ForceRequestHeaderValueRule.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteEncodingRule.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteLanguageRule.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/AbstractRuleTest.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteEncodingRuleTest.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteLanguageAndEncodingRuleTest.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteLanguageRuleTest.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/common/encoders/LongEncoder.java
Labels: save-home

#13382 fix multithread builds and simplify poms
  tests/pom.xml
  tests/test-cross-context-dispatch/ccd-common/pom.xml
  tests/test-cross-context-dispatch/ccd-ee10-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee11-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee8-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-ee9-webapp/pom.xml
  tests/test-cross-context-dispatch/ccd-tests/pom.xml
  tests/test-cross-context-dispatch/pom.xml
Labels: Build

#13384 fix mod file name for inclusion
  documentation/jetty/modules/operations-guide/pages/modules/standard.adoc
Labels: Documentation

#13391 fix/jetty 12.1/tck fixes non supported character encoding
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteThroughWriter.java
Labels: TCK

#13347 Updating release checklist for new central.sonatype.com reality
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Build

#13396 Issue #13395 Support async dispatch to same context
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextState.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/AsyncTest.java
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContextState.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-sessions/jetty-ee11-test-sessions-common/src/test/java/org/eclipse/jetty/ee11/session/AsyncTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/AsyncTest.java
Labels: TCK

#13394 Issue #13393 NPE setContentType
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextResponse.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ResponseHeadersTest.java
Labels: TCK
