Repository jetty/jetty.project, pull requests merged in 2025-04, with the labels that each got.

#12925 Fix to EE8/EE9 StandardDescriptorProcessor to allow duplicate ServletMappings
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/StandardDescriptorProcessor.java
Labels: Sponsored

#12909 Allow EE8/EE9 HttpServletResponse.addHeader to accept null header values
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpGeneratorClientTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/ResponseHttpFields.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiResponse.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ResponseHeadersTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ResponseHeadersTest.java
Labels: Sponsored

#12950 Issue #12361 - Fix ee# ErrorHandler showMessageInTitle flag
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ErrorHandler.java
Labels: Bug

#12875 Fixes for EE11 Jakarta WebSocket implementation to fix TCK failures.
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFieldsMap.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/AbstractMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/DispatchedMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/InputStreamMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/MessageOutputStream.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/messages/ReaderMessageSink.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/InvokerUtils.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/ReflectUtils.java
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/com/acme/websocket/PongSocketStringReturn.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-client/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/client/JakartaWebSocketClientContainer.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-client/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/client/JakartaWebSocketClientFrameHandlerFactory.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-client/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/client/internal/JakartaClientUpgradeRequest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketAsyncRemote.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketContainer.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketFrameHandler.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketFrameHandlerFactory.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketRemoteEndpoint.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketSession.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/decoders/AvailableDecoders.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/decoders/CharacterDecoder.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/decoders/RegisteredDecoder.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/encoders/AvailableEncoders.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/encoders/RegisteredEncoder.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/messages/AbstractDecodedMessageSink.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/messages/DecodedBinaryStreamMessageSink.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/common/messages/DecodedTextStreamMessageSink.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/AbstractJakartaWebSocketFrameHandlerTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/DummyFrameHandlerFactory.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketFrameHandlerBadSignaturesTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketFrameHandlerOnMessageBinaryTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/JakartaWebSocketFrameHandlerOnMessageTextTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/messages/AbstractMessageSinkTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/common/util/InvokerUtilsStaticParamsTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/server/JakartaWebSocketServerContainer.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/server/JakartaWebSocketServerFrameHandlerFactory.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/server/internal/JakartaWebSocketCreator.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/server/internal/JsrHandshakeRequest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/server/internal/PathParamIdentifier.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/WSServer.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/matchers/IsMessageHandlerType.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/matchers/IsMessageHandlerTypeRegistered.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/com/acme/websocket/PongSocketStringReturn.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/GracefulCloseTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/JakartaOnCloseTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/ProgrammaticWebSocketUpgradeTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/coders/AvailableDecodersTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/coders/AvailableEncodersTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/coders/DecoderListTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/handlers/MessageHandlerTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/server/DeploymentTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/server/PingPongTest.java
Labels: TCK

#12964 Use provided buffer size when serving non-Path Resources
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java
Labels: Enhancement

#12962 Upgrade to quiche 0.23.5
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheBinding.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/ForeignQuicheBinding.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/pom.xml
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheBinding.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#12968 Enable ee9 AsyncContextTest and update.
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/AsyncContextTest.java
Labels: Test

#12932 Jetty 12.0.x surefire upgrade 3.5.3
  Jenkinsfile
  jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java
  jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/BufferUtilTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/MountedPathResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/PathResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceAliasTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/ssl/X509Test.java
  pom.xml
Labels: Build

#12974 Introduce `Content.Source.Factory` to allow 3rd parties benefitting from a fast codepath in `IOResources`
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartCaptureTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/BufferUtilTest.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/HugeResourceTest.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/HugeResourceTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/CoreMultiPartTest.java
Labels: Enhancement

#13001 Issue #12997 - Limit environments/ directory changes to just xml and properties files
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
Labels: Bug

#12996 Issue #12991 - Fix ClassCastException on Redeploy
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerRuntimeUpdatesTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandlerCollection.java
Labels: Bug

#12919 Reduce some OSGi code duplication with core Activator.
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/AbstractContextProvider.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/AbstractEEActivator.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/BundleIndex.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/BundleWebAppProvider.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/JettyBootstrapActivator.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/JettyServerFactory.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/LibExtClassLoaderHelper.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/OSGiServerConstants.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/OSGiWebappConstants.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/PackageAdminServiceListener.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/ServerClasspathContributor.java
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/util/Util.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee10/osgi/boot/jsp/FragmentActivator.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee10/osgi/boot/jsp/TLDServerClasspathContributor.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/annotations/AnnotationConfiguration.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/annotations/AnnotationParser.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/boot/EE10Activator.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/boot/OSGiMetaInfConfiguration.java
  jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/src/main/java/org/eclipse/jetty/ee10/osgi/boot/PackageAdminServiceTracker.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee11/osgi/boot/jsp/FragmentActivator.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee11/osgi/boot/jsp/TLDServerClasspathContributor.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot/src/main/java/org/eclipse/jetty/ee11/osgi/annotations/AnnotationConfiguration.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot/src/main/java/org/eclipse/jetty/ee11/osgi/annotations/AnnotationParser.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot/src/main/java/org/eclipse/jetty/ee11/osgi/boot/EE11Activator.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot/src/main/java/org/eclipse/jetty/ee11/osgi/boot/OSGiMetaInfConfiguration.java
  jetty-ee11/jetty-ee11-osgi/jetty-ee11-osgi-boot/src/main/java/org/eclipse/jetty/ee11/osgi/boot/PackageAdminServiceTracker.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-ee8/jetty-ee8-osgi/jetty-ee8-osgi-boot-jsp/pom.xml
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot-jsp/pom.xml
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee9/osgi/boot/jsp/FragmentActivator.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot-jsp/src/main/java/org/eclipse/jetty/ee9/osgi/boot/jsp/TLDServerClasspathContributor.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/annotations/AnnotationConfiguration.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/annotations/AnnotationParser.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/boot/EE9Activator.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/boot/OSGiMetaInfConfiguration.java
  jetty-ee9/jetty-ee9-osgi/jetty-ee9-osgi-boot/src/main/java/org/eclipse/jetty/ee9/osgi/boot/PackageAdminServiceTracker.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiAnnotationParser.java
Labels: Enhancement

#12948 Use weld release 6.0.1.Final for ee11 and 5.1.5.Final for ee10
  pom.xml
Labels: dependencies

#13005 Issue #13000 - remove old jetty.deploy.environmentXml=<path> feature
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/ContextHandlerFactory.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardContextHandlerFactory.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerStartupTest.java
Labels: Bug, behavior-change

#12987 Replace `Scheduler` with `CyclicTimeout` in websocket `FrameFlusher` to avoid repeatedly scheduling timeout tasks
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FrameFlusher.java
Labels: Enhancement

#12947 Fix sporadic NPE in `HttpChannelState.onFailure()`
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Labels: Bug

#13009 Fixes #13008 - Introduce HttpClient's Request.onResponseListener().
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/client/http/HTTPClientDocs.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Request.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpConnectionLifecycleTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpRequestAbortTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/http/HttpSenderOverHTTPTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/CoreClientUpgradeRequest.java
Labels: Enhancement, Sponsored

#12989 Fixes #12988 - Introduce an HTTP/2 frame listener.
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/client/http2/HTTP2ClientDocs.java
  documentation/jetty/modules/programming-guide/pages/client/http.adoc
  documentation/jetty/modules/programming-guide/pages/client/http2.adoc
  jetty-core/jetty-http2/jetty-http2-client/src/main/java/org/eclipse/jetty/http2/client/HTTP2ClientConnectionFactory.java
  jetty-core/jetty-http2/jetty-http2-client/src/main/java/org/eclipse/jetty/http2/client/internal/HTTP2ClientSession.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/FrameType.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/generator/Generator.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/generator/NoOpGenerator.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/Parser.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerSession.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HTTP2ListenersTest.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ClientConnector.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java
Labels: Enhancement, Sponsored

#12984 Issue #12981 - add flag to allow Annotation Introspection if metatdata complete
  jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/AnnotationIntrospector.java
Labels: Sponsored

#13010 Issue #11492 - Auto add `AliasChecker` for custom Base Resource in `DefaultServlet`
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SymlinkAllowedResourceAliasChecker.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ResourceServlet.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DefaultServletTest.java
  jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/DefaultServlet.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/DefaultServletTest.java
Labels: Bug

#13020 Issue #13019 - util-ajax: support CharSequence for JSON
  jetty-core/jetty-util-ajax/src/main/java/org/eclipse/jetty/util/ajax/JSON.java
Labels: Enhancement

#13016 Allow the HttpClient in AbstractProxyServlet to configure additional attributes
  jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/AbstractProxyServlet.java
  jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/AbstractProxyServlet.java
Labels: Enhancement

#13017 Upgrade quiche to version 0.24.0
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#13039 Fix `SettingsTest` flakiness
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java
Labels: flaky-test

#13032 Make sure `SessionDataStore` is not stopped while there are pending requests using it
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/GracefulHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/GracefulHandlerTest.java
  jetty-core/jetty-session/src/test/java/org/eclipse/jetty/session/SessionHandlerTest.java
Labels: Bug

#12998 Issue #12990 - Introduce `static-deploy` module
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardContextHandlerFactory.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerCoreWebappTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerRuntimeUpdatesTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/StaticContextHandlerTest.java
  jetty-core/jetty-server/src/main/config/etc/jetty-static-deploy.xml
  jetty-core/jetty-server/src/main/config/modules/core-deploy.mod
  jetty-core/jetty-server/src/main/config/modules/static-deploy.mod
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Deployable.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/CoreContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StaticContextHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/StaticContextHandlerTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IO.java
  jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/WebAppPropertyConverter.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee11/jetty-ee11-maven-plugin/src/main/java/org/eclipse/jetty/ee11/maven/plugin/WebAppPropertyConverter.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/java/org/eclipse/jetty/ee11/test/DeploymentDefaultContextPathTest.java
  jetty-ee11/jetty-ee11-webapp/src/main/java/org/eclipse/jetty/ee11/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-maven-plugin/src/main/java/org/eclipse/jetty/ee9/maven/plugin/WebAppPropertyConverter.java
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/JettyHomeTester.java
  tests/test-distribution/test-distribution-common/pom.xml
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DeployerTest.java
Labels: Enhancement, Bug

#13068 Issue #13046 - Standardize URL Parameter Decoding in UrlEncoder methods (Pull Based)
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/UrlParameterDecoderTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/FormTest.java
  tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/UrlParameterDecoderBenchmark.java
Labels: Bug, Sponsored
