Repository jetty/jetty.project, pull requests merged in 2025-01, with the labels that each got.

#12671 Check UriCompliance.Violation.ALLOW_BAD_UTF8 in query parameter extraction
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/RequestTest.java
Labels: Sponsored

#12675 Issue #12674 - Exclude Xalan from ee8 dependencies
  jetty-ee8/jetty-ee8-glassfish-jstl/pom.xml
  jetty-ee8/jetty-ee8-home/pom.xml
  jetty-ee8/jetty-ee8-osgi/test-jetty-ee8-osgi/pom.xml
  jetty-ee8/pom.xml
Labels: Bug, Build

#12684 Issue #12683 Fix cross context dispatch to root context.
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcherTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/CrossContextServletContext.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/CrossContextDispatcherTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/resources/docroot/empty
Labels: Bug, Sponsored

#12704 Fix CachingHttpContentFactory$CachedHttpContent already released buffer
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java
Labels: Bug

#12696 Issue #12695 - don't return ByteBuffer from .toMappedBuffer if FS reports as UnsupportedOperationException.
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpTester.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/FileMappingHttpContentFactory.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandlerTest.java
Labels: Bug

#12732 Issue #12730 - regex rules have configs for query matching and merging
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RedirectRegexRule.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RegexRule.java
  jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteRegexRule.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RedirectRegexRuleTest.java
  jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteRegexRuleTest.java
Labels: Enhancement, Sponsored

#12738 Issue #11494 - PathMappingsHandler exposes PathSpec and Context based on PathSpec.
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Context.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/PathMappingsHandlerTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/TryPathsHandlerTest.java
Labels: Enhancement

#12724 Fix SymlinkAllowedResourceAliasChecker for use with CombinedResource
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SymlinkAllowedResourceAliasChecker.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerMultipleResourceBasesTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerMultipleResourceTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerSymlinkTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerTestBase.java
  tests/test-integration/src/test/resources/multipleResourceTest/webroot2/foo/file3
  tests/test-integration/src/test/resources/multipleResourceTest/webroot3/file2
Labels: Bug, Sponsored

#12737 Upgrade to quiche 0.23.2
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/NativeHelper.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_path_stats.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/bool.java
  pom.xml
Labels: Enhancement

#12711 Rehabilitate quadratic pool
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferAggregator.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/MathUtils.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdPool.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/MathUtilsTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/TypeUtilTest.java
Labels: Enhancement
