Repository jetty/jetty.project, pull requests merged in 2025-09, with the labels that each got.

#13531 Fix delays that are too short to avoid flakiness in websocket tests
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/WebSocketTester.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/WebSocketTester.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/WebSocketTester.java
Labels: flaky-test

#13279 Issue #12735 - restore some documentation for the servlet dependent Jetty WebSocket API usage.
  documentation/jetty/modules/code/examples/pom.xml
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/server/websocket/WebSocketServerDocs.java
  documentation/jetty/modules/programming-guide/pages/migration/12.0-to-12.1.adoc
  documentation/jetty/modules/programming-guide/pages/server/websocket.adoc
Labels: Documentation

#13572 use an empty repository for release
  build/scripts/release-jetty.sh
Labels: Build

#13595 Issue #13592 ClosedFileSystemException for jar:file base resource
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee11/jetty-ee11-webapp/src/test/java/org/eclipse/jetty/ee11/webapp/WebAppContextTest.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/WebAppContextTest.java
Labels: Bug

#13628 Fixes #13621 - Restore BufferingResponseListener.onContent(Response, ByteBuffer) behavior.
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractResponseListener.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientDemandTest.java
Labels: Bug, Sponsored

#13606 Added test case for request timeout when reading request content.
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
Labels: Sponsored

#13637 12.0.x: H2 reset: fix missing callback completion
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
Labels: Bug
