Repository jetty/jetty.project, pull requests merged in 2025-05, with the labels that each got.

#13067 Fix default fallback Jetty version
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Jetty.java
Labels: Bug

#13015 Issue #13011 - Properly deprecate older constants from `org.eclipse.jetty.server.Deployable`
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Deployable.java
Labels: Bug

#13080 Issue #13064 - Let test timeout if there is an issue.
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ShutdownMonitor.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ShutdownMonitorTest.java
Labels: Test, Build

#13049 Issue #13046 - Standardize URL Parameter Decoding in UrlEncoder methods
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/UrlParameterDecoderTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/NullAppendable.java
  tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/UrlParameterDecoderBenchmark.java
Labels: Bug

#13112 Improve reliability of WebAppContextTest
  jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java
  jetty-ee11/jetty-ee11-webapp/src/test/java/org/eclipse/jetty/ee11/webapp/WebAppContextTest.java
  jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/WebAppContextTest.java
Labels: Test

#13103 Issue #12995 - cleanup DeploymentScanner path filter
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
Labels: Bug

#13069 Deploy Environment Weights
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardContextHandlerFactory.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/AbstractCleanEnvironmentTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerCoreWebappTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerDeferredStartupTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerRuntimeUpdatesTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerStartupTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/StaticContextHandlerTest.java
  jetty-core/jetty-deploy/src/test/resources/jetty-core-deploy-custom.xml
  jetty-core/jetty-server/src/main/config/modules/core-deploy.mod
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/CoreContextHandler.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-ee10/jetty-ee10-webapp/src/main/config/modules/ee10-deploy.mod
  jetty-ee11/jetty-ee11-webapp/src/main/config/modules/ee11-deploy.mod
  jetty-ee8/jetty-ee8-webapp/src/main/config/modules/ee8-deploy.mod
  jetty-ee9/jetty-ee9-webapp/src/main/config/modules/ee9-deploy.mod
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DeployModulesTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DeployerTest.java
Labels: Enhancement

#13105 Issue #13104 - Changing DeploymentScanner monitoredDir to webappsDir
  jetty-core/jetty-deploy/src/main/config/etc/jetty-deployment-scanner.xml
  jetty-core/jetty-deploy/src/main/config/modules/deployment-scanner.mod
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerCoreWebappTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/StaticContextHandlerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/test/XmlConfiguredJetty.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/DeploymentDefaultContextPathTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/DeploymentErrorTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/deploy.xml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/java/org/eclipse/jetty/ee11/test/DeploymentDefaultContextPathTest.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/java/org/eclipse/jetty/ee11/test/DeploymentErrorTest.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/resources/deploy.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/java/org/eclipse/jetty/ee9/test/DeploymentDefaultContextPathTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/java/org/eclipse/jetty/ee9/test/DeploymentErrorTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/resources/deploy.xml
Labels: Enhancement

#13106 Issue #13040 - Finish implementation of `jetty.deploy.baseResource`
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/CoreContextHandlerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/StaticContextHandlerTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/CoreContextHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StaticContextHandler.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee11/jetty-ee11-webapp/src/main/java/org/eclipse/jetty/ee11/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/AbstractJettyHomeTest.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DeployerTest.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Bug

#13121 Deploy Dump & cleanup
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/ContextHandlerFactory.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/DeploymentScanner.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardContextHandlerFactory.java
  jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentScannerTest.java
Labels: Enhancement

#13134 remove non used demo-template, skip deployment for test modules
  jetty-core/jetty-compression/jetty-compression-tests/pom.xml
  jetty-core/jetty-quic/jetty-quic-tests/pom.xml
  jetty-demos/jetty-servlet5-demos/jetty-servlet5-demo-jndi-webapp/src/main/config/modules/ee10-demo-jndi.mod
  jetty-demos/jetty-servlet5-demos/jetty-servlet5-demo-jndi-webapp/src/main/config/modules/ee11-demo-jndi.mod
  jetty-demos/jetty-servlet5-demos/jetty-servlet5-demo-jndi-webapp/src/main/config/modules/ee9-demo-jndi.mod
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-template/pom.xml
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-template/src/main/resources/demo.css
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-template/src/main/resources/index.html
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-template/src/main/resources/small_powered_by.gif
  jetty-ee10/jetty-ee10-demos/pom.xml
  jetty-ee11/jetty-ee11-demos/jetty-ee11-demo-template/pom.xml
  jetty-ee11/jetty-ee11-demos/jetty-ee11-demo-template/src/main/resources/demo.css
  jetty-ee11/jetty-ee11-demos/jetty-ee11-demo-template/src/main/resources/index.html
  jetty-ee11/jetty-ee11-demos/jetty-ee11-demo-template/src/main/resources/small_powered_by.gif
  jetty-ee11/jetty-ee11-demos/pom.xml
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-template/pom.xml
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-template/src/main/resources/demo.css
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-template/src/main/resources/index.html
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-template/src/main/resources/small_powered_by.gif
  jetty-ee9/jetty-ee9-demos/pom.xml
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DemoModulesTests.java
Labels: Build

#13152 Minor correction in logo color
  .idea/icon.png
  logos/jetty-avatar.svg
Labels: Task

#13153 Dependency Updates - 12.0.x to 12.1.x
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/pom.xml
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootWithBundle.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestOSGiUtil.java
  jetty-ee10/pom.xml
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/pom.xml
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestOSGiUtil.java
  jetty-ee8/jetty-ee8-osgi/test-jetty-ee8-osgi/pom.xml
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/pom.xml
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiAnnotationParser.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestOSGiUtil.java
  jetty-ee9/jetty-ee9-plus/pom.xml
  jetty-ee9/pom.xml
  pom.xml
Labels: dependencies

#13130 Issue #13110 - Cleanup `<jdk>` profile ranges
  documentation/jetty/modules/code/examples/pom.xml
  jetty-core/jetty-http-spi/pom.xml
  jetty-core/jetty-tests/jetty-test-client-transports/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/pom.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-infinispan/pom.xml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-client-transports/pom.xml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-sessions/jetty-ee11-test-sessions-infinispan/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-client-transports/pom.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-infinispan/pom.xml
  tests/test-distribution/pom.xml
Labels: Build, build-no-cache

#13129 Workstation wide cache and RRF
  .github/ci-mimir-daemon.properties
  .github/workflows/codeql-analysis.yml
  .mvn/extensions.xml
  .mvn/maven.config
  .mvn/rrf/groupId-confluent.txt
  .mvn/rrf/groupId-google-maven-central-copy.txt
  .mvn/rrf/groupId-hazelcast-security.txt
  .mvn/rrf/groupId-maven-central.txt
  .mvn/rrf/groupId-redhat-ga.txt
Labels: Build

#13161 Change default stop timeout value in `WebSocketClient`
  jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketStopTest.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientCloseTest.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-client/src/main/java/org/eclipse/jetty/ee9/websocket/client/WebSocketClient.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/WebSocketStopTest.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/client/ClientCloseTest.java
Labels: Bug

#13159 Fixes #13131 - Surface received GOAWAY in HttpClient.
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/client/http2/HTTP2ClientDocs.java
  documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/client/http3/HTTP3ClientDocs.java
  documentation/jetty/modules/programming-guide/pages/client/http.adoc
  documentation/jetty/modules/programming-guide/pages/client/http2.adoc
  documentation/jetty/modules/programming-guide/pages/client/http3.adoc
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/RetryableRequestException.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/RetryableStreamException.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/RetryRequestTest.java
  jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpReceiverOverHTTP3.java
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java
  jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/RetryableStreamException.java
  jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/HttpClientTransportOverHTTP3Test.java
  jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/RetryRequestTest.java
Labels: Enhancement

#13136 Do not abort response in nested HttpChannelState.onError if sendError
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java
Labels: Sponsored

#13147 Support `maven.offline` property in jetty-start, to control of download of maven files from remote repos during `--add-modules`
  Jenkinsfile
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/BaseBuilder.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializer.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/fileinits/MavenLocalRepoFileInitializerTest.java
  tests/jetty-testers/pom.xml
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/JettyHomeTester.java
  tests/jetty-testers/src/main/java/org/eclipse/jetty/tests/testers/ProcessWrapper.java
  tests/test-distribution/pom.xml
  tests/test-distribution/test-distribution-common/pom.xml
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/AbstractJettyHomeTest.java
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Enhancement

#13165 Issue #13057 - ServletContext.getResource() failures should result in MalformedURLException or null
  jetty-ee10/jetty-ee10-servlet/pom.xml
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextResourcesTest.java
  jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/CrossContextServletContext.java
  jetty-ee9/jetty-ee9-servlet/pom.xml
  jetty-ee9/jetty-ee9-servlet/src/main/java/module-info.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ServletContextResourcesTest.java
  jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java
Labels: Bug, Specification

#13174 Jetty 12.0.x setup pom and release script for new central portal
  build/scripts/release-jetty.sh
  pom.xml
Labels: Build
