Repository jetty/jetty.project, pull requests merged in 2025-02, with the labels that each got.

#12761 Issue #12760 force running flatten goal to really have boms generated and not cached one
  .mvn/maven-build-cache-config.xml
Labels: Build

#12770 Issue #12768 - Cleanup references to old Jetty versions
  jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
  jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
  jetty-core/jetty-start/src/test/java/org/eclipse/jetty/start/CommandLineBuilderTest.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/test/java/org/eclipse/jetty/websocket/client/WebSocketClientInitTest.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/main/java/org/eclipse/jetty/ee10/demos/LikeJettyXml.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/test/java/org/eclipse/jetty/ee10/demos/LikeJettyXmlTest.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-embedded/src/test/java/org/eclipse/jetty/ee10/demos/ManyConnectorsTest.java
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-jetty-webapp/src/main/webapp/remote.html
  jetty-ee10/jetty-ee10-demos/jetty-ee10-demo-proxy-webapp/src/test/java/org/eclipse/jetty/ee10/demos/ProxyWebAppTest.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/main/java/org/eclipse/jetty/ee9/demos/LikeJettyXml.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/test/java/org/eclipse/jetty/ee9/demos/LikeJettyXmlTest.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-embedded/src/test/java/org/eclipse/jetty/ee9/demos/ManyConnectorsTest.java
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-jetty-webapp/src/main/webapp/remote.html
  jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-proxy-webapp/src/test/java/org/eclipse/jetty/ee9/demos/ProxyWebAppTest.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestOSGiUtil.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-client/src/test/java/org/eclipse/jetty/ee9/websocket/client/WebSocketClientInitTest.java
  jetty-home/src/main/resources/bin/jetty.sh
Labels: Bug

#12786 Jetty 10.0.x: avoid buffer use after repooling
  jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
Labels: Bug

#12769 Introduce Scanner.ChangeSetListener
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/ScannerTest.java
Labels: Enhancement

#12811 Issue #12810 - add missing jetty-ee artifact to core jetty-bom
  jetty-core/jetty-bom/pom.xml
Labels: Bug

#12823 Issue #12821 - Restore ee9/ee8 `ContextHandler.is/setCompactPath` behavior for backward compat reasons
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
Labels: Bug, Sponsored

#12727 Cancel write semantic
  jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/generator/Flusher.java
  jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/FrameType.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/CancelWriteTest.java
  jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/StreamResetTest.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractEndPoint.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/EndPoint.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/ArrayByteBufferPoolTest.java
  jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/WriteFlusherTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CancelWriteTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpStreamTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/FutureCallback.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CallbackTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/internal/MockEndpoint.java
Labels: High Priority, Bug

#12796 Do not decode path in EE9 Dispatcher
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcherTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Dispatcher.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/CrossContextDispatcherTest.java
Labels: Sponsored

#12822 Issue #12821 - expand javadoc/comments of ContextHandler.setCompactPath/isCompactPath
  jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
Labels: Enhancement, Sponsored, Documentation

#12827 Added tests for legacy URI compliance
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlEncoded.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/UrlEncodedUtf8Test.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/RequestTest.java
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java
  jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/RequestTest.java
Labels: Sponsored
