Repository jetty/jetty.project, pull requests merged in 2025-10, with the labels that each got.

#13646 Improve HTTP/2 and HTTP/3 invalid header value exception message
  jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java
  jetty-core/jetty-http2/jetty-http2-hpack/src/test/java/org/eclipse/jetty/http2/hpack/HpackTest.java
  jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/QpackEncoder.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java
Labels: Enhancement, Sponsored

#13612 Issue #13603 - Bad Accept-Language parsing fix for Locale. [12.1.x]
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSV.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedQualityCSV.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedCSVTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
  jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/RequestHeadersTest.java
Labels: Bug, Sponsored

#13633 Implement etag support in CompressionHandler
  jetty-core/jetty-compression/jetty-compression-brotli/src/test/java/org/eclipse/jetty/compression/brotli/BrotliCompressionTest.java
  jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/Compression.java
  jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipCompressionTest.java
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/CompressionHandler.java
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/internal/CompressionResponse.java
  jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/internal/DecompressionRequest.java
  jetty-core/jetty-compression/jetty-compression-tests/src/test/java/org/eclipse/jetty/compression/CompressionHandlerTest.java
  jetty-core/jetty-compression/jetty-compression-tests/src/test/java/org/eclipse/jetty/compression/CompressionTest.java
  jetty-core/jetty-compression/jetty-compression-zstandard/src/test/java/org/eclipse/jetty/compression/zstandard/ZstandardCompressionTest.java
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
Labels: Sponsored

#13663 Issue #13603 - Params only parsing from HttpFields.getValueList() is broken
  jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSV.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldTest.java
  jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedCSVTest.java
Labels: High Priority, Bug

#13671 Fix ServerWebSocketContainer lifecycle when restarted.
  jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeHandler.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/RestartTest.java
  jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/JakartaWebSocketRestartTest.java
Labels: High Priority, Bug
