Repository jetty/jetty.project, pull requests merged in 2025-03, with the labels that each got.

#12831 Always resolve pathSpec with asPathSpec in ConstraintSecurityHandler
  jetty-ee9/jetty-ee9-security/src/main/java/org/eclipse/jetty/ee9/security/ConstraintSecurityHandler.java
Labels: Sponsored

#12844 Fix `StatisticsHandlerTest`'s non-compliant tests
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/StatisticsHandlerTest.java
Labels: Test

#12843 Fix flaky `HttpClientStreamTest.testInputStreamResponseListenerBufferedRead`
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
Labels: Bug

#12835 Quoted Request Log #12834
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
Labels: High Priority, Bug

#12847 Use try-with-resources on `HttpClient` and `HTTP2Client` in OSGi Tests.
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootWithAnnotations.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootWithBundle.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootWithBundleJettyHome.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiBootWithJsp.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiBootWithAnnotations.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiBootWithBundleJettyHome.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiBootWithJsp.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestJettyOSGiClasspathResources.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiBootHTTP2Conscrypt.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiBootHTTP2JDK9.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiBootWithAnnotations.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiBootWithJsp.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestJettyOSGiClasspathResources.java
Labels: Test

#12849 Improve OSGi `ServerConnectorListener` implementation.
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/util/ServerConnectorListener.java
Labels: Test, Build

#12850 Improve TestOSGIUtil lookup of XML.
  jetty-core/jetty-osgi/src/main/java/org/eclipse/jetty/osgi/JettyBootstrapActivator.java
  jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestOSGiUtil.java
  jetty-ee11/jetty-ee11-osgi/test-jetty-ee11-osgi/src/test/java/org/eclipse/jetty/ee11/osgi/test/TestOSGiUtil.java
  jetty-ee9/jetty-ee9-osgi/test-jetty-ee9-osgi/src/test/java/org/eclipse/jetty/ee9/osgi/test/TestOSGiUtil.java
Labels: Test

#12870 Issue #12869 - XmlConfiguration should only load XML files that end in `.xml` extension.
  jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
Labels: Bug, Sponsored

#12873 Issue #12871 - Add ee8-cdi sub-module
  jetty-ee8/jetty-ee8-cdi/pom.xml
  jetty-ee8/jetty-ee8-cdi/src/main/config/etc/cdi/jetty-ee8-cdi.xml
  jetty-ee8/jetty-ee8-cdi/src/main/config/modules/ee8-cdi-decorate.mod
  jetty-ee8/jetty-ee8-cdi/src/main/config/modules/ee8-cdi-spi.mod
  jetty-ee8/jetty-ee8-cdi/src/main/config/modules/ee8-cdi.mod
  jetty-ee8/jetty-ee8-cdi/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  jetty-ee8/jetty-ee8-cdi/src/main/resources/META-INF/services/org.eclipse.jetty.ee8.webapp.Configuration
  jetty-ee8/jetty-ee8-home/pom.xml
  jetty-ee8/pom.xml
Labels: Enhancement

#12866 Allow `_callbackFailure` to be non-null in `HttpChannelState.HandlerInvoker.succeeded()`
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Labels: Bug

#12885 Fixes #12882 - HttpConfiguration setResponseHeaderSize is ineffective in 12.0.17.
  jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java
  jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/AbstractHTTP3ServerConnectionFactory.java
  jetty-core/jetty-server/src/main/config/etc/jetty.xml
  jetty-core/jetty-server/src/main/config/modules/server.mod
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java
  jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpConnectionTest.java
  jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/LargeHeaderTest.java
Labels: High Priority, Bug

#12854 Make `Environment.ensure()` call from thread-safe context
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentManagerLifeCycleRouteTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentManagerTest.java
  jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/MockAppProvider.java
  jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/TestableWebAppClassLoaderContext.java
  jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/WebAppClassLoaderTest.java
  jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/WebAppClassLoaderUrlStreamTest.java
  jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/WebAppClassLoadingTest.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/component/EnvironmentTest.java
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java
  jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
  jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/DeploymentErrorTest.java
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/RFC2616Base.xml
  jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/deploy.xml
  jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/java/org/eclipse/jetty/ee11/test/DeploymentErrorTest.java
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/resources/RFC2616Base.xml
  jetty-ee11/jetty-ee11-tests/jetty-ee11-test-integration/src/test/resources/deploy.xml
  jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/java/org/eclipse/jetty/ee9/test/DeploymentErrorTest.java
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/resources/RFC2616Base.xml
  jetty-ee9/jetty-ee9-tests/jetty-ee9-test-integration/src/test/resources/deploy.xml
Labels: flaky-test

#12896 Fix SSL buffer leak
  jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
Labels: Bug

#12864 Issue #12824 add lib/eeXX/ext modules
  jetty-home/src/main/resources/modules/ee10-ext.mod
  jetty-home/src/main/resources/modules/ee11-ext.mod
  jetty-home/src/main/resources/modules/ee8-ext.mod
  jetty-home/src/main/resources/modules/ee9-ext.mod
  tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
Labels: Enhancement

#12905 12.0.x: Fix SSL buffer leak
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
Labels: Bug

#12907 Issue #12906 - URIUtil.correctURI() should be able to handle `file:/`
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URIUtilTest.java
Labels: Bug

#12911 Upgrade quiche to version 0.23.4
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/main/java/org/eclipse/jetty/quic/quiche/foreign/quiche_h.java
  jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/LibQuiche.java
  pom.xml
Labels: Enhancement

#12920 Fix npe in ee11 `AsyncMiddleManServletTest`
  jetty-ee11/jetty-ee11-proxy/src/test/java/org/eclipse/jetty/ee11/proxy/AsyncMiddleManServletTest.java
Labels: Bug

#12921 Fix bad URL to URI conversion in `ResourceFactory.newClassLoaderResource()`
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java
  jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/MountedPathResourceTest.java
Labels: Bug

#12931 Addendum to #12927 for #12916.
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/InputStreamResponseListener.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpConnectionOverHTTP.java
  jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpConnectionOverFCGI.java
  jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpReceiverOverFCGI.java
  jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTimeoutTest.java
  jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java
  jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/MultiPartServletTest.java
  tests/test-integration/src/test/java/org/eclipse/jetty/test/CoreMultiPartTest.java
Labels: build-all-tests

#12929 [jetty-http-spi] Fix Multi-Value Response Headers
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java
  jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestSPIServer.java
Labels: Bug

#12942 Backport tracking pool improvements from 12.1.x
  jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
Labels: Enhancement

#12946 `IteratingCallback.iterate()` should be a no-op when closed or aborted
  jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java
Labels: Bug
