Repository jetty/jetty.project, pull requests merged in 2025-08, with the labels that each got.

#13446 jetty 12.1 merge 12.0
  VERSION.txt
Labels: Build

#13458 Issue #13457 threadsafe access to @HandlesTypes values
  jetty-ee10/jetty-ee10-annotations/src/main/java/org/eclipse/jetty/ee10/annotations/AnnotationConfiguration.java
  jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/AnnotationConfiguration.java
Labels: Bug

#13381 Fixes #13375 - WebSocketClient attempts to use HTTP/2 on servers without SETTINGS_ENABLE_CONNECT_PROTOCOL
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRedirector.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Origin.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/RetryableRequestException.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportOverHTTP.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java
  jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/HttpClientTransportOverFCGI.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/HttpClientTransportOverHTTP2.java
  jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java
  jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/HttpClientTransportOverHTTP3.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTimeoutTest.java
  jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTransportDynamicTest.java
  jetty-core/jetty-websocket/jetty-websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/CoreClientUpgradeRequest.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketOverHTTP2Test.java
  jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/resources/jetty-logging.properties
  jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
  jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/WebSocketOverHTTP2Test.java
Labels: build-all-tests

#13485 [jetty-http-spi] Add Https Implementation
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServerProvider.java
  jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpsParameters.java
  jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/TestSPIServer.java
  jetty-core/jetty-http-spi/src/test/resources/keystore.jks
Labels: Enhancement

#13533 Fixes StackOverflowError in redirect tests.
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRedirector.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConversation.java
  jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientRedirectTest.java
  jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
Labels: Test
